### ISSUE TITLE
Please install lightly package using pip install lightly

### ISSUE THREAD

**Issue by Ashufet** [Kaggle/docker-python#1001]
I tried to install in notebook but could not. Getting timeout issues.

**Comment by djherbis** [comment]
@Ashufet did you turn on internet for your notebook?

**Comment by Ashufet** [comment]
@djherbis - I want to use this package in offline mode. So I have uploaded the whl file as data and tried pip install but getting issues.

Can you please install it in docker environment.

**Comment by Philmod** [comment]
Hi,

Unfortunately this package doesn't meet one of our requirements (1000+ stars) to be added to the base image.
