### ISSUE TITLE
Requesting einops package for python

### ISSUE THREAD

**Issue by hadaev8** [Kaggle/docker-python#1012]

**Comment by rosbo** [comment]
Hi @hadaev8,

I suggest you install it in your Kaggle internet-enabled notebook using `!pip install einops`: https://github.com/Kaggle/docker-python/wiki/Missing-Packages

I will leave this request open and consider including it if many people are adding `+1` to the issue.

Thank you

**Comment by s-rog** [comment]
Seems like einops was added to the tpu image somewhat recently, can it be added to the python image as well?

**Comment by s-rog** [comment]
Ah I see, my mistake.
