### ISSUE TITLE
CUDA toolkit libraries not found.

### ISSUE THREAD

**Issue by Joel1177** [Kaggle/docker-python#1016]
Can't use GPU  because I think there is no CUDA toolkit installed.
When I run this command given below in the notebook I can then use GPU. Can you integrate the codes along with dockerfile?

```
!apt-get install sudo -y
!sudo apt-get update
!DEBIAN_FRONTEND=noninteractive!sudo apt-get -y install cuda

```
Fix this issue.

**Comment by czm1123** [comment]
I think it is to be done. Because installing CUDA toolkit using those commands take away 6 or 7 minutes. Because of this additional GPU usage is gone. Fix this.

**Comment by Philmod** [comment]
CUDA is installed in the GPU image: https://github.com/Kaggle/docker-python/blob/master/gpu.Dockerfile
