### ISSUE TITLE
ModuleNotFoundError: No module named 'spacy_readability' on Save and Commit

### ISSUE THREAD

**Issue by iskander-akhmetov** [Kaggle/docker-python#1023]
Hi!

When I work on my Kaggle notebook, I install the 'spacy_readability' module through '!pip install spacy_readability', and everything works fine. But when I try to save and commit to get the script output for the submission, it shows me the 'ModuleNotFoundError: No module named 'spacy_readability' error in the logs.

So could you please include the 'spacy_readability' module in the docker?

**Comment by djherbis** [comment]
@iskander-akhmetov Did you keep the pip install cell when you ran save & commit? Do you have a minimal notebook you can share that reproduces this issue?

This should normally work without needing to install in the base image.
