### ISSUE TITLE
Upgrade wandb to 0.10.32

### ISSUE THREAD

**Issue by bsridatta** [Kaggle/docker-python#1030]
running multiple experiments in a loop, like training many folds, only one run gets monitored. This is specific to using wandb in Notebooks. The latest version resolves that. 

Once could install new package but it required restarting the kernel, so there is no workaround to commit the notebook.

**Comment by rosbo** [comment]
Hi @bsridatta,

We will release a new version of our image next week. I checked and `wandb` 0.10.33 will be installed on the new image.

Thank you for flagging.

**Comment by bsridatta** [comment]
Awesome, thanks!
