### ISSUE TITLE
Add HDBSCAN and pyclustering to docker file

### ISSUE THREAD

**Issue by PeteBleackley** [Kaggle/docker-python#1055]
- [HDBSCAN](https://hdbscan.readthedocs.io) enables fast clustering of large dataset
- [pyclustering](https://pyclustering.github.io/docs/0.8.2/html/index.html) provides clustering methods (such as Xmeans) which are not found in scikit-learn

**Comment by rosbo** [comment]
Closing, see reason in PR.
