### ISSUE TITLE
Update fastai to latest version

### ISSUE THREAD

**Issue by kurianbenoy** [Kaggle/docker-python#1059]
- The fastai version is a bit outdated(2.2.7, while current version is 2.4.1). Can you please update to the latest version along with pytorch upgrade planned #984

**Comment by rosbo** [comment]
Hi @kurianbenoy,

I am waiting on one package to support CUDA 11.1+ to upgrade pytorch to 1.8.1 and fastai will be updated to the latest version in the same upgrade.

Thank you

**Comment by roboserg** [comment]
Waiting for fastai 2.5. as well, can not submit my code with the no internet competition.
