### ISSUE TITLE
GPU docker image does not find keras

### ISSUE THREAD

**Issue by marketneutral** [Kaggle/docker-python#1070]
I have used the CPU docker image extensively and am trying to migrate to the GPU one. I am having an issue with just the basics.

- I am running Ubuntu 20.04
- Docker version 20.10.7

I try the following sequence

- `docker pull gcr.io/kaggle-gpu-images:v102`
- `docker run -it --gpus all gcr.io/kaggle-gpu-images/python:v102 /bin/bash`
- `nvidia-smi` is fine... all looks good
- `ipython`
- `import keras`

this throws

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-88d96843a926> in <module>
----> 1 import keras

ModuleNotFoundError: No module named 'keras'
```

on the Kaggle site, this works fine with GPU enabled

![image](https://user-images.githubusercontent.com/16124573/131596495-a21bcfde-ad1c-42d6-a0f7-a53102ded11b.png)

I should note that I *can* import other libraries locally (e.g., `import torch` works fine).

Do you have an idea of what is happening to cause this issue?

Thank you.

**Comment by rosbo** [comment]
Hi @marketneutral,

We've removed multi-backend Keras from our base image since it has been discontinued. See #1045.

We will upgrade to TensorFlow 2.6 soon and I was hitting issue with multi-backend Keras + TF 2.6.

You should use `tf.keras` instead.

Thank you
