### ISSUE TITLE
Please install Rtree

### ISSUE THREAD

**Issue by jbcollins-spatially** [Kaggle/docker-python#108]
It would be great to have the "Rtree" package available for kaggle python kernels. It implements spatial indexing, which can speed up a lot of types of geospatial processing by a couple of orders of magnitude.  Thanks!

**Comment by nerdcha** [comment]
Looks like it depends on `libspatialindex`, which is nontrivial to install. We'll see about getting it working in due course. Thanks for the suggestion!

**Comment by shotleft** [comment]
Just wondering if there is any news on this one? I tried using / installing yesterday on Kaggle and was not able to complete the operation successfully? The Center for Policing Equity challenge would _really_ benefit from use of spatial joins :)

**Comment by perjonasam** [comment]
+1 on this. Would be very useful to be able to do spatial joins using geopandas, thus rtree is needed. Will look into other way of doing it in the meantime. Any suggestions are highly appreciated.
