### ISSUE TITLE
Is it OK to use kaggle docker in company (anaconda license issue)?

### ISSUE THREAD

**Issue by tomooinubushi** [Kaggle/docker-python#1096]
I have posted this question in [kaggle forum](https://www.kaggle.com/general/286639), but could not get any answers. I am afraid my question is too noob.
I want to use kaggle docker in my company, because it is very convenient tool for DS/ML. 
I know that kaggle docker itself is [free for commercial use](https://github.com/Kaggle/docker-python/blob/main/LICENSE), but I notice that [anaconda is not](https://www.anaconda.com/blog/anaconda-commercial-edition-faq).
In my understanding, if people in company with > 200 employees want to use kaggle docker, they have to buy anaconda license, because kaggle docker uses conda default repository.

- Is my understanding correct?
- If correct, is it possile to create _free_ version of kaggle docker (e.g., miniconda + conda-forge without default repo)?

I believe that many people have already used kaggle docker in company (e.g., a company which hosts a competition). Correct me if I am wrong.

**Comment by calderjo** [comment]
Outdated bug, with no follow up, 

not related to our docker image in terms reporting issues or feedback.

will close this out
