### ISSUE TITLE
Any chance of upgrading from CUDA 11.0 to 11.1? (installing PyG with pip takes >1 hour)

### ISSUE THREAD

**Issue by brunoklaus** [Kaggle/docker-python#1098]
This is mostly related to Pytorch Geometric. From what i understand, issue  #675 is unresolved due to issues with GPU tests. Fair enough, so I tried to use the following command on Kaggle Notebooks:

``!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cu110.html``

Unfortunately, this takes over 1 hour to install the packages, mostly building the wheel files for _torch-sparse, torch-cluster, torch-spline-conv_ (some of which are required when importing ``torch_geometric``). I believe that this is something related to the CUDA 11.0 version of these packages, given that I had a similar problem locally on my machine. On the other hand, if you run the following on Google Colab (currently with CUDA 11.1) or my own machine with CUDA 11.1:

``!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cu111.html``

, it takes only a few seconds. 

Installing the CPU-only version  of PyG does work in Kaggle Notebooks, but it's inefficient to the point that waiting 1 hour at the start may still better in the long run.

**Comment by rosbo** [comment]
Hi @brunoklaus,

We base our environment on [Google's Deep Learning containers](https://cloud.google.com/deep-learning-containers).

For GPU, they use CUDA 11.0 for TensorFlow 2.6. Soon, we will upgrade to the TensorFlow 2.7 which uses CUDA 11.3.

With the new CUDA compatibility support, I believe torch build for CUDA 11.1 should work with CUDA 11.3

**Comment by darien-schettler** [comment]
Why is this closed? The current Kaggle GPU Kernel is still only CUDA 11.0.

```
!nvcc --version
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by jakirkham** [comment]
Indeed it looks like CUDA 11.0 is still used here (please see below). Could someone please reopen this issue?

https://github.com/Kaggle/docker-python/blob/029dea1fc47b696983e60fd0f6d71f5cfeb4ea53/config.txt#L11L12

**Comment by jaimergp** [comment]
The [release notes for Google Deep Learning containers](https://cloud.google.com/deep-learning-containers/docs/release-notes) even state:

> February 28, 2022
> M90 Release
> 
> - CUDA has been upgraded from 11.3.0 to 11.3.1 to address some NCCL issues.
> - GPU TensorFlow containers are available and have a significantly smaller size.
> - TensorFlow 2.7 containers are re-released.

So it has been available for a while, it looks like?

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

Is this then just a matter of updating the config linked above? What else would that entail?

**Comment by rosbo** [comment]
It actually entails a lot given the large number of packages installed on our image.

@djherbis is hard at work trying to complete this upgrade. You can follow his progress on this PR: https://github.com/Kaggle/docker-python/pull/1182

**Comment by jakirkham** [comment]
Gotcha thanks for the additional context. Will start reading up on that PR
