### ISSUE TITLE
Upgrade Jupyterlab to be able to disable document-wide history

### ISSUE THREAD

**Issue by RafalSkolasinski** [Kaggle/docker-python#1103]
## 🚀 Feature

Upgrade Jupyterlab to 3.2.x

### Motivation

Jupyterlab 3.1 changed a way the undo/redo behaves. Jupyterlab 3.2 brings in flag that allows to go back to prior behaviour. 

This probably do not affect kernels running on Kaggle itself (not sure though) but would be quite nice for users of docker images.

### Additional context

https://github.com/jupyterlab/jupyterlab/issues/10791

**Comment by djherbis** [comment]
Jupyterlab version installed in the latest released images is 3.6.3
