### ISSUE TITLE
Surprise library

### ISSUE THREAD

**Issue by ResidentMario** [Kaggle/docker-python#111]
I would love to see the [`surprise`](https://github.com/NicolasHug/Surprise) package available in the env.  It seems to only rely on `numpy` (?), so it should be another `pip install` one-liner in the image.

I have a notebook application in mind for it.

**Comment by nerdcha** [comment]
We've added it in https://github.com/Kaggle/docker-python/commit/f546dde02b0e837af3496820737299c937fd91a9, and it should be deployed shortly.
