### ISSUE TITLE
python crash with "Illegal instruction" on  import tensorflow in Docker Personal for Mac

### ISSUE THREAD

**Issue by talk2dfox** [Kaggle/docker-python#1117]
## 🐛 Bug

Whenever I try to "import tensorflow" from the included python 3.7, python exits with the message "Illegal instruction".

### To Reproduce

Specs (not sure which are critical to reproduce):

#### Host machine
mac mini (late 2012)
2.6GHz 4-core Intel i7 (Ivy Bridge, so it should support the AVX instructions per https://www.tensorflow.org/install/pip#hardware-requirements)
16 GB RAM.  

#### Docker
Docker Desktop (Personal) 4.3.2 with Docker engine 20.10.11
allocating 3 cores, 8 GB RAM, 4 GB swap, 75GB free disk space (above the 21G for the image)

#### Image
docker pull kaggle/python:latest on 12/27/21
build-date: 20211129-122800
git commit: eaf724136b95aaa788045b78b7a38a3e60389b9c
TensorFlow 2.6 (CPU)
tensorflow container-name = tf2-cpu/2-6 (tf-cpu2.2-6:nightly-2021-11-17

### Expected behavior

import tensorflow

should succeed

**Comment by talk2dfox** [comment]
sysctl -a | grep machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C

so AVX1.0 instructions are supported.

**Comment by talk2dfox** [comment]
was able to install pre-built version of 2.7 from

https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.7.0-cp37-cp37m-macosx_10_11_x86_64.whl

will check for pre-build 2.6 or otherwise try to build myself

**Comment by Philmod** [comment]
Hi!

How do you run the docker image?
