### ISSUE TITLE
Please add GPFlow in Kaggle

### ISSUE THREAD

**Issue by tamoghnabh** [Kaggle/docker-python#1133]
## 🚀 Feature

GPflow is a fantastic library for performing Bayesian Inference based regression and classification. Unfortunately installing it by pip install creates dependency conflicts and it doesn't work.

**Comment by calderjo** [comment]
In an effort to limit the size of our Docker Python image and ease the maintenance burden, The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image.

Thank you for understanding!
