### ISSUE TITLE
Update pytorch to 1.11

### ISSUE THREAD

**Issue by SomeoneSerge** [Kaggle/docker-python#1148]
Kaggle currently uses pytorch 1.9, the latest release is 1.11, that's two releases behind: perhaps it's time! 🚀

**Comment by Philmod** [comment]
It was upgraded in this [release](https://github.com/Kaggle/docker-python/releases/tag/2526686e2bde6b3af5288661aa6e5c0c5b470412eaf284a0017a4c73c6a9bd89).
