### ISSUE TITLE
from sklearn_extra.cluster import KMedoids

### ISSUE THREAD

**Issue by SylwiaKmiec** [Kaggle/docker-python#1149]
Hi There,
trying to post my notebook but getting error: ModuleNotFoundError: No module named 'sklearn_extra'
can you pls assist?

**Comment by Philmod** [comment]
Hi!

This package is not installed in the base image, but you can install it with `pip`:

`!pip install scikit-learn-extra`

See https://github.com/Kaggle/docker-python/wiki/Missing-Packages
