### ISSUE TITLE
matplotlib imshow function does not work

### ISSUE THREAD

**Issue by maryamag85** [Kaggle/docker-python#115]
I am using kaggle/python image in docker to run a kaggle kernel but imshow does not work on my system. nothing is shown, even no plot window pops up. I have the ubuntu 16, pycharm 2017 connected to the latest docker version. any suggestion?

**Comment by nerdcha** [comment]
Ah yes, anything graphics-related can get tricky when containers are involved. I'm not an expert on that, but if you want to explore a general solution, there are ideas [here](https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container) and [here](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/).

The solution that I myself use is a bit hacky, but it works. If you start a Jupyter notebook server inside the container, you can connect to it using a web browser, and then graphics and plot output will show up in the notebook as you edit. You'd do that with something like `docker run -v $PWD:/tmp/working -w=/tmp/working -p 8888:8888 --rm -it kaggle/python jupyter notebook --no-browser --ip="\*" --notebook-dir=/tmp/working` on the host, and then pointing your browser to `http://localhost:8888`.

Hope that helps!
