### ISSUE TITLE
[Feature Request]Ability to use devtools::install_github command in R kernels

### ISSUE THREAD

**Issue by gvyshnya** [Kaggle/docker-python#116]
It would be nice to use devtools::install_github command within a R code/kernel (to install a package other than from CRAN).

**Note**: right now, issues like described in https://www.kaggle.com/c/kobe-bryant-shot-selection/discussion/20796 are observed when attempted to invoke devtools::install_github

**Comment by nerdcha** [comment]
Nice idea, thanks for mentioning it! We're hoping to offer something like that in the near future.
