### ISSUE TITLE
Failed to dlopen some gpu images

### ISSUE THREAD

**Issue by HSchmale16** [Kaggle/docker-python#1164]
## 🐛 Bug

It appears to be missing some GPU libraries based on what the output of the notebook puts out. Don't know how to fix.

### To Reproduce

Create an empty notebook on kaggle, with the gpu accelerator attached. Add the following as a code block

     >  print(tf.config.list_physical_devices('GPU'))

### Expected behavior

A list with at least 1 gpu device.

### Additional context

As of 23:38 EST May 21st, 2022 on kaggle, I'm not able to run code on the GPU and things are running slow.

**Comment by HSchmale16** [comment]
Here's some additional error messages.



```
94 | 2022-05-22 03:31:41.057907: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
-- | --
105.0s | 95 | 2022-05-22 03:31:41.087295: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

**Comment by Philmod** [comment]
Hi @HSchmale16 ,

I do see a GPU: 

![Screen Shot 2022-06-02 at 10 17 26 AM](https://user-images.githubusercontent.com/818310/171650399-381880c2-9d24-4ded-a982-2b11a579298e.png)

Did you select the GPU Accelerator in the Settings? 

![Screen Shot 2022-06-02 at 10 18 10 AM](https://user-images.githubusercontent.com/818310/171650539-b0bc7666-da68-4f17-bae6-243f91c0b337.png)
