### ISSUE TITLE
Pandas profiling import error

### ISSUE THREAD

**Issue by harisonmg** [Kaggle/docker-python#1174]
## 🐛 Bug

One cannot import `ProfileReport` from `pandas_profiling`

### To Reproduce
Run this code from any Kaggle notebook
```
from pandas_profiling import ProfileReport
```

### Expected behaviour

`ProfileReport` should be imported successfully

### Additional context

There seems to be a bug in pandas profiling 2.4 that was probably fixed in the latest version (3.2). 
I'd recommend upgrading this dependency because the import works after updating pandas profiling with `pip install -U pandas-profiling`. However, this requires restarting the notebook, which does not work with the __Save All & Run__ notebooks feature.

**Comment by Philmod** [comment]
The latest version of the package will be released this week. https://github.com/Kaggle/docker-python/releases/tag/5d709c1a09783ce8de6c7f777f1267bc4d9735608aff695cb13227d5d0b928b5

Feel free to reopen if this is not fixed by next week.

Thanks,
Philippe
