### ISSUE TITLE
Jax is not compiled for GPU

### ISSUE THREAD

**Issue by Selimonder** [Kaggle/docker-python#1178]
## 🐛 Bug

<img width="746" alt="image" src="https://user-images.githubusercontent.com/36644230/178949306-03fc6087-d4f7-47ca-bd9b-d20b465b4176.png">

Expecting to see a GPU device on backend, but seeing CPU instead.

This wasn't an issue on earlier environments. Also, thanks for making Flax a default package 🙌

**Comment by Selimonder** [comment]
temporary fix for offline environment (latest as 14th of July): use output data of https://www.kaggle.com/realsleim/jax-wheels

execute following in the beginning of your notebook

> !pip install -U ../input/jax-wheels/pip-22.1.2-py3-none-any.whl --no-index --find-links ../input/jax-wheels/
> !pip install ../input/jax-wheels/jaxlib-0.3.14+cuda11.cudnn82-cp37-none-manylinux2014_x86_64.whl --no-index --find-links ../input/jax-wheels/ 

result 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/36644230/178956939-efe47c04-e242-42c8-9572-1cf480e04214.png">

**Comment by rosbo** [comment]
Hi @Selimonder,

Looks like we install the JAX GPU package for the wrong cudnn version: https://github.com/Kaggle/docker-python/blob/029dea1fc47b696983e60fd0f6d71f5cfeb4ea53/Dockerfile.tmpl#L126-L127

I will fix this and add a test to prevent regression on this.

Thanks for flagging.

**Comment by rosbo** [comment]
I found the issue: the CUDA releases have been moved to: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html (before they were available at https://storage.googleapis.com/jax-releases/jax_releases.html).

**Comment by rosbo** [comment]
@Selimonder A new image with the fix will be released tomorrow.
