### ISSUE TITLE
Can not found "input" folder

### ISSUE THREAD

**Issue by acheshkov** [Kaggle/docker-python#118]
Hello, 

executing a kernel i got an error **FileNotFoundError**. It happens because of the container does not have **input** folder with kaggle's datasets.

**Comment by ResidentMario** [comment]
I think this was a temporary error that was patched last week. However this is only AFAIK.

**Comment by nerdcha** [comment]
You can check the paths to your input files by browsing through the "Input Files" widget in the notebook editor, or the "Data" tab of the script editor.
