### ISSUE TITLE
Upgrade Python version to Python 3.8 (adhere to NEP 29)

### ISSUE THREAD

**Issue by lithomas1** [Kaggle/docker-python#1180]
## 🚀 Feature

The python version in Kaggle kernels should be upgraded to Python 3.8. Additionally, Kaggle should try to adhere to NEP 29.

### Motivation

Pandas and numpy, and many other packages in the scientific python ecosystem have both dropped support for Python 3.8 as per NEP 29(which lists a recommended support schedule for Python/numpy versions). https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

The python docker images should adhere to this schedule to avoid falling many versions behind in key packages(e.g. pandas is already one minor version behind).

### Additional context

I noticed this after surprisingly hitting a bug in pandas fixed in pandas 1.4.0, which led me to notice that the pandas version on kaggle kernels is still 1.3.5.

**Comment by Philmod** [comment]
Hey @lithomas1,

Upgrading to Python 3.8+ is something we would like to do, but we are depending on a base image that doesn't have it yet. They say it should come sometimes in H2 2022 hopefully.

**Comment by jakirkham** [comment]
Which base image is being used?

Poking around am seeing this, but maybe I'm missing things

https://github.com/Kaggle/docker-python/blob/029dea1fc47b696983e60fd0f6d71f5cfeb4ea53/config.txt#L1-L2

**Comment by lithomas1** [comment]
That seems right(would be nice to get this confirmed though).
@Philmod Is there a way to get in touch with the Google team that makes the images and pass on the word about NEP 29 to them? Python 3.8 is also going to be dropped somewhat soon(after 4/14/2023)

**Comment by MarMarhoun** [comment]
This issue is still open and I have an issue related to the python version which should be updated.

**Comment by sonphantrung** [comment]
#1231 It's coming guys

**Comment by lithomas1** [comment]
@djherbis 
Is there a timeline for when the TPU images will be upgraded to Python 3.10?

It looks like they are still on Python 3.8.

**Comment by djherbis** [comment]
@lithomas1 Yeah the goal is to jump to 3.10, I have an unpushed branch attempting this that doesn't build successfully yet but once it does we'll make the jump.

Probably worth its own issue if you want further discussion.

**Comment by lithomas1** [comment]
Thanks for the quick reply. I opened #1312 to track this. 

It'd be great to have more info about what's going wrong (maybe the community can help debug?) - https://github.com/Kaggle/docker-python/commit/57233453a0d601d5053b266b501db3146128fd70  links to a Google issue.
