### ISSUE TITLE
pythreejs is installed, but widgets are not shown

### ISSUE THREAD

**Issue by francesco-ballarin** [Kaggle/docker-python#1190]
## 🐛 Bug

I would like to use `pythreejs` widgets in a kaggle notebook. The `pythreejs` package is indeed installed in the docker image, but no widgets are shown when running notebooks on `https://www.kaggle.com/code/`.

### To Reproduce

```
# Cell 1: confirm that pythreejs is installed
!pip show pythreejs
```
```
# Cell 2: confirm that its jupyter notebook extension is installed
!jupyter nbextension list
```
```
# Cell 3: confirm that import works
import pythreejs
```
```
# Cell 4: no widget shows up, only "Loading widget..."
pythreejs.BoxGeometry(
    width=5,
    height=10,
    depth=15,
    widthSegments=5,
    heightSegments=10,
    depthSegments=15)
```

### Expected behavior

An interactive widget, as in the third cell of https://pythreejs.readthedocs.io/en/stable/examples/Geometries.html

### Additional context

I'd be happy to add this code as a test.

**Comment by djherbis** [comment]
Installing widget packages usually won't just work because Jupyter has to reboot to use and serve the widget code.

We also use a statically built and deployed Jupyter so installing widgets actually has to be done as part of our Jupyter build as well.

**Comment by djherbis** [comment]
The docker image doesn't serve the Jupyter frontend, just the Jupyter backend, so even having it pre-installed doesn't mean the widget will work.
This makes widget support fairly inconsistent because the JS they might need isn't necessarily served by the fronted.

Interactive Jupyter error (due to the module being missing from the static frontend build):
```
10:09:09.019 manager.js:319 Uncaught (in promise) Error: Module jupyter-threejs, semver range ^2.1.0 is not registered as a widget module
    at k.loadClass (manager.js:319:39)
    at k.<anonymous> (manager-base.js:264:84)
    at l (manager-base.js:46:45)
    at Object.next (manager-base.js:28:16)
    at manager-base.js:23:28
    at new Promise (<anonymous>)
    at Rtm6.S (manager-base.js:16:47)
    at e._make_model (manager-base.js:258:48)
    at k.<anonymous> (manager-base.js:249:30)
    at l (manager-base.js:46:45)
```

It does work with Save Versions though:
https://www.kaggle.com/code/herbison/pythreejs/notebook

Do you need it in the interactive editor? If so, we can look into installing it in the static editor to see if that fixes the issue.

**Comment by francesco-ballarin** [comment]
Thanks @djherbis for looking into this!

> Do you need it in the interactive editor? 

Yes, myself (and @ediemiglio) would love to have `pythreejs` in the interactive editor, if it were possible.

**Comment by francesco-ballarin** [comment]
My main motivation was using `pythreejs` within `pyvista`. Since the `pythreejs` backend was removed from `pyvista` in https://github.com/pyvista/pyvista/pull/4687, I don't have any further interest in this, hence I am closing this. Feel free to reopen if someone else is interested in `pythreejs` on its own, rather than within `pyvista`.
