### ISSUE TITLE
Request new package `functorch`

### ISSUE THREAD

**Issue by submartingales** [Kaggle/docker-python#1191]
`functorch` which provides JAX-like API for PyTorch, can be used for acceleration of training and inference in many use cases.  

However, hard as I try to install it via something like
```
!pip install functorch
```
it may break the cuda version of `torch` and later code will fail due to cuda error.

Therefore, I hope the kaggle staff can in some way add `functorch` to the notebook environment.

**Comment by djherbis** [comment]
Seems popular enough:
https://github.com/pytorch/functorch

We're working on some major upgrades first, we can evaluate how easy it is to include after those are done.

**Comment by calderjo** [comment]
In an effort to limit the size of our Docker Python image and ease the maintenance burden, The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image.

Thank you for understanding!
