### ISSUE TITLE
Cannot import flax after installing while using TPU

### ISSUE THREAD

**Issue by deadsoul44** [Kaggle/docker-python#1192]
## 🐛 Bug

cannot import flax after installing (TPU env)

ImportError Traceback (most recent call last)
/tmp/ipykernel_19/1030813116.py in
5 import tensorflow_datasets as tfds
6 from absl import logging
----> 7 import flax
8 from flax import linen as nn
9 from flax.training import train_state

/opt/conda/lib/python3.7/site-packages/flax/init.py in
16 """Flax API."""
17
---> 18 from . import core
19 from . import jax_utils
20 from . import linen

/opt/conda/lib/python3.7/site-packages/flax/core/init.py in
26 )
27
---> 28 from .scope import (
29 Scope as Scope,
30 Array as Array,

/opt/conda/lib/python3.7/site-packages/flax/core/scope.py in
26 from flax import config
27 from flax import errors
---> 28 from flax import struct
29 from flax import traceback_util
30 from .frozen_dict import freeze

/opt/conda/lib/python3.7/site-packages/flax/struct.py in
23
24 import jax
---> 25 from typing_extensions import dataclass_transform # pytype: disable=not-supported-yet
26
27

ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/opt/conda/lib/python3.7/site-packages/typing_extensions.py)

### To Reproduce

!pip install flax
import flax

### Expected behavior

Flax should be imported

### Additional context

The related issue is below. 

https://github.com/google/flax/issues/2605

**Comment by djherbis** [comment]
@deadsoul44 We normally don't guarantee support for pip installed packages in our env.

Basically the env is very complex, and getting all the packages to install safely alongside one another is difficult.
A prime example is the PR to upgrade pytorch which has taken me months and I'm still not in a place to merge it yet.

All that being said, if you can wait a little longer I have something I've been working on which should give you access to flax + TPUs.

**Comment by djherbis** [comment]
@deadsoul44 Can you try using TPU 1VM v3-8 Accelerator option? It should come pre-installed with Flax now.
Going forward this will be the main way to use TPUs. Let me know if that works for you :)

**Comment by deadsoul44** [comment]
Now, I get this error. This import works on CPU.

```
ImportError                               Traceback (most recent call last)
Cell In [21], line 29
     27 from seaborn import pairplot
     28 from scipy.stats import zscore 
---> 29 from flax.linen import celu, elu, gelu, glu, hard_sigmoid, hard_silu, hard_swish, hard_tanh, leaky_relu, log_sigmoid, relu, relu6, selu, sigmoid, silu, soft_sign, softplus, swish, tanh, PReLU
     30 from random import shuffle
     32 ModuleDef = Any

ImportError: cannot import name 'hard_sigmoid' from 'flax.linen' (/usr/local/lib/python3.8/site-packages/flax/linen/__init__.py)
```

**Comment by djherbis** [comment]
@deadsoul44 Does the latest TPU VM env fit your needs? It should come with flax installed.
