### ISSUE TITLE
Update torch to 1.13.1

### ISSUE THREAD

**Issue by schmidt-jake** [Kaggle/docker-python#1203]
## 🚀 Feature

Release a new docker image with `torch` bumped to 1.13.1 (and related packages such as torchvision also bumped for compatibility).

### Motivation

To allow usage of new torch features, such as the new `torch.data` APIs.

**Comment by schmidt-jake** [comment]
@kaggleteam It looks like [this](https://github.com/Kaggle/docker-python/releases/tag/f918adcfe4ef8a5baf354d0177648ff437e8133e49d1e30c8b7ba0280595856a) release bumped torch to 1.13.0 for TPU... any chance we could get this for GPU/CPU too?

**Comment by djherbis** [comment]
I upgraded Kaggle to 1.13 for GPU/CPU as part of the tf2.11 upgrade:
https://github.com/Kaggle/docker-python/pull/1216
