### ISSUE TITLE
🐛 v129 - GPU torch 1.13.0 🥳 But CUDA 11.4 😐

### ISSUE THREAD

**Issue by camenduru** [Kaggle/docker-python#1224]
https://github.com/pytorch/pytorch/releases/tag/v1.13.0

>We are excited to announce the release of PyTorch 1.13! This includes stable versions of BetterTransformer. We deprecated CUDA 10.2 and 11.3 and completed migration of CUDA 11.6 and 11.7

If I turn back to 
`!pip install -q torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113`

now I am getting this 🤪

![Screenshot 2023-03-01 041414](https://user-images.githubusercontent.com/54370274/222019785-976def65-5127-454a-8fd4-c30332a79243.png)

```py
OSError: /opt/conda/lib/python3.7/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
```

**Comment by camenduru** [comment]
If it's not possible to fix this, please tell me how I can update to CUDA 11.6

**Comment by camenduru** [comment]
Please update your drivers to at least CUDA 11.6 if possible.

Colab 12.0 🥳

![Screenshot 2023-03-01 044726](https://user-images.githubusercontent.com/54370274/222024232-258e746a-d781-4077-b19f-6198409ad3c7.png)

Kaggle 11.4.0 (June 2021)  😐

![Screenshot 2023-03-01 044808](https://user-images.githubusercontent.com/54370274/222024095-c2a18d3e-db81-452f-babb-e327ee7792dd.png)

**Comment by camenduru** [comment]
![Screenshot 2023-03-01 050515](https://user-images.githubusercontent.com/54370274/222026058-2c3a57f7-891c-40d7-942a-9773b7b1c7c8.png)

```py
OSError: /opt/conda/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
```

**Comment by camenduru** [comment]
why @djherbis just why

**Comment by djherbis** [comment]
@camenduru our versions of tf and cuda are pinned by our base image so we don't manage those.
I will upgrade them whenever the next base upgrades though, hopefully soon 🤞 

If you're referring to your Kaggle account though, I took a look and unbanned. 
You may want avoid the crowd that's forking your stable-diffusion notebook though, so much banned activity off that notebook flagged your account.

**Comment by camenduru** [comment]
This is a serious issue. Let's ask @benhamner for advice. Hi @benhamner 👋 I have a question. Is my statement 'You cannot ban the main repository and especially the author's account because forks are violating company guidelines' true or false? We all know in real life this is true, but Kaggle is a company and you are the rule maker.

If @benhamner says false, I will delete the https://www.kaggle.com/code/camenduru/stable-diffusion-webui-kaggle  If @benhamner says true, this message is for @djherbis 

I hope you are aware of how unethical your action was. You have clearly abused your administrative authority. You have deleted knowledge; you are the person who burns the books. Please be aware of how serious and wrong your action was. You are not running a cheesy game site. You cannot ban the author's account and the main repository because forks are violating company guidelines. Also, if the notebook really harms Kaggle, I will delete the notebook, but you should tell me how. I really don't understand. I am assuming people are opening multiple accounts and using free GPU; then, detect those accounts. Do not delete the knowledge. I will always remember Kaggle with this unfortunate event.

**Comment by djherbis** [comment]
@camenduru Ben's not at Kaggle anymore. 

Accidental bans happen and I unbanned you after checking. I'm not sure what else you are referring to, if you want to chat reach me at herbison@kaggle.com.
