### ISSUE TITLE
Unable to install tensorflow_similarity offline

### ISSUE THREAD

**Issue by GregBd20** [Kaggle/docker-python#1226]
Hello,

I am new to kaggle competitions. I am trying to make my first submission, and I need a package tensorflow_similarity. When I install it with internet, it works fine, but I can't install it without internet. Following advice from kaggle forum, I tried to add the installation .whl file as a dataset and install it from the file, but I receive an error

**ERROR: Could not find a version that satisfies the requirement nmslib (from tensorflow-similarity) (from versions: none)
ERROR: No matching distribution found for nmslib**

I would appreciate if you could help me with it

**Comment by jplotts** [comment]
Hi @GregBd20 - at this time, we would be unlikely to add `tensorflow_similarity` to the base image; we have to be selective with the packages installed to prevent bloat.  The best option would be to ask for help on the Kaggle Forums, either the Q&A forum or even the competition forum.  The forums likely have a lot more users who are familiar with this setup and may provide tips to solve the issue.
