### ISSUE TITLE
Kaggle's Python GPU Notebooks should not be running on Python 3.7

### ISSUE THREAD

**Issue by mayfieldmobster** [Kaggle/docker-python#1243]
## 🚀 Feature

Upgrade the default Python version of Kaggle notebooks

### Motivation

Python 3.7 was released in 2018, we are currently on Python 3.11. In order to access the most recent tools for data science and ML you usually need Python3.8 for example Pytorch2.0 requires python3.8, I feel like this isn't a big ask and would benefit everyone. 

To my understanding, the TPU notebooks already utilise Python3.8

**Comment by djherbis** [comment]
https://github.com/Kaggle/docker-python/pull/1231

We're jumping to py3.10, the release will hopefully go out this week.

**Comment by Richienb** [comment]
@djherbis It may or may not have just been 2 weeks

python 3.10 when
