### ISSUE TITLE
PySpark support for Kaggle.

### ISSUE THREAD

**Issue by komal436** [Kaggle/docker-python#125]
Can Kaggle docker support PySpark? PySpark can help to do transformation easily.

**Comment by nerdcha** [comment]
Integration with Spark and other external ETL tools is something we're eager to support in the near future. Thanks for the suggestion!

**Comment by kmader** [comment]
@komal436 since pyspark is pip installable now you should be able to install it now using the new special settings panel in Kaggle Kernels
