### ISSUE TITLE
"Run all" hangs the notebook if not scrolled to the top when executing

### ISSUE THREAD

**Issue by Carl-McBride-Ellis** [Kaggle/docker-python#1252]
## 🐛 (Possible) bug with new Docker image notebooks

It seems that when executing "Run all" in a notebook whilst the notebook is **not** scrolled to the very top of the page, after calculating a few cells (approx five or so) the notebook execution then hangs seemingly calculating  a cell (even though the cell could be as trivial as a simple print statement) *i.e.* the "calculating circle" keeps spinning.

(This seems to happen after a second "Run all" not necessarily the first one)

A notebook reload/refresh is then needed in order to resume.

**Comment by djherbis** [comment]
@Carl-McBride-Ellis I've been able to flaky-reproduce this (it seems to work most of the time for me, but sometimes bugs out). I think this is more of a https://www.kaggle.com/discussions/product-feedback issue though, I don't think it has anything to do with the image and is more likely a javascript bug in the run all button.

**Comment by Carl-McBride-Ellis** [comment]
Thanks for the prompt reply. 

I should say that this has only started happening for me when using the new image.
I shall post as a Product Feedback as per your suggestion.

**Comment by Carl-McBride-Ellis** [comment]
Closed and translated to kaggle "Product Feedback".

**Comment by djherbis** [comment]
Thanks! I think the new image may cause it, but the issue might be that the editor needs upgrades to handle the upgraded backend.
