### ISSUE TITLE
Strange wiki page

### ISSUE THREAD

**Issue by panozzaj** [Kaggle/docker-python#1263]
## 🐛 Bug

The following wiki page seems out of place: https://github.com/Kaggle/docker-python/wiki/The-holy-city-bitcoin

### To Reproduce

Go to that URL.

### Expected behavior

There's nothing about bitcoin in the wiki

### Additional context

Not sure how it got here? Thanks!

**Comment by Philmod** [comment]
Thanks, deleted.

**Comment by panozzaj** [comment]
Thanks for the quick turnaround!
