### ISSUE TITLE
Add `peft` package

### ISSUE THREAD

**Issue by submartingales** [Kaggle/docker-python#1264]
Hi, could you evaluate the possibility of adding [peft](https://github.com/huggingface/peft) to the image. This package is quite popular and generic. The urge to install comes from kernel-only competitions that don't allow internet connection.

**Comment by djherbis** [comment]
@submartingales Would you consider trying a PR + tests to install it?

**Comment by submartingales** [comment]
@djherbis I am somewhat busy now but I think I am happy to do that later.

**Comment by calderjo** [comment]
In an effort to limit the size of our Docker Python image and ease the maintenance burden, The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image.

Thank you for understanding!
