### ISSUE TITLE
dask-ml

### ISSUE THREAD

**Issue by westurner** [Kaggle/docker-python#128]
### Dask-ml

> Dask-ML enables parallel and distributed machine learning using Dask alongside existing machine learning libraries like Scikit-Learn.

- Src: https://github.com/dask/dask-ml
- Docs: https://dask-ml.readthedocs.io/en/latest/

...

- XGBoost, TensorFlow, scikit-learn

**Comment by nerdcha** [comment]
Looks interesting! Am I right in thinking that it adds value on clusters, rather than multicore single machines? (We only support single VMs right now, but will add clusters down the track.)

**Comment by westurner** [comment]
On Thursday, November 16, 2017, Jamie Hall <notifications@github.com> wrote:

> Looks interesting! Am I right in thinking that it adds value on clusters,
> rather than multicore single machines?
>
dask.distributed is useful for clusters.

dask is generally useful for data larger than available RAM; which, given
the recent dataset max size increase to 10gb, will be more and more common.

> (We only support single VMs right now, but will add clusters down the
> track.)
>
This image may be already be especially useful for multi-machine
computation as well.

**Comment by nerdcha** [comment]
Sorry for the delay in getting back to you. I'll add dask-ml and its xgboost extension to the image shortly. Looks like they also have an early version of a TensorFlow interface, but its pip installation is failing, so we'll have to come back to that.

**Comment by westurner** [comment]
Thanks!
