### ISSUE TITLE
pandas 21.0 -- fails reading lot of categorical values

### ISSUE THREAD

**Issue by mkagenius** [Kaggle/docker-python#131]
Would you guys mind downgrading pandas to last stable version that is 20.3 instead of 21.0 -- lot of kernels are failing because of https://github.com/pandas-dev/pandas/issues/18186

Dont know when they will fix this.

**Comment by nerdcha** [comment]
Ah, thanks for pointing that out. We'll deploy 0.20.3 shortly.

**Comment by nerdcha** [comment]
@mkagenius Ok, we've downgraded it. Thanks again for alerting us.
