### ISSUE TITLE
Upgrade TPU Python version to Python 3.10

### ISSUE THREAD

**Issue by lithomas1** [Kaggle/docker-python#1312]
```
@djherbis 
Is there a timeline for when the TPU images will be upgraded to Python 3.10?

It looks like they are still on Python 3.8.
```

_Originally posted by @lithomas1 in https://github.com/Kaggle/docker-python/issues/1180#issuecomment-1773357139_

**Comment by djherbis** [comment]
I pushed my in progress work, I think that PR at least builds successfully but I haven't tested it yet and it does drop a number of packages :(
