### ISSUE TITLE
DenMune clustering Algorithm, the latest version

### ISSUE THREAD

**Issue by egy1st** [Kaggle/docker-python#1319]
I can not install the latest version of DenMune which is 1.17.2

**Comment by Philmod** [comment]
Hi! I was able to install the latest version (`1.17.6`): https://www.kaggle.com/code/philmod/denmune/notebook

Let me know if I'm missing something

**Comment by egy1st** [comment]
![Screenshot_70](https://github.com/Kaggle/docker-python/assets/25140375/bf53dc77-c3fb-4348-94fb-2fc48d5a45c1)

**Comment by Philmod** [comment]
This version exists: https://pypi.org/project/denmune/1.17.6/

Did you turn internet on in your notebook?

**Comment by egy1st** [comment]
yes, the internet is on. 

I found that to fix it, I should use "Always use latest environment" from the environment list

![Screenshot_71](https://github.com/Kaggle/docker-python/assets/25140375/167ee59a-9517-49fd-adbf-4cbe91ce6488)
