### ISSUE TITLE
CUML version clashes with new Pandas version

### ISSUE THREAD

**Issue by snat-s** [Kaggle/docker-python#1321]
## 🐛 Bug

The new version of pandas broke the CUML version.

### To Reproduce

Import CUML in a new environment.

### Expected behavior

It should import normally, but it crashes and says that there is a problem with the pandas version.

### Additional context

This conversation says how to solve it, but it feels like a little hack: https://www.kaggle.com/competitions/llm-detect-ai-generated-text/discussion/455587#2526454

**Comment by djherbis** [comment]
Thanks, its strange though, the pandas 2 upgrade happened back in Aug/Sept:
https://github.com/Kaggle/docker-python/releases/tag/13246793b8f76cf8eb794947760afce5104ab3e3c759659e3757f82c5f0c61de

So it either was working until some other change happened, or it wasn't hit until recently.

**Comment by calderjo** [comment]
this is to be addressed in https://github.com/Kaggle/docker-python/issues/1392

**Comment by calderjo** [comment]
this has been addressed!!!!!!!!!!!!!!
