### ISSUE TITLE
Please Install new package to be used in Kaggel Notebook

### ISSUE THREAD

**Issue by masun** [Kaggle/docker-python#1354]
## 🚀 Feature

Please install lftk package

### Motivation
I could not install this library while my Notebook is offline during my submission to a competition
you can find the library here:
https://github.com/brucewlee/lftk
Thank you very much

**Comment by Philmod** [comment]
Hi! Unfortunately this library doesn't meet the minimum requirements to be added to our base image.

Have you tried installing it in your notebook? https://github.com/Kaggle/docker-python/wiki/Missing-Packages
