### ISSUE TITLE
Not Able to run google generative ai models on kaggle notebook [bug] 

### ISSUE THREAD

**Issue by gunjak** [Kaggle/docker-python#1386]
## 🐛 Bug

>**Problem:** While matching google api key we are getting error.
>**Cause of problem** : google generative model default_metadata which is attribute of configure method is tuple but in your code you have declared as list.

### Image where we are getting and what is  error
![kaggle_issues](https://github.com/Kaggle/docker-python/assets/90557288/47fdae5e-8e29-4d98-8108-18838f9b68c7)

###  [link](https://github.com/Kaggle/docker-python/blob/13696526c8d64126bbd1297e45ef18a667cf23a0/patches/sitecustomize.py#L91) of your kaggle code.

I have also seen some  folks raised issue on langchain but after analyzing code I found that this issue is raising from kaggle.

Please fix this issue so that we can use google generative model on kaggle.

**Comment by calderjo** [comment]
Hi @gunjak , Please share your notebook that you are using. It helps me understand what use cases needs to be covered.

**Comment by gunjak** [comment]
I don't know how but Now the notebook is working fine with the api key.
