### ISSUE TITLE
LightAutoML library in Kaggle Kernels

### ISSUE THREAD

**Issue by alexmryzhkov** [Kaggle/docker-python#1396]
## 🚀 Feature

I would like to propose the idea to add LightAutoML (https://pypi.org/project/lightautoml/) to kaggle kernels environment

### Motivation

1. [LightAutoML GitHub repository](https://github.com/sb-ai-lab/LightAutoML) has 1k+ stars 
2. The all-time count of downloads from PyPI is about 200k
3. LightAutoML is the winner of the Kaggle AutoML GrandPrix (phase 1, May 2024):
     - [Official results](https://www.kaggle.com/competitions/playground-series-s4e5/discussion/499482)
     - [LightAutoML solution](https://www.kaggle.com/competitions/playground-series-s4e5/discussion/500700)
5. LightAutoML models (especially Tabular NNs) are used in almost every competition. For example, in the currently active HomeCredit competition many kernels are based on [Andrey Nesterov's LightAutoML kernel](https://www.kaggle.com/code/andreynesterov/home-credit-baseline-inference).

In my opinion adding LightAutoML to kaggle kernels env can help kagglers to use it in the rest of Kaggle AutoML GrandPrix and also in kernel competitions (which become extremely popular nowadays) with the submissions without internet connection.

**Comment by samvelkoch** [comment]
Nice idea. Upvote +1

**Comment by Snake-G** [comment]
and more +1 ))

**Comment by aPovidlo** [comment]
+1

**Comment by calderjo** [comment]
Hey Alexander, congrats to you and your team on reaching 1k stars!!! It's very exciting and amazing to see the work done by the community outside of Kaggle.

The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image. 

Thank you for understanding!
