### ISSUE TITLE
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by sadeep25** [Kaggle/docker-python#1405]
## 🐛 Bug
I encountered a RuntimeError while training llma2 model on Kaggle. The code that I'm executing works on the Kaggle environment 2024-04-19. but gives the following error on newly created note books.
![image](https://github.com/Kaggle/docker-python/assets/18017108/04d5ee7e-58bf-443c-882d-42113195a669)

**Comment by calderjo** [comment]
Hey, if possible, could you share your notebook with me?

it will help use find what causing this issue and get a bit more context. I suggest forking(copy) the original (working) notebook, and work from there meanwhile.

 username in kaggle is jcchavez

**Comment by calderjo** [comment]
not enough info to investigate, closing
