### ISSUE TITLE
pillow needs to be updated to the latest version

### ISSUE THREAD

**Issue by aeozyalcin** [Kaggle/docker-python#1420]
## 🚀 Feature

Current version of pillow included in the images is 9.5.0, which is way too old. Unfortunately, updating Pillow requires a kernel restart, which doesn't seem to be possible for committed runs. It would be great to update the default version up to 10.4.0.

### Motivation

Pillow 9.5.0 is having issues loading some images from my dataset, while 10.4.0 handles it perfectly fine. When I run the kernel in a draft session, and update pillow to 10.4.0, I have to restart the kernel for the update to take effect. Once restarted, I can open the images just fine in PIL 10.4.0. However, 9.5.0 is not handling all images gracefully, and gives me lots of "unidentified image" error.

### Additional context

Restarting the kernel doesn't seem to be possible on a committed run running in the background. As a result, it appears I am stuck with Pillow 9.5.0 on all of my committed runs.

**Comment by aeozyalcin** [comment]
example: Super-gradient requires PIL>=10.2.0. Even though pip is installing newer version of PIL while installing super-gradient, the Python environment continues using PIL 9.5.0 :/

**Comment by calderjo** [comment]
seems like it is currently pinned explaining why is doesn't get bumped up from 9.5.0, we can try unpinning it and see what happens. 

if you beat me to it, you can send a pr with the change.

**Comment by aeozyalcin** [comment]
@calderjo 
https://github.com/Kaggle/docker-python/pull/1422

**Comment by calderjo** [comment]
https://github.com/Kaggle/docker-python/pull/1422 

has been merge, please note it be a while until we do another release, 

thanks for your contribution, hope to see more!!
