### ISSUE TITLE
[FR] Add `mlflow` like `wandb`

### ISSUE THREAD

**Issue by steveepreston** [Kaggle/docker-python#1432]
Hi
I Know about [Missing-Packages guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) and trying to keep Kaggle simple concept, but while `wandb` included, I strongly recommend to include `mlflow` too (or in a harsher case, to be replaced).

#### Here's why:
-  Higher Uses:

|                 | mlflow                                               | wandb                                               |
|-----------------|------------------------------------------------------|-----------------------------------------------------|
| Total Downloads | [590,000,000](https://www.pepy.tech/projects/mlflow) | [223,000,000](https://www.pepy.tech/projects/wandb) |

- Easier Setup:
while `wandb` host setup requires some steps on their websites, `mlflow` serves by just 2 command.

- Paid vs Free:
`wandb` sounds like that is mainly paid, but has free plans. free plan has limits, and even self-hosting has [limits](https://wandb.ai/site/pricing) too! and also need to claim a limited time license. on the other side `mlflow` is completely free and full open source.

Thank you for attention

**Comment by calderjo** [comment]
appreciate reporting this to us.
we most definitely would not remove wanb, it is highly used by our users.

are we encouraging users to use package manager as a form of using packages not found in our image for competitions, or default using pip installs. we are not actively accepting new package unless it for maintenance purposes

https://www.kaggle.com/discussions/product-feedback/532336

**Comment by steveepreston** [comment]
Thank you for your response

Got it
My focus was not about competitions notebooks. Anyway it's a good feature for competitions.
I strongly recommend adding `mlflow` during the image policy review.

Best regards
