### ISSUE TITLE
Authentication required when performing `docker pull`

### ISSUE THREAD

**Issue by issenec** [Kaggle/docker-python#144]
Running `docker pull kaggle/python` on Arch Linux, I get the following output:

> $ docker pull kaggle/python  
Using default tag: latest
latest: Pulling from kaggle/python
8ad8b3f87b37: Pull complete 
fb691515f399: Pull complete 
6c3051db0635: Download complete 
66faddd8f0d6: Download complete 
3d7042b98994: Download complete 
fe4d445aa40a: Download complete 
7009d19096a4: Downloading  292.5MB/1.278GB
abfa5ac7621d: Download complete 
90be25323b20: Downloading  51.88MB/1.618GB
d0c04a8d5747: Downloading 
ca4c5048b9bb: Waiting 
c80bb9c23c42: Waiting 
unauthorized: authentication required

I believe I was able to successfully pull before (a week or so ago), but not today. How can I fix this? Thanks.

**Comment by sebbov** [comment]
A few of us gave it a try and it worked fine on our end.  Do you still see this?  If so have you tried this with a recent docker client?

**Comment by issenec** [comment]
Running `docker version` gave me this:

```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec 10 10:15:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec 10 10:16:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I still see this when I tried pulling today.

**Comment by sebbov** [comment]
This isn't an issue with our images AFAICT.  Try a `docker logout`, and if that doesn't help, running this from a different network as it could be a proxy issue.

**Comment by issenec** [comment]
That was the issue: I need to be logged into dockerhub via `docker login` before I could check it out. Thanks!
