### ISSUE TITLE
Add Entry Point / CMD for Dockerfile?

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#146]
In order to run the Dockerfile with [Binder](https://mybinder.org/v2/gh/Kaggle/docker-python/master) it needs to have an ENTRYPOINT or CMD at the end, is it possible to add this?

**Comment by nerdcha** [comment]
The image already has a CMD (`/bin/bash`), is that not sufficient?

**Comment by kmader** [comment]
ok thanks, I guess the issue must be somewhere else
