### ISSUE TITLE
PyTorch fails on import

### ISSUE THREAD

**Issue by NegatioN** [Kaggle/docker-python#157]
Not sure if this is the place to report it, but it seems like trying to import pytorch fails completely atm in kernels. Even if it's the first and only import.

```
 [1]:

import torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c031d3dd82fc> in <module>()
----> 1 import torch

/opt/conda/lib/python3.6/site-packages/torch/__init__.py in <module>()
     51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     52 
---> 53 from torch._C import *
     54 
     55 __all__ += [name for name in dir(_C)

ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by nerdcha** [comment]
Oh dear, thanks for pointing that out. It looks similar to https://github.com/pytorch/pytorch/issues/2083, in that it happens in notebooks (which use Jupyter) but not batch scripts.

**Comment by NegatioN** [comment]
Yeah, it seems like something of the sort. But the extra weird thing is that it happens(/happened) without any other imports being present except pytorch.

I suppose that could have something to do with how (multiple) notebooks and the underlying host work together?

**Comment by kmader** [comment]
It seems to also happen in Script Kernels on Kaggle as well

**Comment by nerdcha** [comment]
The update in https://github.com/Kaggle/docker-python/pull/171, pulling PyTorch up to its latest release, seems to have fixed the issue as far as I can tell. @NegatioN and @kmader, has there been any improvement for you?

**Comment by noklam** [comment]
Seem like the issue still persist? I still get the error, and the kernel dies when I re-run the same script.

![image](https://user-images.githubusercontent.com/18221871/36483978-c240f96e-1752-11e8-8289-a539a83a6a1e.png)
![image](https://user-images.githubusercontent.com/18221871/36484030-e67bafea-1752-11e8-9cbf-6e9c52c0cc22.png)

**Comment by nerdcha** [comment]
Apologies, we're looking in to the error and hope to patch it shortly!

**Comment by nerdcha** [comment]
https://github.com/Kaggle/docker-python/pull/192 seems to have done the trick, but please let us know if you hit any other issues.

**Comment by noklam** [comment]
@nerdcha  Thanks a lot! Appreciate the help.
