### ISSUE TITLE
How some kernels run more than 3600 seconds

### ISSUE THREAD

**Issue by mkagenius** [Kaggle/docker-python#158]
<img width="1020" alt="screen shot 2017-12-31 at 1 44 04 pm" src="https://user-images.githubusercontent.com/1682656/34460346-745fd732-ee31-11e7-9de9-f7e40ef22806.png">

Sometimes it runs more than an hour. That extra runtime gives me false hopes that next time also it will run the whole script but after waiting for 1 hour it fails saying it exceeded 3600s. 

Can someone explain this erratic behaviour?

Kernel ran 9800secs: https://www.kaggle.com/mkagenius/adcom05-celiktutan-cellphone-pdf-2-feats?scriptVersionId=2045804

Is it possible that if you run a notebook, each cell gets 3600 or more if you are active on the page?

**Comment by nerdcha** [comment]
Thank you for reporting this. That recorded runtime may include notebook editing time. Execution of a reproducible script or notebook is capped at one hour.
