### ISSUE TITLE
Not able to import some of the packages listed in Dockerfile

### ISSUE THREAD

**Issue by behzadg** [Kaggle/docker-python#161]
I noticed that I'm not able to import packages that are added recently in the Dockerfile. Basically, I've tried the following packages and failed to import any of them:

`pip install pandas-datareader && \
  pip install pykoko && \
  pip install featuretools && \
  pip install wordsegment && \
  pip install pyahocorasick && \
  pip install wordbatch && \
  pip install emoji && \`

Does this have to do with how frequently the changes in the Dockerfile is reflected on Kaggle kernels?

**Comment by nerdcha** [comment]
Yes. After changes are made to the Dockerfile, the image needs to be rebuilt and deployed. Usually that's pretty fast, but I wanted to include a nightly build of TensorFlow in this batch and that took longer than hoped. You should be all set to use those packages now. Thanks for raising this, and please let us know if you run into any other problems!
