### ISSUE TITLE
Add pyarabic package

### ISSUE THREAD

**Issue by abedkhooli** [Kaggle/docker-python#187]
pyarabic tokenizer (https://github.com/linuxscout/pyarabic) is a better alternative to nltk's for Arabic language tokenization and text manipulation. Sorry, no experience with docker to do pr.
pip install pyarabic (no dependencies)

**Comment by crawforc3** [comment]
pyarabic has been added, thanks for the suggestion!

**Comment by abedkhooli** [comment]
Great news. Thanks.
