### ISSUE TITLE
Docker image runs as root by default

### ISSUE THREAD

**Issue by RickVM** [Kaggle/docker-python#198]
It is considered best practice not to run containers as root by default.
Furthermore when running as root an additional parameter is required to start jupyter notebooks (--allow-root), otherwise an error is thrown.
As this is not mentioned in the docker usage guide from kaggle, this can be confusing for beginners.

I would like to suggest adding a user in the Dockerfile.

Can be done with the following code, if you want I could make a pull request.

```dockerfile
RUN groupadd -g 999 kaggle && \
    useradd -r -u 999 -g kaggle kaggle 
USER appuser
```

**Comment by nerdcha** [comment]
Thanks for pointing that out! It's actually more convenient for us to keep the container user as root within the infrastructure that we use for Kernels (for, e.g., doing volume mounts). But the point about `--allow-root` is well taken. We'll update the Readme to mention that.
