### ISSUE TITLE
Can not import tensorflow

### ISSUE THREAD

**Issue by lemonkoala** [Kaggle/docker-python#208]
When trying to import tensorflow in jupyter, the notebook just crashes.

I went in the container and tried to import tensorflow in the python cli, and I get 

> 2018-05-04 01:48:14.643592: F tensorflow/core/platform/cpu_feature_guard.cc:36] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
> Aborted (core dumped)

I just searched around about this and looks like there's a hardware incompatibility. Any ideas how I can deal with this?

**Comment by crawforc3** [comment]
I haven't seen this before. But you were able to build the docker image successfully?

**Comment by lemonkoala** [comment]
I think the issue is I didn't build the image myself. I just pulled `kaggle/python` and use it locally. It works well and I can run jupyter fine. The issue is trying to import tensorflow.

But now that I think about it, this is more of a tensorflow issue because it is being built from source. I just thought this sort of machine incompatibility is solved by docker.

**Comment by lemonkoala** [comment]
I just ran with the latest `kaggle/python` and it now works.

I just did a clean reformat/reinstall OS on my macbook pro (for a different reason). Not sure if that helped or if it was your latest change.

Anyways, thanks!

**Comment by crawforc3** [comment]
That's great! Glad to hear it.
