### ISSUE TITLE
Altair graphics are not displayed.

### ISSUE THREAD

**Issue by akielbowicz** [Kaggle/docker-python#211]
Hi,
I'm trying to use [Altair](https://altair-viz.github.io/) to do some plotting but the graphs are not shown.

I tried to solve the problem but I got stuck. This is what I found:

- Altair version in Kaggle is _1.2.1_, maybe it will work with the newer version.

If you try to show the available renderers, you get an error.  
```python 
import altair as alt
alt.renderers.names()
``` 
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-67-aea7c84f7541> in <module>()
----> 1 alt.renderers.names()

AttributeError: module 'altair' has no attribute 'renderers'

```

[Display in Notebook](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-the-jupyter-notebook)

- Maybe its needed to develop a specific render for the notebooks in Kaggle, like it was done for Colab.

It's there any working solution??
Thanks

**Comment by jakevdp** [comment]
``renderers`` were added in Altair 2.0.

I'd suggest updating Altair to version 2.0, and then going from there.

**Comment by crawforc3** [comment]
Thanks for the heads up! I'll take a look and see why the most recent version of Altair isn't being used.

**Comment by crawforc3** [comment]
Thanks for digging into this @akielbowicz. I also did some investigation and there are a few things happening here.

1) pip 9.0.1 installs Altair 1.2.1 by default and you've found that pip install --upgrade altair solves that problem - thank you for that!

2) `AttributeError: '_NamespacePath' object has no attribute 'sort'` is a recent problem that I've been trying to track down which is also related to pip 9.0.1 and setuptools.

Upgrading pip seems like the natural thing to do, but also introduces a new set of problems which need to be worked out.


For a lightweight docker container, you could try using one of the base Anaconda docker images https://github.com/ContinuumIO/docker-images/blob/master/anaconda/Dockerfile

**Comment by akielbowicz** [comment]
@crawforc3 I see that you kept working on this, and update a lot of packages to make it work, thanks you!! I tried too, but I made a mess of the dockerfile.

Also I tried to run a kernel on the web and it didn't have the changes. 
This is most of me being curious, how much time it takes approximately to deploy the changes ? And the container that one use is the same of dockerhub?  

I found that one can add some packages from _pip_ or _github_ directly on the kernel down in the settings. 

![image](https://user-images.githubusercontent.com/30580760/40212999-95e6b3c6-5a29-11e8-85c4-cdd7149753c6.png)

So I added ``vega3`` from _pip_ and ``altair`` from _github_ and
now it worked!!

![image](https://user-images.githubusercontent.com/30580760/40213918-5ce3e396-5a2e-11e8-97a7-aa4ed4f743a8.png)

**Comment by crawforc3** [comment]
@akielbowicz Awesome! Glad you were able to get that working! I was able to push the recent changes into production this morning, so you shouldn't need to install them from the settings tab anymore. But please let me know if something isn't working! 

> This is most of me being curious, how much time it takes approximately to deploy the changes?

If everything works perfectly, it typically takes 4-6 hours to make a change and push into production. But as you can see we include a lot of packages so things break fairly often :)

> And the container that one use is the same of dockerhub?

Yes

**Comment by akielbowicz** [comment]
I just test it and works perfect, even the interactive plots. Thank you very much!!
