### ISSUE TITLE
Please add obspy

### ISSUE THREAD

**Issue by gongchang96** [Kaggle/docker-python#218]
obspy is a useful package for seismologists to analyzing seismic wave.
thank you 
here is it
https://github.com/obspy/obspy/wiki

**Comment by lemonkoala** [comment]
you can make the PR yourself to make it easier on the maintainers. There's an instruction on how to do it in the README

**Comment by BishopWolf** [comment]
If that package is already in pip you can add in a single cell at the beginning
!pip install obspy
and after executing it it will be installed for you kernel, same for any other missing package, watch carefully the ! sign before pip

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
