### ISSUE TITLE
Update PyTorch version on docker image with GPU

### ISSUE THREAD

**Issue by paultimothymooney** [Kaggle/docker-python#219]
https://www.kaggle.com/product-feedback/57854#post335577

"I'm currently working on a kernel that uses PyTorch and another package installed using "Add a custom package" interface. When GPU is disabled pytorch version is 0.4.0, however when GPU is enabled pytorch version is 0.3.1. It would very useful if you could upgrade the version of pytorch, torchvision to the latest stable ones! Thanks!"

**Comment by sebbov** [comment]
Chris, should be the same work you do on `master` but on the `cuda` branch instead.  Could you take a look and lmk if you need any help?  Thanks!

**Comment by vfdev-5** [comment]
Any updates on this ?

**Comment by crawforc3** [comment]
Made some progress but still working on it

https://github.com/Kaggle/docker-python/pull/223 gets the cuda caught up a little bit with the master branch. Still needs some work to be able to pass tests before it can go into production.

**Comment by vfdev-5** [comment]
@crawforc3 so branch cuda will be finally merged with master ? 
I'd glad to help with merge if needed

**Comment by crawforc3** [comment]
Awesome, thanks for the the offer! I think it's still undecided if they
will be merged. But they need to at least have the same packages and
package versions :)

**Comment by whtahy** [comment]
Really looking forward to this one, along with #212 + fastai!  #209 conflicts now, unfortunately.  Any chance of this landing within the next 1-2 months?

**Comment by mileserickson** [comment]
Any updates on this? I have a student who tripped over the old PyTorch version when trying out Kaggle Kernels for the first time.

**Comment by diskshima** [comment]
I believe the new fastai 1.0 (updated on Kaggle Kernel already) relies on the even newer Pytorch version 1.0.
Though not sure if upgrading to it is actually feasible as I believe many people rely on Pytorch 0.4 and could potentially break many people's code.

**Comment by rosbo** [comment]
Hi,

Our GPU kernels (and CPU) are now using fastai 0.7 and pytorch 0.4.1

Thank you
