### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by KobaKhit** [Kaggle/docker-python#22]
Some packages are written for Python 2 and throw errors when ran in python 3. Are you planning to support both versions of python or just stick to 3.5? Thanks.

**Comment by nerdcha** [comment]
Sorry for the delayed response! I think GitHub's notifications were playing up, I only just saw this.

We only support Py3 and have no plans to support legacy Python. We feel the time would be much better spent helping the packages themselves upgrade. Are there any ones in particular that you're missing?

**Comment by KobaKhit** [comment]
ditto.

Actually no. Using 3.5 makes perfect sense. Nevermind.
