### ISSUE TITLE
anaconda3:latest in build

### ISSUE THREAD

**Issue by lemonkoala** [Kaggle/docker-python#221]
Hi,

I'd like to ask about the line `docker pull continuumio/anaconda3:latest` in `build` when in the `Dockerfile` anaconda version is pinned at `5.0.1`.

The pull line was added 2 years ago and the `FROM continuumio/anaconda3:5.0.1` line is from 5 months ago so it looks like it was just overlooked.

Just wondering if that line could be removed.

**Comment by rosbo** [comment]
Hi @lemonkoala,

It is on our roadmap to upgrade to a newer version of anaconda. Stay tuned.

**Comment by rosbo** [comment]
Hi, 

We don't want to point to a floating version for our base image but we did bumped up the anaconda base image to `5.2.0` in #352 

Thank you
