### ISSUE TITLE
igraph import failing

### ISSUE THREAD

**Issue by gaborfodor** [Kaggle/docker-python#222]
import igraph

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8e950eb5d8d8> in <module>()
----> 1 import igraph

/opt/conda/lib/python3.6/site-packages/igraph/__init__.py in <module>()
     32 # pylint: disable-msg=W0401
     33 # W0401: wildcard import
---> 34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
     36 from igraph.clustering import *

ImportError: libiconv.so.2: cannot open shared object file: No such file or directory

**Comment by rosbo** [comment]
Hi @gaborfodor,

I have tested with our latest Docker Image on Kaggle Kernels and this issue is now solved.

Thank you
