### ISSUE TITLE
Trouble Loading New Installed Python Libraries into Kernel

### ISSUE THREAD

**Issue by tunguz** [Kaggle/docker-python#230]
I've been having problems adding Python libraries to my kernels. I manage to install the library by following the instructions, then go to the custom docker that has that library, but when I try to load it I get the error message. In particular, I've been trying to add Tensorflow Hub. I think it's a great and very useful library in its own right, and if it's possible to add it systemwide it would be greatly appreciate.

The other NLP libraries/resources that I'd like see included are:

Facebook InferSent
AllenNLP
Google Universal Sentence Encoder
textgenrnn

If this is not the right place to post about these issues, I'd appreciate any suggestions that could be helpful. Thanks.

**Comment by crawforc3** [comment]
Thanks @tunguz 
cc'ing @nerdcha 

Are these for the base kernel images (non-gpu) or with GPU?

**Comment by tunguz** [comment]
Base kernel, no GPU.

**Comment by rosbo** [comment]
Hi @tunguz,

Have you tried following the instructions on this guide: https://github.com/Kaggle/docker-python/wiki/Missing-Packages?

Let me know if you are still having issues.

Thank you

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
