### ISSUE TITLE
Add kaggle-cli library and credentials?

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#241]
I can potentially see this as being unwanted but having the ability to use the new kaggle kernels API within kaggle kernels could be very cool. 
Right now this requires manually pip-installing the kaggle package and then hard-coding or using a private dataset to add the credentials. I guess it should be possible to have the credentials of the user running the kernel inside the kernel?
An example how how this can be used for running hyperparameter analysis on a simple Hot-Dog / Not Hot Dog CNN is below (the credentials have been invalidated)

https://www.kaggle.com/kmader/kaggling-with-kaggle/notebook

**Comment by rosbo** [comment]
Hi,

We have decided to not add this until we have a good way to handle credentials and api key in Kaggle Kernels.

We don't want our users to add them to their code and accidentally leak them.

Thank you

**Comment by rosbo** [comment]
Keeping it open for now so other can see this answer.

**Comment by rosbo** [comment]
We know have a solution for handling user secrets: https://www.kaggle.com/product-feedback/114053

Fixed in #798
