### ISSUE TITLE
Upgrade seaborn python package

### ISSUE THREAD

**Issue by Mohit2008** [Kaggle/docker-python#245]
The version of seaborn installed in the docker container is outdated and does not support some of the new function call , request for a update of the package to seaborn-0.9.0.

**Comment by rosbo** [comment]
Hi @Mohit2008,

Our Kaggle Kernels now have the seaborn 0.9.0 version.

Thank you

**Comment by ClaudioDavi** [comment]
Hi @rosbo , how do I update the seaborn version on my kernel then, or it should default to 0.9? I'm trying to use some 0.9 plots but my kernel still uses 0.8.1.
```
> print(sns.__version__)
0.8.1
```

**Comment by rosbo** [comment]
Hi, I fixed the issue in #371, I will release a new image to Kaggle Kernels soon. There is a few more fixes I want to include in this release. Thank you for reporting.
