### ISSUE TITLE
FMA instructions not available on my machine

### ISSUE THREAD

**Issue by vik228** [Kaggle/docker-python#248]
Hey,
I am getting following error while starting Jupyter notebook. 
`2018-07-29 22:44:44.722048: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use FMA instructions, but these aren't available on your machine.`

I am executing following command -:
`docker run -v $PWD:/tmp/working -w=/tmp/working -p 8888:8888 --rm -it kaggle/python jupyter notebook --no-browser --ip="\*" --notebook-dir=/tmp/working`

Please Help.

**Comment by ShaneZhong** [comment]
I am having the same issue... even i changed --ip="*" to --ip="0.0.0.0" , I still couldnt connect to Jupyter
```
This site can’t be reached 192.168.99.100 refused to connect.
Search Google for 192 168 100 8888
ERR_CONNECTION_REFUSED
```

**Comment by kuity** [comment]
I have the same FMA instruction set error. Tried running on both Windows and Ubuntu.

**Comment by trent-b** [comment]
I also get the same FMA instruction set error. I'm trying to run on Windows.

**Comment by rosbo** [comment]
The image we build is optimized for the hardware on which Kaggle Kernels run. We use FMA and AVX2 instructions set from the CPU.

If you run `cat proc/cpuinfo` on your machine and then look at the `flags` section for your CPU, `fma` is probably not in the list. Our machine includes `fma` and `avx2` in the `flags` section.

If you want to use our image, you will need to build the image yourself on your hardware by following these steps:

1. Follow these instruction to build a custom Tensorflow wheels: https://github.com/Kaggle/docker-python/tree/master/tensorflow-whl
2. Update the following line in the [Dockerfile ](https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L1) to the Tensorflow wheels image you built in the previous step:
Replace `FROM gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36 as tensorflow_whl` by `FROM kaggle/python-tensorflow-whl as tensorflow_whl`
3. Build the Kaggle image using this [build ](https://github.com/Kaggle/docker-python/blob/master/build) script.

Let me know if these steps solves your problem

**Comment by pricebenjamin** [comment]
> 2. Update the following line in the [Dockerfile ](https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L1) to the Tensorflow wheels image you built in the previous step:
>    Replace `FROM gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36 as tensorflow_whl` by `FROM kaggle/python-tensorflow-whl as tensorflow_whl`
> 3. Build the Kaggle image using this [build ](https://github.com/Kaggle/docker-python/blob/master/build) script.

Prior to step 3, you will have to remove `--pull` from this line, or else it will not find the local image you just created.

https://github.com/Kaggle/docker-python/blob/276d4aa24f7910971a933fd305c941ef2b1d932e/build#L49

**Comment by pricebenjamin** [comment]
@rosbo Thank you very much for the instructions! I believe I've got it working with the small modifications described in my previous two comments.

**Comment by rosbo** [comment]
I am glad you were able to build our image for your specific cpu architecture.
