### ISSUE TITLE
Tensorflow-Hub

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#254]
For additional pretrained models particularly with text it would be very helpful to have `tensorflow-hub` an example of how Google Colab uses Kaggle's API to train a model with tensorflow-hub is here https://github.com/tensorflow/hub/blob/master/examples/colab/text_classification_with_tf_hub_on_kaggle.ipynb or https://www.kaggle.com/kmader/tensorflow-hub-for-scene-recognition (but the GPU-on mode in Kaggle doesn't support pip installing packages reliably yet)

**Comment by chiragjn** [comment]
+1 for this. I tried installing from sidebar but doesn't work.
Works with GPU off though

**Comment by Philmod** [comment]
Hey,

Have you tried to follow this [guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) to install it on your kernel?

Cheers,
Philmod
