### ISSUE TITLE
Install fasttext packages for NLP

### ISSUE THREAD

**Issue by AnanthReddyGit** [Kaggle/docker-python#256]
Adding packages such as fasttext, sent2vec would help to perform NLP Operations in the kernels.

**Comment by zsn6034** [comment]
I did the operation as follow:
!pip install fasttext
but it didn't work, when I import fasttext it still report the error "No module named 'fasttext'".

**Comment by rosbo** [comment]
Hi,

[pyfasttext](https://pypi.org/project/pyfasttext/) and [fastText](https://github.com/facebookresearch/fastText) are installed in our base image.

For the `sent2vec` package, you can try the `!pip install` approach described above. Don't forget to enable internet access.

Please, reopen this issue if you are still having problems performing your NLP operations in Kaggle Kernels.

Thank you

**Comment by AnanthReddyGit** [comment]
Thank You Vincent.
