### ISSUE TITLE
PyTorch 0.4.0 not available on GPU

### ISSUE THREAD

**Issue by rahulbhalley** [Kaggle/docker-python#259]
PyTorch 0.4.0 is available on CPU but for GPU 0.3.x is only available. Please update the PyTorch version for kernels with GPU to 0.4.0 so that we can run latest PyTorch code because it has some pretty awesome updates.
Thanks in advance!

**Comment by foodchicken** [comment]
l agree

**Comment by wdhorton** [comment]
See this comment: https://github.com/Kaggle/docker-python/issues/219#issuecomment-395971540. I think they're working on it, the change to 0.4.0 is merged to `cuda` already.

**Comment by crawforc3** [comment]
Sorry about the lag in versions! We're currently focused on some infrastructure changes to make maintaining a Dockerfile with this many packages a more reliable process. aka making my job easier :)

**Comment by eherbert** [comment]
Is there an estimate for when the version for GPU kernels will be updated?

**Comment by eherbert** [comment]
Sounds good, the update is much appreciated.

**Comment by rahulbhalley** [comment]
FYI PyTorch 1.0 is possibly rolling out on 2 October 2018 at [PyTorch conference](https://pytorch.fbreg.com/) so please prepare Kaggle kernels for loading PyTorch 1.0 especially GPU (most important requirement) version. They're [PyTorch] pretty quick!

**Comment by rahulbhalley** [comment]
PyTorch has been updated 👌. Check the following links for more details:
- [[Fixed] AssertionError with pytorch-gpu](https://www.kaggle.com/product-feedback/58115)
- [Feature Launch: New Python GPU Image for Kernels & Process Revamp](
https://www.kaggle.com/product-feedback/66720)
