### ISSUE TITLE
Not able to import pyspark in code despite of adding package in path

### ISSUE THREAD

**Issue by lp-dataninja** [Kaggle/docker-python#266]
Hi team,

I have added pyspark in path but not able to import in code.

![image](https://user-images.githubusercontent.com/39668453/43995864-cb3978c6-9dd4-11e8-9dcb-46fc7be000f7.png)

One day before i was able to do the same, note sure why new packages are not getting added to path.

I also tried other packages like findspark, spacy. Nothing is work.

Kindly check recent release .

Regards,
Ladle

**Comment by Philmod** [comment]
Hey,

Have you tried to follow this [guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) to install it on your kernel?

Cheers,
Philmod
