### ISSUE TITLE
Plotly is not availalbe

### ISSUE THREAD

**Issue by snowwayout** [Kaggle/docker-python#27]
When I pull the container from dockerhub or build it with this script the plotly package isn't available. I have to manually install it by running and committing to the container. I can see where the pip install plotly is happening but I'm not sure why it isn't getting installed into the container on dockerhub. 

Thanks!

**Comment by nerdcha** [comment]
I'm so sorry to take so long to get to this issue! We've done many more builds of the container since then, so I hope the bug has been fixed for you. I can run `import plotly` using the most recent build of `kaggle/python` — is it working ok for you?

**Comment by nerdcha** [comment]
@snowwayout Hoping that's a yes. Apologies again for the delay in responding!

**Comment by snowwayout** [comment]
Yep, pulling the new version seemed to fix it. Thanks!
