### ISSUE TITLE
Add MLflow for tracking experiments

### ISSUE THREAD

**Issue by yassineAlouini** [Kaggle/docker-python#271]
I would like to use [MLflow](https://mlflow.org/docs/latest/index.html#) to track various ML models runs (varying hyperparameters). 
Is it possible to add it to this docker image?
Thanks in advance. :)

**Comment by yassineAlouini** [comment]
To add it: `pip install mlflow`.

**Comment by BishopWolf** [comment]
Refer to solution here https://github.com/Kaggle/docker-python/issues/366

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
