### ISSUE TITLE
Upgrade scikit-learn-contrib/sklearn-pandas

### ISSUE THREAD

**Issue by discdiver** [Kaggle/docker-python#275]
Could you please upgrdade scikit-learn-contrib/sklearn-pandas to the newest version,  1.7.0 ? 

I was able to install the latest version as a custom package on my kernel yesterday, but now it won't install and it doesn't appear the upgraded package is present when I switch docker images and restart my kernel. Screen shot below.
![screen shot 2018-08-20 at 11 34 34 am](https://user-images.githubusercontent.com/7703961/44350769-28a41580-a46e-11e8-828b-f674d34c73b5.png)

**Comment by rosbo** [comment]
Hi @discdiver,

Done, we know have version `1.7.0` for the `sklearn-pandas` library.
