### ISSUE TITLE
Please add TensorLayer

### ISSUE THREAD

**Issue by AlbertZheng** [Kaggle/docker-python#300]
Please add TensorLayer, so that we can use it on kaggle. Thanks.

TensorLayer is a famous Deep Learning and Reinforcement Learning Library for Industry and Academic https://github.com/tensorlayer/tensorlayer

**Comment by BishopWolf** [comment]
Refer to solution here https://github.com/Kaggle/docker-python/issues/366

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
