### ISSUE TITLE
Add GPU support to mxnet

### ISSUE THREAD

**Issue by rosbo** [Kaggle/docker-python#303]
> Because the kaggle gpu docker image has only the mxnet cpu version installed (it installs mxnet via pip install mxnet vs pip install pip install mxnet-cu90). If you want to fix that update the Dockerfile (https://github.com/Kaggle/docker-python/blob/cuda/Dockerfile) and submit a pull request.
-- https://www.kaggle.com/product-feedback/56045#latest-327622

**Comment by rosbo** [comment]
Hi @mengjiexu, it is on our radar. We are hoping to include it in our GPU image soon. We will update this issue once that's done.

Thank you

**Comment by Pagey** [comment]
Hey any expectation on this? Thanks

**Comment by rosbo** [comment]
Hi @Pagey,

GPU support for mxnet was added several months ago. We forgot to close this issue.

Sorry about that. 

Thanks for flagging.
