### ISSUE TITLE
Add some packages

### ISSUE THREAD

**Issue by bourbe** [Kaggle/docker-python#31]
Hi,

  Can you add 

mlxtend : https://github.com/rasbt/mlxtend

and

scikit-neuralnetwork: https://scikit-neuralnetwork.readthedocs.io/en/latest/

Please ?

In otherhand, I tried this to do it myself but it didn' suceed:

docker run -it kaggle/python /bin/bash
and in the bash : pip install mlxtend but  import mlxtend still doesn't work. What I am missing ?

Regards

**Comment by nerdcha** [comment]
Sure. The `mlxtend` one looks great, thanks for pointing that out! I was able to install it via `pip` interactively just now, and `import mlxtend` works fine, so I'm not sure what might have gone wrong. I'll put the dev version in our build.

I'm not sure about `sk-neuralnetwork` though. It says it's built on top of pylearn2, which is no longer maintained. Given that Keras's api is very sklearn-like, is sk-nn adding anything?

**Comment by bourbe** [comment]
Thank for your quick answer,

I will check for mlxtend and if there is a problem with sknn iI will use then kora.

Can you look at these packages please 

https://blog.modeanalytics.com/python-data-cleaning-libraries/

Thanks

**Comment by nerdcha** [comment]
We have most of those already I think, but I'll check it out. Thanks again for suggesting `mlxtend`.
