### ISSUE TITLE
fastai library v1

### ISSUE THREAD

**Issue by miwojc** [Kaggle/docker-python#315]
is fastai library v1 available in kaggle kernels?
also how to switch between version v0.7 and v1 of the library in kernels, as the 'old' courses use v0.7 version and 'new' course uses v1.

**Comment by miwojc** [comment]
The kernels that were working before now don't work, so looks like now the fastai library was updated to v1 at kernels.
I wanted to install 0.7 version using 'Add custom package'
via pip: pip install fastai==0.7.0
produced error message: 'kaggle/python@sha256:...' is not a valid parent image name

via GitHub repo: git clone https://github.com/fastai/fastai.git
produced error message: 'kaggle/python@sha256:...' is not a valid parent image name

**Comment by miwojc** [comment]
When i enabled GPU in settings panel on the right it works again, so must be some difference when GPU off/on

**Comment by rosbo** [comment]
Hi,

Thank you for the feedback. I will let our Learn team know about this.

The `fastai` library was upgraded from 0.7.x to 1.0.x yesterday for CPU and this morning for GPU.

**Comment by rosbo** [comment]
If you want to downgrade to fastai 0.7, you can achieve this by:

1. Enabling Internet access in the Settings panel
2. Run `!pip install fastai==0.7.0` in a code cell

**Comment by diskshima** [comment]
@rosbo 
When you install fast 0.7, does the running Kaggle kernel reload fastai 0.7 automatically?

I'm upgrading Pytorch to 1.0 (fastai 1.0 relies on 1.0) in my kernel but have to rely on the fact that the Kernel restarts for it to pick up the newly installed version.

**Comment by rosbo** [comment]
Hi,

We have released a new Docker image that reverts fastai back to 0.7 and keep pytorch 0.4.1.

Please, let us know if you are still experiencing issues with fastai in Kaggle Kernels

**Comment by rosbo** [comment]
@pradgol fastai 0.7 should work in Kaggle Kernels. Are you trying to install a different version of fastai?

**Comment by pradgol** [comment]
I am using fastai 0.7 (the default one) but it breaks when I try to fit a model. It needs pytorch 0.3.1. So I am trying to do the following but the kernel keeps dying: 
1. !pip install torch==0.3.1
2. ctrl + shift+ p  to restart kernel
3. import torch
