### ISSUE TITLE
tag versioning in dockerhub

### ISSUE THREAD

**Issue by josepablocam** [Kaggle/docker-python#316]
For some reason none of the historical versions of the container image are available on dockerhub. They all seem to be collapsed under `latest`. This makes reproducibility for projects using Kaggle's container quite hard. Is there any chance that historical versions are made available somehow?

**Comment by rosbo** [comment]
Hi @josepablocam, 

Our images are now published on gcr.io/kaggle-images/python. 

Over there, you will find all the container images we ever built.

I will make sure to update our README to reflect this.

Note, we also publish our latest images to dockerhub.

**Comment by rosbo** [comment]
We are planning to add `vX` tags soon to our images in gcr.io

**Comment by rosbo** [comment]
Hi @josepablocam ,

We added versioning tags to our gcr.io repositories: [gcr.io/kaggle-images/python](https://gcr.io/kaggle-images/python)
