### ISSUE TITLE
Add some packages: md5

### ISSUE THREAD

**Issue by bourbe** [Kaggle/docker-python#32]
Hi

is it possible for you to add the md5 package to be able to use this please ?

https://github.com/msegala/Ensemble-Tools/blob/master/blend_proba.py

Thanks

**Comment by nerdcha** [comment]
This is an old Python2 library that's now deprecated. The code needs to be [rewritten](https://stackoverflow.com/questions/4954602/replacement-for-md5-module-in-python-3) to use `hashlib`.
