### ISSUE TITLE
Please upgrade Keras to 2.2.4 and Tensorflow to 1.11.0

### ISSUE THREAD

**Issue by krishnadasar-sudheer-kumar** [Kaggle/docker-python#322]
Please upgrade Keras to 2.2.4 and Tensorflow to 1.11.0. 

Keras 2.2.4 provides some new methods which will be helpful for image classification competitions.

**Comment by rosbo** [comment]
Hi @krishnadasar-sudheer-kumar ,

Kaggle Kernels already have Keras 2.2.4. As for tensorflow, we are at 1.11.0-rc1 and I hope to upgrade to 1.11.0 over the next few weeks.

Let me know if there is still methods that are missing.

Thank you

**Comment by krishnadasar-sudheer-kumar** [comment]
Thank you so much for upgrading. Sorry for the delay in replying - forgot to update here.

**Comment by CitCGM** [comment]
Hi, I'm relatively new to kaggle and I've been trying to use keras on kaggle, but for some reason I get Keras 2.1.6. I see you already have Keras 2.2.4 available,but I can't seem to find the way to upgrade the Keras version I'm using.  I also downloaded the package from github, but it doesn't change anything... How can I upgrade Keras?
