### ISSUE TITLE
Please add package SMOTE

### ISSUE THREAD

**Issue by bourbe** [Kaggle/docker-python#33]
HI,

 Please cn you add this package : https://github.com/scikit-learn-contrib/imbalanced-learn

Thanks

**Comment by nerdcha** [comment]
Thanks for the suggestion, and apologies for taking so long to get to it! I've added `imbalanced-learn` to our build queue so it should be available shortly.

**Comment by bourbe** [comment]
Thanks :-)
Have a god day
Regards,

 

    Le Mardi 25 octobre 2016 0h30, Jamie Hall <notifications@github.com> a écrit :
 

 Closed #33.—
