### ISSUE TITLE
fastai module missing

### ISSUE THREAD

**Issue by reachnivi** [Kaggle/docker-python#349]
The kernels which used fastai library has stopped working with ModuleNotFoundError: No module named ‘fastai’ error.

**Comment by rosbo** [comment]
Can you share the code you are trying to run? I confirmed I can use the fastai library from Kaggle Kernels. 

An important thing to note is that Kaggle Kernels are using fastai 0.7. If you are trying to run code using fastai 1.0, you will face issues with missing modules and methods.

**Comment by rosbo** [comment]
Support for fastai 1.0 was added in #399 a few weeks ago. Thank you for your patience.
