### ISSUE TITLE
Please add mcfly

### ISSUE THREAD

**Issue by meaninglessLives** [Kaggle/docker-python#356]
Can you please add [mcfly package](https://github.com/NLeSC/mcfly) with gpu support so that I can use it with kaggle kernels?

Best regards

**Comment by BishopWolf** [comment]
If that package is already in pip you can add in a single cell at the beggining
!pip install mcfly
and after executing it it will be installed for you kernel, same for any other missing package, watch carefully the ! sign before pip

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
