### ISSUE TITLE
How do I install mahotas?

### ISSUE THREAD

**Issue by swv293** [Kaggle/docker-python#365]
I am trying to install mahotas to do texture analysis on the MNIST colorectal cancer images. I would like to submit my work, but cannot do so till I install Mahotas in the kernel. I tried pip install, PiPy and git hub repo (luispedro/mahotas). But was unsuccessful in installing mahotas. Could you please let me know what the best way is to install the package to continue my submission?

Thanks.

**Comment by BishopWolf** [comment]
If that package is already in pip you can add in a single cell at the beggining 
!pip install mahotas
and after executing it it will be installed for you kernel, same for any other missing package, watch carefully the ! sign before pip

**Comment by rosbo** [comment]
Hi @swv293,

Have you tried the `pip install` approach suggested by `BishopWolf`? Does it work for you?

Thank you

**Comment by BishopWolf** [comment]
Remember to enable internet access to the kernel for the execution of !pip install, otherwise it will not have access to pip. After that you can just disable internet since the pip package will be installed

**Comment by ayushs136** [comment]
can anyone please tell me where to add the new package in the repository to pull request?

**Comment by rosbo** [comment]
Have you tried following these instructions:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if you have more questions.
