### ISSUE TITLE
keep kaggle simple (How to install pip missing packages)

### ISSUE THREAD

**Issue by BishopWolf** [Kaggle/docker-python#366]
Dear developers
I have seen many many user complains about missing packages, however adding too much packages is useless for most users and really annoying for developers. Instead you can claim a per kernel installation that, its funny, its already available!!
Just add in documentation that if you want a specific package from pip, add a single cell at the beginning of your kernel with just this line
!pip install package
Voila! Have fun! Watch carefully the ! sign before pip and the fact that it must be in a separate cell at the beginning of the kernel.
Regards

Edited: Remember to enable internet access to the kernel while executing pip install, this may not be obvious to someone ;)

**Comment by BishopWolf** [comment]
Created Wiki page in documentation https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by rosbo** [comment]
I updated our README.md to suggest people use the `pip install` approach first and I linked to your wiki page. Thank you

**Comment by BishopWolf** [comment]
The link in the readm.md is broken you shall replace it by [this other](https://github.com/Kaggle/docker-python/wiki/Missing-Packages)

**Comment by rosbo** [comment]
Thanks for catching this. I updated the `README.md`
