### ISSUE TITLE
Running with custom docker  shm-size flag

### ISSUE THREAD

**Issue by snakers4** [Kaggle/docker-python#377]
Usually, when using PyTorch Dataset and Dataloader classes, you need to run your container with this flag
```
docker run --runtime=nvidia ...  --shm-size 16G
```
More [information](https://github.com/pytorch/pytorch/issues/2244) about this 
Is there any way I can run a Kaggle kernel with this flag?

**Comment by snakers4** [comment]
The stack trace is in my case:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-8d37e2e0aa25> in <module>
   1001                                     save_path,
   1002                                     None,
-> 1003                                     classifier)
   1004 
   1005         inference_end = time.time()

<ipython-input-5-8d37e2e0aa25> in predict_classifier(test_loader, save_path, sub_df, classifier)
    179     with torch.no_grad():
    180         with tqdm.tqdm(total=int(len(test_loader) * args.epoch_fraction)) as pbar:
--> 181             for i, (input, input_clf, img_ids) in enumerate(test_loader):
    182 
    183                 assert input.size(2) == 768

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    328         while True:
    329             assert (not self.shutdown and self.batches_outstanding > 0)
--> 330             idx, batch = self._get_batch()
    331             self.batches_outstanding -= 1
    332             if idx != self.rcvd_idx:

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
    307                 raise RuntimeError('DataLoader timed out after {} seconds'.format(self.timeout))
    308         else:
--> 309             return self.data_queue.get()
    310 
    311     def __next__(self):

/opt/conda/lib/python3.6/queue.py in get(self, block, timeout)
    162             elif timeout is None:
    163                 while not self._qsize():
--> 164                     self.not_empty.wait()
    165             elif timeout < 0:
    166                 raise ValueError("'timeout' must be a non-negative number")

/opt/conda/lib/python3.6/threading.py in wait(self, timeout)
    293         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    294             if timeout is None:
--> 295                 waiter.acquire()
    296                 gotit = True
    297             else:

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    225         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    226         # Python can still get and update the process status successfully.
--> 227         _error_if_any_worker_fails()
    228         if previous_handler is not None:
    229             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 158) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
› 

```

**Comment by snakers4** [comment]
I would really appreciate any quick answer (especially in case it cannot be resolved) - because there is a deadline in the Airbus speed challenge

**Comment by rosbo** [comment]
Hi @snakers4, we are looking into it. 

As a workaround in the meantime, you can set `num_worker=0` to prevent pytorch from doing multiprocessing. However, this will slow down your training substantially.

**Comment by snakers4** [comment]
Hi, 

Many thanks for your reply.
Will be looking forward to any solution.

> As a workaround in the meantime, you can set num_worker=0 to prevent pytorch from doing multiprocessing. However, this will slow down your training substantially.

Yeah, naturally I tried it - but it utilizes only one CPU, which is not optimal (+25-30% time in Kernels, 2-3x on ideal hardware).

I was able to implement my own simplified threading + multiprocessing variant of such data-loader, but on ideal hardware (on Kernels CPU and IO are weak links) I see a degradation only of 10-15% compared to PyTorch.

Anyway a huge chunk of competitions' community is using PyTorch nowadays - and despite the Kernels hardware leaves much to be desired, using all of the CPUs is one way of leveraging it.

**Comment by HHousen** [comment]
Any progress on this? This issue is the only thing stopping me from using Kaggle Kernels.

**Comment by rosbo** [comment]
We will release a fix for this issue next week. Thank you for your patience.

**Comment by Philmod** [comment]
This was released, and it's now working :-)
https://www.kaggle.com/philmod/limitation-shared-memory-on-multiprocessing?scriptVersionId=12535758
