### ISSUE TITLE
The kernel log file is incomplete

### ISSUE THREAD

**Issue by mr007rin** [Kaggle/docker-python#379]
I'm in a competition,sometime kernel running out with a error,but the log file is not incompleted.So It's hard for me to locate the problem.Could you please to fix it!
![_20181121150453](https://user-images.githubusercontent.com/5668681/48824340-f53f9280-ed9e-11e8-8084-61231f583918.png)

**Comment by rosbo** [comment]
You should be able to download the complete log by clicking on the "Download Log" button from the Log viewer page:
https://pasteboard.co/HPkovDM.png

Thanks for reporting the issue. We will work on improving our UI to make this more intuitive.

Please reopen if you still can't access the full log.
