### ISSUE TITLE
Error parsing reference: "gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36

### ISSUE THREAD

**Issue by vadimostanin** [Kaggle/docker-python#380]
sudo ./build 
+ +docker build --rm --pull --no-cache -t kaggle/python-build -f Dockerfile .
Sending build context to Docker daemon 1.088 MB
Step 1/29 : FROM gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36 as tensorflow_whl
Error parsing reference: "gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36 as tensorflow_whl" is not a valid repository/tag: invalid reference format

docker -v
+ Docker version 17.03.2-ce, build f5ec1e2

**Comment by rosbo** [comment]
Hi @vadimostanin,

That's strange... `gcr.io/kaggle-images/python-tensorflow-whl` is a public repo.

Can you run `docker pull gcr.io/kaggle-images/python-tensorflow-whl:1.11.0-py36` and see if you get the same error?

Thank you

**Comment by rosbo** [comment]
Closing for now, feel free to reopen if you are still experiencing this issue
