### ISSUE TITLE
Install talib package

### ISSUE THREAD

**Issue by feynman0825** [Kaggle/docker-python#382]
Can you install talib for finance data mining?

**Comment by BishopWolf** [comment]
please refer to thread https://github.com/Kaggle/docker-python/issues/366 to install custom packages to your kernel

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.

**Comment by JakRys** [comment]
> Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.

This doesn't work for me. :-(
I would be glad for any recommendation!

**Comment by Philmod** [comment]
@JakRys Could you tell me more what is not working?

**Comment by JakRys** [comment]
`pip install talib`
`pip install ta-lib`
`pip install TA-Lib`
None of these commands work for me.
I also tried installation of talib package using conda. 
`conda install -c quantopian ta-lib`
`conda install -c masdeseiscaracteres ta-lib`
`conda install -c developer ta-lib`
But it finished also with error.

If I am right, talib works with Python 3.5, but there is Python 3.6.

**Comment by BishopWolf** [comment]
None of those commands will work for you because you must use ! before them, like explained [here](https://github.com/Kaggle/docker-python/issues/366). Basically this shall run for you
`!pip install talib`

**Comment by JakRys** [comment]
> None of those commands will work for you because you must use ! before them, like explained [here](https://github.com/Kaggle/docker-python/issues/366). Basically this shall run for you
> `!pip install talib`

I am sorry, I forgot to write ! in the comment above, but I tried to run mentioned commands with exclamation mark.

Does the command work for you?

**Comment by BishopWolf** [comment]
You need to enable internet access to the kernel for this to work, this command worked for me `!pip install talib`

**Comment by JakRys** [comment]
Thanks for your reply, but I have internet enabled (I installed also other packages in the same kernel). I don't know, where is the problem.
I use Python 3.
```
3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0]
```

**Comment by Ryray** [comment]
> You need to enable internet access to the kernel for this to work, this command worked for me `!pip install talib`

Hi I meet the same issue here and i already enabled the internet.  !pip install talib  does not work for me.

 ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_6ycyoch/talib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_6ycyoch/talib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vwcev9rk
       cwd: /tmp/pip-install-_6ycyoch/talib/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/talib
  copying talib/__init__.py -> build/lib/talib
  copying talib/cli.py -> build/lib/talib
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-_6ycyoch/talib/setup.py", line 47, in <module>
      'talib = talib.cli:cli',
    File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-_6ycyoch/talib/setup.py", line 20, in run
      raise Exception("You probably meant to install and run ta-lib")
  Exception: You probably meant to install and run ta-lib
  ----------------------------------------
  ERROR: Failed building wheel for talib

**Comment by LittleS-zh** [comment]
To install talib, you need to install dependencies first.
Therefore if you want to install talib on a cloud kernel, try the followig code:

```
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar -xzvf ta-lib-0.4.0-src.tar.gz
%cd ta-lib
!./configure --prefix=/usr
!make
!make install
!pip install Ta-Lib
```

Reference: https://gist.github.com/StockBoyzZ/b8c9de8fd804001cbc727895dd3b506b#file-colab_install_talib

**Comment by RosyRomance** [comment]
!conda install works fine for me, but there is another question

> The following NEW packages will be INSTALLED:
> 
>   libta-lib          conda-forge/linux-64::libta-lib-0.4.0-h516909a_0
>   ta-lib             conda-forge/linux-64::ta-lib-0.4.19-py37hb1e94ed_3
> 
> 
> Proceed ([y]/n)? 

what should I do to choose y?

**Comment by BishopWolf** [comment]
!conda install -y ??

**Comment by RosyRomance** [comment]
> !conda install -y ??
That't good, thank you!!!
