### ISSUE TITLE
update cuda 9.2

### ISSUE THREAD

**Issue by dromosys** [Kaggle/docker-python#388]

**Comment by rosbo** [comment]
Hi dromosys,

This is already on our radar. I am upgrading the NVIDIA driver version this week which is a prerequisites for installing cuda 9.2.

Stay tuned.

**Comment by rosbo** [comment]
The NVIDIA driver has been updated to a version that supports cuda 9.2. 

Next up, installing cuda 9.2 on the image. 

Thank you for your patience

**Comment by rosbo** [comment]
We have released a new Docker image to Kaggle Kernels earlier today that includes cuda 9.2
