### ISSUE TITLE
Updating to fastai version 1 

### ISSUE THREAD

**Issue by salilmishra23** [Kaggle/docker-python#397]
Since the stable version of PyTorch 1.0 is released. Can we now get access to fastai version 1 of the library in Kaggle kernels?

**Comment by rosbo** [comment]
We are actively working on this and should make it available in Kaggle Kernels soon.

Stay tuned

**Comment by rosbo** [comment]
Hi @salilmishra23,

We release a new Python docker images to Kaggle Kernels. It now uses PyTorch 1.0 and fastai 1.0.

Thank you for your patience

**Comment by KumarArindam** [comment]
I am still getting the import module error. Could anyone please specify as to how to get around the error?

Thanks in advance.

**Comment by rosbo** [comment]
@KumarArindam can you paste the specific modules you are trying to import? Thank you

**Comment by KumarArindam** [comment]
@rosbo  i am trying to import the version 0.7 of the fastai. I am unable to downgrade it. Any help would be appreciated. Thank You.

**Comment by rosbo** [comment]
Hi @KumarArindam,

You can downgrade to fastai 0.7.0 by following these instructions:
https://www.kaggle.com/rosebv/downgrade-fastai-to-0-7-0

Let me know if you encounter any issues after following these steps.

Thank you
