### ISSUE TITLE
Update tensorflow to 1.12

### ISSUE THREAD

**Issue by hadaev8** [Kaggle/docker-python#398]

**Comment by rosbo** [comment]
We have released a new image earlier today that include tensorflow 1.12.

**Comment by hadaev8** [comment]
Hmm, any ideas why 
data = tf.data.Dataset.from_tensor_slices((X, y))
data = data.apply(tf.data.experimental.shuffle_and_repeat(buffer_size=len(X)))
raise error in kaggle while it ok in google colab?

**Comment by rosbo** [comment]
Hi @hadaev8,

Do you have GPU enabled?

**Comment by hadaev8** [comment]
Yes, im on gpu, will wait.

**Comment by rosbo** [comment]
@hadaev8 tensorflow 1.12 is available on GPU now.
