### ISSUE TITLE
image on docker has not been built

### ISSUE THREAD

**Issue by simonm3** [Kaggle/docker-python#40]
The last build on docker hub is 3 months ago; and the dockerfile shown there is much smaller than the one on github. I am new to docker but I believe there is a setting to automatically build.

**Comment by nerdcha** [comment]
Yes, we used to use the auto-builds on Docker Hub. It's great, but it's designed for the a certain style of Docker containers, where they're very specialised and only take a few minutes to build. Our type of image does not play well with it.

A few months ago, we switched to building all our images on our own worker machines, then doing a `docker push` to send them up to the Hub. You can see the latest push time in the subtitle of the Docker Hub page. If you do a `docker pull kaggle/python`, you'll get that latest image.

**Comment by simonm3** [comment]
OK thanks.....but the dockerfile tab in the hub has a different script. It
is shorter but with a different base. Are you saying the image is up to
date but the script is not?

**Comment by nerdcha** [comment]
Ah, I see what you mean — it seems that Docker Hub stopped syncing the README and Dockerfile when we turned off the auto-builds. Yes, those are stale now but the image is definitely up to date.

**Comment by nerdcha** [comment]
The current and active versions of those files live in this very Github repo.

**Comment by simonm3** [comment]
OK thanks. Perhaps you can push the dockerfile too? Or if not then put a
note in there to avoid confusion.

**Comment by nerdcha** [comment]
Doesn't seem possible without destroying and recreating the repo, but I've added a clarifying note to the Readme. Thanks for pointing that ou!
