### ISSUE TITLE
Need new packages

### ISSUE THREAD

**Issue by daqisun** [Kaggle/docker-python#407]
Hi there, 

Could you please help me install fastai.nlp and fastai.structured and fastai.column_data?

Many thanks.

Best,
Daqi

**Comment by rosbo** [comment]
Hi @daqisun, 

`fastai.nlp`, `fastai.structured` and `fastai.column_data` are modules of fastai `0.7`.

Kaggle Kernels uses fastai `1.0`. You should look at the fastai documentation to use the new modules like `vision`, `text` or `tabular`:
https://docs.fast.ai/

Thank you
