### ISSUE TITLE
How do I install tsfresh at Internet blocked?

### ISSUE THREAD

**Issue by OhMyGodness** [Kaggle/docker-python#415]
I can use the code "!pip install tsfresh" in the cell to install the tsfresh package when the internet is connected, but when I change the "internet connected" to "internet blocked", the tsfresh can't used in the next cell. Showing import error when "import tsfresh".

**Comment by rosbo** [comment]
Any reasons why you don't want to leave the "internet connected"?

Thank you

**Comment by BishopWolf** [comment]
That's odd, unless tsfresh is using some internet stuff, it shall be installed to your own docker container and be accessible ever since. Please check if you can use it in your own system without internet. If not you have to let the internet connected.

**Comment by OhMyGodness** [comment]
> 
> 
> Any reasons why you don't want to leave the "internet connected"?
> 
> Thank you

Since the competiton don't allow the internet connected,and using the custom docker.[https://www.kaggle.com/c/two-sigma-financial-news](url)

**Comment by OhMyGodness** [comment]
> 
> 
> That's odd, unless tsfresh is using some internet stuff, it shall be installed to your own docker container and be accessible ever since. Please check if you can use it in your own system without internet. If not you have to let the internet connected.

I have  installed the tsfresh with the internet connected,but the competion [https://www.kaggle.com/c/two-sigma-financial-news](url)  ask us must keep the internet blocked and don't allow use the custom docker, it means I have to use the lastest available docker and it not install the tsfresh package.

**Comment by rosbo** [comment]
Given that the `tsfresh` package is popular (> 3000 starts on GitHub), I have added the package to our base image. Our next release will include it (we release a new image to Kaggle Kernels roughly every other week).

Thank you

**Comment by OhMyGodness** [comment]
> 
> 
> Given that the `tsfresh` package is popular (> 3000 starts on GitHub), I have added the package to our base image. Our next release will include it (we release a new image to Kaggle Kernels roughly every other week).
> 
> Thank you

This is exciting for me. Dose this mean I can import tsfresh directly now?Thank you.

**Comment by rosbo** [comment]
Yes, you will be able to once we release a new image to Kaggle Kernels (we release every ~2 weeks, our last release was earlier this week).

**Comment by OhMyGodness** [comment]
> Yes, you will be able to once we release a new image to Kaggle Kernels (we release every ~2 weeks, our last release was earlier this week).

Just now when I "import tsfresh" directly,it show "no module named 'tsfresh'",is there" something wrong?I just use the docker "Latest available".

**Comment by OhMyGodness** [comment]
> Yes, you will be able to once we release a new image to Kaggle Kernels (we release every ~2 weeks, our last release was earlier this week).

Or should I do something to update the Kaggle Kernels?

**Comment by OhMyGodness** [comment]
> Yes, you will be able to once we release a new image to Kaggle Kernels (we release every ~2 weeks, our last release was earlier this week).

Beg you! I am now joining in the competition [https://www.kaggle.com/c/two-sigma-financial-news](url),there are only serveral days to deadline,I must fix this problem "could not import tsfresh".Beg you helping me to solve this problem urgently,thank you very much!

**Comment by rosbo** [comment]
Hi @OhMyGodness 

This change hasn't been released yet.

As I mentioned above, we will release a new Docker image with `tsfresh` next week. We want to wait after the Two Sigma competition close to avoid breaking competitor's solution in the last days of the competition. Each new Docker image release updates several Python packages and we want to offer a stable environment in the last days leading to the end of the competition. 

I encourage you to look at other libraries already included in our Docker image to achieve what you wanted to do with `tsfresh`:
https://github.com/Kaggle/docker-python/blob/master/Dockerfile

Thank you

**Comment by rosbo** [comment]
@OhMyGodness `tsfresh` is now available in Kaggle Kernels.
