### ISSUE TITLE
Add lightgbm python bindings

### ISSUE THREAD

**Issue by tobigithub** [Kaggle/docker-python#42]
Hi,
please add the lightgbm python package 
https://github.com/Microsoft/LightGBM/tree/master/examples/python-guide  

Reason:
3-8 times faster than xgboost, potentially more accurate and less memory required
https://github.com/Microsoft/LightGBM/wiki/Experiments#comparison-experiment  
Tnx

**Comment by nerdcha** [comment]
Thanks for the suggestion! We've added the package and deployed it, so you can use it in Kernels now. We'd love to see a demo on a dataset or a competition…

**Comment by tobigithub** [comment]
Cool!
that was quick, thanks so much.
