### ISSUE TITLE
 ModuleNotFoundError: No module named 'arff'

### ISSUE THREAD

**Issue by smrdhkh** [Kaggle/docker-python#425]

**Comment by rosbo** [comment]
The [arff](https://pypi.org/project/arff/#history) package is not installed on our image at the moment. Looking at the history of this package, it doesn't seem like it is actively maintained anymore and therefor, we won't add it to our base image.

If you need the package, I encourage you to try the following steps:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Thank you
