### ISSUE TITLE
Please Add tsfresh to kernel

### ISSUE THREAD

**Issue by xuanming123** [Kaggle/docker-python#429]
Hi, I am currently in the competition of Two Sigma: Using News to Predict Stock Movements, which would close soon in next 2 days. tsfresh is a very important component in my new solution, so can you guys help to install this package? Since this competition doesn`t allow any internet access or a custom package, I cannot even submit my latest solution without this package. 

Anxiously waiting for your response.

Thanks

**Comment by rosbo** [comment]
We added `tsfresh` to our Docker image but we will release it to Kaggle Kernels after the Two Sigma competition closes to provide a stable environment in the last days leading to the end of the competition. See #415 

Thank you
