### ISSUE TITLE
Please add groupy

### ISSUE THREAD

**Issue by zhangyhhong** [Kaggle/docker-python#432]
Please add this package groupy:
[https://github.com/adambielski/GrouPy](https://github.com/adambielski/GrouPy)
This is a very useful package for group equivariant convolution of images, which needs GPU to run and cannot be installed by pip.
Thanks.

**Comment by Philmod** [comment]
Hey,

Have you tried to follow this [guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) to install it on your kernel?

Cheers,
Philmod
