### ISSUE TITLE
Add h2oai/datatable package

### ISSUE THREAD

**Issue by tunguz** [Kaggle/docker-python#436]
Hi there,

Would it be possible to install Python datatable package:

https://github.com/h2oai/datatable

Thank you,

Bojan

**Comment by rosbo** [comment]
Hi @tunguz 

Have you tried following these instructions to add it to your kernel?
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Thank you

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
