### ISSUE TITLE
Add package object_detection

### ISSUE THREAD

**Issue by vidit2011998** [Kaggle/docker-python#437]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1d367dcfbb33> in <module>()
     17 
     18 from PIL import Image
---> 19 from object_detection.utils import dataset_util
     20 from collections import namedtuple, OrderedDict
     21 

ModuleNotFoundError: No module named 'object_detection'

**Comment by rosbo** [comment]
Hi @vidit2011998,

Have you tried following these instructions to add this library to your kernel?
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Thank you

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
