### ISSUE TITLE
install pyperclip as  pyperclip.copy() is not working

### ISSUE THREAD

**Issue by vishalkumarchaudhary** [Kaggle/docker-python#439]
After install ```xclip``` we need to restart the local computer and then it works but when we restart the kaggle kernel, we need to install everything again. Can anyone suggest how to make the following code workable without any error in kaggle?
``` 
import pyperclip as p
p.copy("Some string")
```

**Comment by rosbo** [comment]
Hi @vishalkumarchaudhary,

What is your use case for using pyperclip in a Kaggle Kernel?

Thank you
