### ISSUE TITLE
Keras warning fails

### ISSUE THREAD

**Issue by psinger** [Kaggle/docker-python#444]
Since today, I receive the following error when using `fit_generator` with callbacks in Keras:

```
/opt/conda/lib/python3.6/site-packages/Keras-2.2.4-py3.6.egg/keras/callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
     93                 'Method (%s) is slow compared '
     94                 'to the batch update (%f). Check your callbacks.', hook_name,
---> 95                 delta_t_median)
     96         if hook == 'begin':
     97             self._t_enter_batch = time.time()

TypeError: integer argument expected, got float

```

Apparently, the issue is with either the warnings package, or something that changed in Keras.

Respective code can be seen in https://github.com/keras-team/keras/blob/master/keras/callbacks.py at lines 92 and onwards.

If I remove my callbacks, everything is fine.

**Comment by rosbo** [comment]
Hi @psinger,

We updated our Python Docker image in which Kaggle Kernels run yesterday.

If you can share your kernels with me (https://www.kaggle.com/rosebv), I can take a look.

Thank you

**Comment by psinger** [comment]
@rosbo Sorry can't share, but you can pretty easily re-create it by just running line 92 of https://github.com/keras-team/keras/blob/master/keras/callbacks.py with some values. I have also reported it to keras https://github.com/keras-team/keras/issues/12069#issuecomment-455638055.

**Comment by rosbo** [comment]
Based on the answer from issue you reported to Keras, this is an issue with the Keras package and not Kaggle Kernels. 

We update Python packages to the their latest version ~ every other week. Once a fix is released by Keras. Kaggle Kernels will soon have it.

Thank you for reporting.
