### ISSUE TITLE
add xlearn package

### ISSUE THREAD

**Issue by chizhu** [Kaggle/docker-python#445]
Could you add xlearn package for us to use ffm? many thx!

**Comment by Philmod** [comment]
Hey,

Have you tried to follow this [guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) to install it on your kernel?

Cheers,
Philmod

**Comment by chizhu** [comment]
emm...for kernel competition which  can not access internet.Thank you all the same.

**Comment by chizhu** [comment]
emm...for kernel competition which can not access internet.Thank you all the same.

**Comment by Philmod** [comment]
Hey @chizhu, is it

**Comment by Philmod** [comment]
I will add `xlearn`, stay tuned...

**Comment by Philmod** [comment]
@chizhu Could you create a Pull Request adding the package with a simple unit test?

You can find a few examples like this one https://github.com/Kaggle/docker-python/pull/593
