### ISSUE TITLE
GDAL package not able to install

### ISSUE THREAD

**Issue by dhruvil009** [Kaggle/docker-python#449]
I have been working with some geospatial image data and would be really nice if I can access them using gdal

**Comment by rosbo** [comment]
Have you tried following these instructions to add this package to your kernel:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
