### ISSUE TITLE
Add matplotlib/mpl_finance package

### ISSUE THREAD

**Issue by commcad** [Kaggle/docker-python#456]
As the title says, I am somehow unable to open a pull request. Grateful if someone could do this on my behalf, I'd appreciate. Having trouble installing Custom Package in the Kernel, it wont let me do it also.

Thanks

Package: matplotlib/mpl_finance
Ref: https://github.com/matplotlib/mpl_finance

**Comment by rosbo** [comment]
Have you tried following these instructions to add this package to your kernel?
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
