### ISSUE TITLE
Add vaderSentiment package

### ISSUE THREAD

**Issue by NazarioR9** [Kaggle/docker-python#457]
Hello Kaggle Team,

I've installed 'vaderSentiment' on my custom docker. But I could'nt use it because it was't allowed in the competion. I also tried using it via 'NLTK' (by using "import nltk.sentiment.vader" ) but it failed to load it.
So can you please add it (It's a sentiment analysis library).
Thanks

**Comment by rosbo** [comment]
Hi @NazarioR9,

Given that this is a very popular package (1000+ starts on GitHub) we would accept a PR adding this package with some tests. See instructions here:
https://github.com/Kaggle/docker-python#opening-a-pull-request

You can tag me in the PR and I will make sure to review it promptly.

Thank you

**Comment by rosbo** [comment]
If you are still interested in this package, feel free to reopen this issue and follow the instructions I have posted above. 

Thank you
