### ISSUE TITLE
Add pydotplus package

### ISSUE THREAD

**Issue by bestfit05** [Kaggle/docker-python#467]
unable to import pydotplus

**Comment by rosbo** [comment]
You can try following these instructions to add this package to your Kaggle Kernels:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by Patil2099** [comment]
@rosbo Can I work on this issue?

**Comment by rosbo** [comment]
@Patil2099 Have you tried the instructions I posted above?

We are trying to limit the # of packages we include into our base image. Each new package we add makes dependencies management harder to manage and make our images larger which is someone we want to keep under control.

Thank you
