### ISSUE TITLE
Getting module not found error 

### ISSUE THREAD

**Issue by premvardhan** [Kaggle/docker-python#471]
![module_not_found](https://user-images.githubusercontent.com/26577403/52480390-92a5a800-2bd1-11e9-9614-c78d6e673510.PNG)

Please add this module too.

**Comment by rosbo** [comment]
Hi @premvardhan 

Which top-module are you trying to use?

**Comment by premvardhan** [comment]
Hi @rosbo 
distance module is not installed which is use to compute similarities between arbitrary sequences. 
I tried to install myself but was unable to install. 
I tried the following command (!pip install distance) 
Please resolve it.

**Comment by premvardhan** [comment]
Hi @rosbo 
I tried using something like this and it worked for me
In the kernel:
1) Setting (at the right bottom of the kernel):
Turn the internet "ON"

2) In the kernel:
!pip install yourpackage
