### ISSUE TITLE
An error while building docker-python image

### ISSUE THREAD

**Issue by yell0w4x** [Kaggle/docker-python#472]
While building the image this error occurs:

`The command '/bin/sh -c apt-get -y install zlib1g-dev liblcms2-dev libwebp-dev libgeos-dev &&     pip install matplotlib==2.2.3 &&     pip install pyshp &&     pip install pyproj &&     cd /usr/local/src && git clone https://github.com/matplotlib/basemap.git &&     cd basemap &&     git checkout v1.1.0 &&     python setup.py install &&     pip install basemap --no-binary basemap &&     apt-get -y install libsasl2-dev &&     apt-get install -y libpq-dev &&     pip install ibis-framework &&     yes | conda install proj4 &&     pip install packaging &&     pip install shapely &&     pip install cartopy &&     pip install mxnet &&     pip install --upgrade numpy &&     apt-get install -y default-jdk &&     cd /usr/local/src && mkdir h2o && cd h2o &&     wget --no-verbose http://h2o-release.s3.amazonaws.com/h2o/latest_stable -O latest &&     wget --no-verbose --no-check-certificate -i latest -O h2o.zip && rm latest &&     unzip h2o.zip && rm h2o.zip && cp h2o-*/h2o.jar . &&     pip install `find . -name "*whl"` &&     python -c "from keras.models import Sequential"  &&     sed -i 's/theano/tensorflow/' /root/.keras/keras.json  &&     python -c "from keras.models import Sequential; from keras import backend; print(backend._BACKEND)" &&     mkdir -p /tmp/.keras && cp /root/.keras/keras.json /tmp/.keras &&     /tmp/clean-layer.sh' returned a non-zero code: 132`

If it matters the platform is:
`[root@s141537 docker-python]# docker --version`
`Docker version 18.09.1, build 4c52b90`
`[root@s141537 docker-python]# rpm -q centos-release`
`centos-release-7-6.1810.2.el7.centos.x86_64`

Thanx in advance.

**Comment by yell0w4x** [comment]
I found out exactly this one causes the error:

`The command '/bin/sh -c python -c "from keras.models import Sequential"' returned a non-zero code: 132`

**Comment by rosbo** [comment]
Interesting... It works on our ci server and on my dev machine.

Can you run `python -c "from keras.models import Sequential"`  in an interactive container using the image the `RUN` command you pasted above ran in?

To do this, you can look at the `./build` script logs. You should see: 

```
Feb 11 02:12:32 Step 14/31 : RUN apt-get -y install zlib1g-dev liblcms2-dev libwebp-dev libgeos-dev &&     pip install matplotlib==2.2.3 &&     pip install pyshp &&     pip install pyproj &&     cd /usr/local/src && git clone https://github.com/matplotlib/basemap.git &&     cd basemap &&     git checkout v1.1.0 &&     python setup.py install &&     pip install basemap --no-binary basemap &&     apt-get -y install libsasl2-dev &&     apt-get install -y libpq-dev &&     pip install ibis-framework &&     yes | conda install proj4 &&     pip install packaging &&     pip install shapely &&     pip install cartopy &&     pip install mxnet &&     pip install --upgrade numpy &&     apt-get install -y default-jdk &&     cd /usr/local/src && mkdir h2o && cd h2o &&     wget --no-verbose http://h2o-release.s3.amazonaws.com/h2o/latest_stable -O latest &&     wget --no-verbose --no-check-certificate -i latest -O h2o.zip && rm latest &&     unzip h2o.zip && rm h2o.zip && cp h2o-*/h2o.jar . &&     pip install `find . -name "*whl"` &&     python -c "from keras.models import Sequential"  &&     sed -i 's/theano/tensorflow/' /root/.keras/keras.json  &&     python -c "from keras.models import Sequential; from keras import backend; print(backend._BACKEND)" &&     mkdir -p /tmp/.keras && cp /root/.keras/keras.json /tmp/.keras &&     /tmp/clean-layer.sh
Feb 11 02:12:33  ---> Running in 16a93d1fde95
```

`16a93d1fde95` is the container id.

You can commit it to create an image with by running:
```
docker commit 16a93d1fde95
```

This command will output an <IMAGE_HASH>.

You can use it to start a new container:

```
docker run -it <IMAGE_HASH> /bin/bash
(container) $ python
(python) $ from keras.models import Sequential
```

Then, paste the full error output of the command.

Thank you

**Comment by yell0w4x** [comment]
I've commented out lines regard to `keras` while building and was able to build the image. I ran the `import` inside the container based on this image. And the result is here.

    [root@s141537 docker-python]# docker run --rm -it kaggle/python-build /bin/bash 
    (base) root@0663ab6af817:/# python
    Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from keras.models import Sequential
    Using TensorFlow backend.
    Illegal instruction (core dumped)

The python interpreter crushes. The core dump is created, but it's size 506MB.  The result is the same for only `import keras`.

**Comment by jpzhangvincent** [comment]
I had the same issue. Is there any fix? Thanks.

**Comment by rosbo** [comment]
Keras and TensorFlow released a new version, can you try again and see if it works on your machine? 

It is hard to debug since it works both on our CI server and my machine (VM running in GCP).

**Comment by reitzig** [comment]
I saw a similar thing. The issue seemed to be that Debian Buster images don't work on our Jenkins server, which runs some form of RHEL7 with a 3.10 kernel (not sure if _that's_ the issue). Using the Debien Stretch variants of the Python Docker images solved the problem.
