### ISSUE TITLE
Add new package classification_models

### ISSUE THREAD

**Issue by Franky1** [Kaggle/docker-python#480]
https://github.com/qubvel/classification_models

**Comment by rosbo** [comment]
We are in the process of upgrading our image to use TensorFlow 2.0.

We will wait before adding packages depending on it until we have released it.

Thank you

**Comment by rosbo** [comment]
For the time being, I recommend you follow these instructions on how to install a package into your own kernel:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages
