### ISSUE TITLE
add package auto-sklearn

### ISSUE THREAD

**Issue by picarus** [Kaggle/docker-python#481]
Hello,
  I would like package auto-sklearn to be added .
  It is not a trivial task,  I have tried to add it to my notebook following the installation instructions:

curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install

 and found some version issues:

> yellowbrick 0.9 has requirement scikit-learn>=0.20, but you'll have scikit-learn 0.19.2 which is incompatible.
> kmeans-smote 0.1.0 has requirement imbalanced-learn<0.4,>=0.3.1, but you'll have imbalanced-learn 0.5.0.dev0 which is incompatible.
> featuretools 0.5.1 has requirement scikit-learn>=0.20.0, but you'll have scikit-learn 0.19.2 which is incompatible.
> dask-ml 0.11.0 has requirement scikit-learn>=0.20, but you'll have scikit-learn 0.19.2 which is incompatible.
> imbalanced-learn 0.5.0.dev0 has requirement scikit-learn>=0.20, but you'll have scikit-learn 0.19.2 which is incompatible.
> 

and also:

>  Failed building wheel for pyrfr

Would be good if someone could check if there is an easy way to add.

**Comment by kmjoshi** [comment]
Following the steps [here](https://mikulskibartosz.name/how-to-install-scikit-automl-in-a-kaggle-notebook-bfd9fbd573ed) I was able to install auto-sklearn to my notebook. 
The key was to install swig:
```
!apt-get remove swig
!apt-get install swig3.0 
!ln -s /usr/bin/swig3.0 /usr/bin/swig
```
