### ISSUE TITLE
Importing datasets package through pip

### ISSUE THREAD

**Issue by KrunalPatel2194** [Kaggle/docker-python#482]
Hi i was trying to import a datasets package for my convoluted neural network, but couldn't do that. on Keggle kernel is says
    Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f325f645518>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/datasets/

on local it says pip version is not having SSl certificate.

**Comment by Franky1** [comment]
@KrunalPatel2194 Did you enable **Internet access** in your Kaggle kernel?

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
