### ISSUE TITLE
igraph import  fails

### ISSUE THREAD

**Issue by NotAnonymity** [Kaggle/docker-python#488]
/opt/conda/lib/python3.6/site-packages/igraph/__init__.py in <module>()
     34 from igraph._igraph import *
     35 from igraph._igraph import __version__, __build_date__
---> 36 from igraph.clustering import *
     37 from igraph.cut import *
     38 from igraph.configuration import Configuration

/opt/conda/lib/python3.6/site-packages/igraph/clustering.py in <module>()
     34 from igraph.configuration import Configuration
     35 from igraph.datatypes import UniqueIdGenerator
---> 36 from igraph.drawing.colors import ClusterColoringPalette
     37 from igraph.statistics import Histogram
     38 from igraph.summary import _get_wrapper_for_width

/opt/conda/lib/python3.6/site-packages/igraph/drawing/__init__.py in <module>()
     25 from igraph.configuration import Configuration
     26 from igraph.drawing.colors import Palette, palettes
---> 27 from igraph.drawing.graph import DefaultGraphDrawer
     28 from igraph.drawing.utils import BoundingBox, Point, Rectangle, find_cairo
     29 from igraph.utils import _is_running_in_ipython, named_temporary_file

/opt/conda/lib/python3.6/site-packages/igraph/drawing/graph.py in <module>()
     25                                        AbstractXMLRPCDrawer
     26 from igraph.drawing.colors import color_to_html_format, color_name_to_rgb
---> 27 from igraph.drawing.edge import ArrowEdgeDrawer
     28 from igraph.drawing.text import TextAlignment, TextDrawer
     29 from igraph.drawing.metamagic import AttributeCollectorBase

/opt/conda/lib/python3.6/site-packages/igraph/drawing/edge.py in <module>()
     15 from math import atan2, cos, pi, sin, sqrt
     16 
---> 17 cairo = find_cairo()
     18 
     19 class AbstractEdgeDrawer(object):

/opt/conda/lib/python3.6/site-packages/igraph/drawing/utils.py in find_cairo()
    411     for module_name in module_names:
    412         try:
--> 413             module = __import__(module_name)
    414             break
    415         except ImportError:

/opt/conda/lib/python3.6/site-packages/cairocffi/__init__.py in <module>()
     39 
     40 
---> 41 cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
     42 
     43 

/opt/conda/lib/python3.6/site-packages/cairocffi/__init__.py in dlopen(ffi, *names)
     36             except OSError:
     37                 pass
---> 38     raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
     39 
     40 

OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 #

**Comment by rosbo** [comment]
Hi @NotAnonymity,

Can you share the code you are trying to run. I can't reproduce your issue.

I can successfully run the following in kernel:
```
import igraph
print(igraph.__version__)
from igraph import *
g  = Graph()
print(g)
```

And this outputs:

```
0.7.1
IGRAPH U--- 0 0 --
```

**Comment by NotAnonymity** [comment]
Thanks for your reply.
It works now.
