### ISSUE TITLE
load all spacy language models

### ISSUE THREAD

**Issue by cedspam** [Kaggle/docker-python#497]
only the english language model is loaded for now, could you load all those aviable? there doesn't seems  to be that much different models aviable
there information about loading the language model in this page
https://spacy.io/usage/models

there could be all this command list in the dockerfile instead of just the first one
```
# out-of-the-box: download best-matching default model
python -m spacy download en
python -m spacy download de
python -m spacy download es
python -m spacy download pt
python -m spacy download fr
python -m spacy download it
python -m spacy download nl
python -m spacy download xx
```

**Comment by rosbo** [comment]
Hi @cedspam,

I would recommend enabling Internet Access in your Kaggle Kernels to download the other language models.

Each model is roughly 1 GB. We are trying to keep this Docker image at a reasonable size (right now, it is around 15GB).

Thank you
