### ISSUE TITLE
Add new package PyPDF2

### ISSUE THREAD

**Issue by jitendragupta69** [Kaggle/docker-python#499]
Add new package PyPDF2

**Comment by Philmod** [comment]
Hey @jitendragupta69 ,

Have you tried to follow this [guide](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) to install it on your kernel?

Cheers,
Philmod

**Comment by Philmod** [comment]
Closing this bug, feel free to reopen if [installing the package](https://github.com/Kaggle/docker-python/wiki/Missing-Packages) yourself doesn't help.
