### ISSUE TITLE
Add option to write notebooks in Swift For TensorFlow

### ISSUE THREAD

**Issue by miwojc** [Kaggle/docker-python#506]
Swift For TensorFlow (S4TF) notebooks can be run at Colab.

Would be great to run S4TF notebooks in kernels platform! Thank you!

https://colab.research.google.com/github/tensorflow/swift/blob/master/docs/site/tutorials/walkthrough.ipynb

**Comment by rosbo** [comment]
Hi @miwojc,

We don't have plans at this point for supporting a new language (Swift) but I will keep this issue open and I encourage people to 👍 the issue if it is something you would like. If there is enough interest, we might revisit our decision.

Thank you
