### ISSUE TITLE
Tensorflow 2.0.0a0 support for Jupyter Notebook Kernel and Script Kernel commits

### ISSUE THREAD

**Issue by eliasgoodale** [Kaggle/docker-python#507]
When creating a new kernel on kaggle for competitions, the script type kernel allows you to install tensorflow 2.0.0-alpha-0 without any issues as long as you have internet enabled and you aren't using GPU. However, upon commiting your work for submission to competition, the version is rolled back to the default 1.12. Installing the package from the settings menu fails with "Error: Image tagging failed." for all versions of tensorflow. In the Jupyter notebook style kernel, the installation fails with error "Could not find a version that satisfies the requirement tensorflow==2.0.0-alpha0 (from versions: ) No matching distribution found for tensorflow==2.0.0-alpha0".

**Comment by Philmod** [comment]
Have you tried using `!pip install`? 
Example: https://www.kaggle.com/philmod/tensorflow-2-0-0-alpha?scriptVersionId=11445848

**Comment by eliasgoodale** [comment]
Yes, I've tried this. However, when committing and running the code the version always rolls back to 1.12, the default version.

**Comment by Philmod** [comment]
Can you share with me a kernel with that problem please?

**Comment by eliasgoodale** [comment]
Here is the URL to my kernel. https://www.kaggle.com/egoodale/boosted-trees. In addition I have added you edit privileges to the kernel. You will have to delete the eval at the top, And I've printed the version below the imports so you can see the commit difference, even when installing tensorflow 2.0 successfully using the command !pip install tensorflow==2.0.0a0. Thanks for your time in helping me resolve this issue.

**Comment by Philmod** [comment]
Hey @eliasgoodale, as commented in the kernel, I didn't see the `!pip install` command?

**Comment by eliasgoodale** [comment]
I'm not sure what you mean. Where were you expecting to see the command displayed?

**Comment by eliasgoodale** [comment]
If we are unable to do it in the script style kernels and we can only do it in the notebook style thats totally fine I can just change the kernel

**Comment by Philmod** [comment]
Ah I see. You are right, the script is not behaving the same when it's interactive vs commit. We would love to improve that soon.

**Comment by eliasgoodale** [comment]
Sounds good. Thanks so much for taking the time to help me solve this issue.
