### ISSUE TITLE
h2o4gpu support for Notebook Kernels and Script Kernels

### ISSUE THREAD

**Issue by sh1ng** [Kaggle/docker-python#521]
Hi,

* It's not possible to install pip package with GPU enabled.
* Even when it's disabled installation is unsuccessful with error `Error: The command '/bin/sh -c pip install h2o4gpu' returned a non-zero code: 1` 
* The package is quite big(~300Mb)

**Comment by erdalsivri** [comment]
We don't prefer to install new packages unless they are very popular and can benefit many Kagglers.

I was able to install this package with `pip install`. I just followed the instructions and used the cuda9 version. Make sure you follow the Prerequisites section too: 

https://github.com/h2oai/h2o4gpu#prerequisites
