### ISSUE TITLE
Upgrade to spaCy 2.1.3

### ISSUE THREAD

**Issue by bongbang** [Kaggle/docker-python#522]
I asked this on the Kaggle forum and was advised to submit a pull request. So I forked and cloned and built a docker image and failed after downloading an ungodly number of bytes.

Surely, there's a better way to request un upgrade to an already installed package (v. 2.0.18). Can someone take care of this, please? It really should be a snap. There's no need to even edit `Dockerfile`.

**Comment by erdalsivri** [comment]
We don't pin this package to a specific version so the next image release will probably contain the up-to-date version. Will follow up on this issue after we've released the image, hopefully some time next week.

**Comment by erdalsivri** [comment]
`spaCy` version is now 2.1.3 so I am closing this issue:

```python
import spacy
spacy.__version__
'2.1.3'
````
