### ISSUE TITLE
[New Package Request Swifter]

### ISSUE THREAD

**Issue by AdityaSoni19031997** [Kaggle/docker-python#525]
Will be great if  Kaggle can add this light weight package to their docker
https://github.com/jmcarpenter2/swifter

It's faster than Pandas as the author claims it to be..

**Comment by Philmod** [comment]
You can try following these instructions to add this package to your Kaggle Kernels:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by AdityaSoni19031997** [comment]
But if we aren't allowed to use internet connection (e.g. for a kernels
only comp)?

**Comment by Philmod** [comment]
Sorry, but we only install packages with some degree of popularity. I hope you understand.

**Comment by AdityaSoni19031997** [comment]
True! You can close this then, no issues.
Thanks for the consideration :)

**Comment by appleyuchi** [comment]
Can you consider the GPU-edition of Lightgbm?@Philmod
