### ISSUE TITLE
Add new package: colored

### ISSUE THREAD

**Issue by MasterScrat** [Kaggle/docker-python#529]
Writing colored text can be useful for data visualisation.

The `termcolor` package is available, but it hasn't been updated since Jan 13, 2011: https://pypi.org/project/termcolor/

The more modern package `colored` would be a nice addition: https://pypi.org/project/colored/

**Comment by erdalsivri** [comment]
Given that it's very easy to install this package manually and that not many people have asked for this, let's keep it out of our already large image for a while. 

If you want to use this package, enable Internet access on your kernel and add this line to the top:

```
!pip install colored --upgrade
```
