### ISSUE TITLE
allow bokeh js to load from cdns

### ISSUE THREAD

**Issue by anandjeyahar** [Kaggle/docker-python#53]
Hi, 
   At the moment using the bokeh package in kaggle notebooks won't actually render the plots as the page/firewall/webserver blocks loading the js from bokeh's default cdn servers. This comes in the way of interactive(zoom, pan) visualizations that [bokeh](http://bokeh.pydata.org/en/latest/) can provide.  
So you can either load bokeh js, from that cdn, or host it in kaggle's cdn and redirect requests to that cdn to kaggle's .

**Comment by nerdcha** [comment]
Thanks, yes, that's something that we're keen to enable as soon as we can!
