### ISSUE TITLE
How to correlate gcr.io version tag with GitHub commit?

### ISSUE THREAD

**Issue by marketneutral** [Kaggle/docker-python#532]
Hi, I am having an issue with the latest `gcr.io/kaggle-images/python` integration with JupyterHub (I posted [this question](https://www.kaggle.com/questions-and-answers/88860) in the Kaggle Forums). I can get `v50` to work, but not `v51`. How do I correlate the commits in this repo to the `gcr.io` version tag so I can do a diff and see what changed? Thanks.

**Comment by Philmod** [comment]
It looks like the v51 was built on March 12th (the v50 on Feb 21st).

Do you have a simple way to reproduce the bug with `docker run gcr.io/kaggle-images/python:v51 ...`?

**Comment by marketneutral** [comment]
Thank you. I was hoping to see `v51`  etc. as a `git tag` on some commit or for there to be a formal release on the GitHub release tab, but that's not the case. The dates you are quoting are from the "Uploaded" column in the container registry, right? I've tried to correlate those dates to the dates of the GitHub commits on the master branch using `git log` but it's unclear that the commit dates/times match the uploading of the image to gcr.

I cannot repro the bug running the image from the command line. Running `docker run gcr.io/kaggle-images/python:latest ...` works fine.

The problem I have is that I use JupyterHub and, within that, Docker Spawner. As such, the hub spawns this image. This is where it fails and there are no helpful error messages. I suspect that there is a conflict between my version of JupyterHub and the Kaggle Dockerfile. My `jupyterhub_config.py` looks something like

```python
   :
   :
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.remove_containers = True
c.DockerSpawner.image_whitelist = {
    'Data Science (Python)': 'kagglepython'
}
   :
   :
```
where `kagglepython` is my local image built with `docker build --tag kagglepython .`. 

I can successfully run `kagglepython` (with the latest Dockerfile from this repo) as a single-user server

```
docker run --rm -v /srv/jupyterhub/home/jlarkin:/tmp/working -w=/tmp/working -p 8888:8888 -it kagglepython jupyter notebook --no-browser --allow-root --ip="0.0.0.0" --notebook-dir=/tmp/working --NotebookApp.token=''
```

That single user run works for `v51` up to `latest`. However after `v51` I cannot get it to spawn from JupyterHub.
