### ISSUE TITLE
Requesting FFMPEG library

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#540]
FFMPEG makes it easier to use FuncAnimation in `matplotlib` to export vidoes as MP4 (it also is useful for importing)

**Comment by kmader** [comment]
apparently this can be mitigated with
```
!apt install -y ffmpeg
```

**Comment by mmiakashs** [comment]
Is the imageio-ffmpeg available in kernel offline kernel? I think it is not added. Could you please add this plugin. This is very crucial for video processing.
