### ISSUE TITLE
Requesting h204gpu package - for running ML models on GPU

### ISSUE THREAD

**Issue by Asrst** [Kaggle/docker-python#543]
`h2o4gpu` can be useful to run the  ml models on the gpu.

tried with `pip install h2o4gpu` but giving version conflicts with other existing packages and its not working. 

as of now, working fine with google colab.

**Comment by Philmod** [comment]
Have you tried installing the package following these [instructions](https://github.com/Kaggle/docker-python/wiki/Missing-Packages)?
