### ISSUE TITLE
Reinstall allennlp's dependencies when dependency fixed

### ISSUE THREAD

**Issue by Philmod** [Kaggle/docker-python#548]
`allennlp` requires `awscli` which requires a very specific version of `PyYAML` https://github.com/aws/aws-cli/blob/develop/requirements.txt#L14

The latest version of `PyYAML` is already installed, so they collide.

The underlying package has an [open issue](https://github.com/aws/aws-cli/issues/4042) and an [open PR](https://github.com/aws/aws-cli/pull/4015#issuecomment-480319733) to fix this pinned version.

**Comment by Philmod** [comment]
cc @RyujiTamaki who created the initial PR to add `allennlp`.

**Comment by rosbo** [comment]
Fixed in #548.
