### ISSUE TITLE
Open Babel

### ISSUE THREAD

**Issue by PCJimmmy** [Kaggle/docker-python#568]
Using openbabel in Predicting Molecular Properties
 in my kernel
https://www.kaggle.com/pcjimmmy/molecule-with-openbabels-build-molecule

It works often with the following code
!conda install -y -c openbabel openbabel 
import openbabel

A couple of public kernels use this method also.  The site host seems to have an issue - on both my local PC and now my kernel the above fails with the following partial error message a high percentage of the time.  Today I could not get it to work all afternoon.

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/openbabel/noarch/repodata.json>
Elapsed: -

Since this competition has couple of months to run, please add openbabel to the available libraries.

**Comment by erdalsivri** [comment]
Hi @PCJimmmy,

Looks like you did not enable internet in your kernel. Internet is disabled by default. Please go to the `Settings` panel on the right, toggle `Internet` and try running `!conda install -y -c openbabel openbabel` again.

Let us know if you have further questions/issues!
