### ISSUE TITLE
Install Textract (new library) - pip install from kernel , custom package and from Github fails

### ISSUE THREAD

**Issue by AlisonDoucette** [Kaggle/docker-python#571]
Error from Kernel pip:

ERROR: Complete output from command /opt/conda/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-84yhamem/pocketsphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-48wub_78/install-record.txt --single-version-externally-managed --compile:
    ERROR: Error in sitecustomize; set PYTHONVERBOSE for traceback:
    ImportError: ``requests >= 2.18.0`` is required by the ``google.resumable_media.requests`` subpackage.
    It can be installed via
        pip install google-resumable-media[requests].
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    ----------------------------------------
ERROR: Command "/opt/conda/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-84yhamem/pocketsphinx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-48wub_78/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-84yhamem/pocketsphinx/

**Comment by Philmod** [comment]
Can you share your Kernel?

**Comment by AlisonDoucette** [comment]
Hi Phil:

In an effort to make the competition deadline I removed all requirements for not currently supported Kaggle libraries. 

> Can you share your Kernel?
