### ISSUE TITLE
How can I add a psi4 module? 

### ISSUE THREAD

**Issue by MelvinYYY** [Kaggle/docker-python#586]
How can I add a psi4 module? I was able to install the psi4 package a couple weeks ago. But it can't resolve the environment right now when I try to install it. # @ @

**Comment by Philmod** [comment]
You should be able to install the package following these [instructions](https://github.com/Kaggle/docker-python/wiki/Missing-Packages).

Let me know if you run into any issues.

**Comment by MelvinYYY** [comment]
Hi @Philmod ,

I think it can only be installed via the conda command. 

Thanks,

Melvin

**Comment by rosbo** [comment]
Hi @MelvinYYY ,

You can run the following in your kernel to install the psi4 module using conda:

```
conda install psi4
```

Thank you
