### ISSUE TITLE
Please add package Scikit-garden

### ISSUE THREAD

**Issue by PavloFesenko** [Kaggle/docker-python#600]
https://github.com/scikit-garden/scikit-garden

Thank you very much!

**Comment by rosbo** [comment]
Hi @PavloFesenko,

In an effort to limit the size of our Docker Python image, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

I recommend you follow these instructions to install the package in your own Kaggle Kernel:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

I hope that helps.

Thank you
