### ISSUE TITLE
GPU edition of LightGBM

### ISSUE THREAD

**Issue by appleyuchi** [Kaggle/docker-python#606]
I hope kaggle's notebook can add the package "GPU edition of LightGBM"
this need to be compile-style installation.
PIP-style  will make it don't support GPU acceleration.
Thanks~

**Comment by qinhanmin2014** [comment]
+1, any progress here?

**Comment by appleyuchi** [comment]
> +1, any progress here?

no,the service mail of kaggle said that:
only if they think it is popular ,will they consider to install it.

But actually,kaggle almost have less tabular competitions these months.
So I think they will not give it a consideration.

**Comment by appleyuchi** [comment]
> Some kagglers tried to install GPU version of LightGBM manually
> see, e.g.,
> https://www.kaggle.com/vinhnguyen/gpu-acceleration-for-lightgbm

It's very time-consuming,you may don't find that each time you open/restart a notebook,
you have to re-installed it with very long time.

**Comment by appleyuchi** [comment]
> @appleyuchi I'm not sure if I follow the original comment about compile-style installation vs. pip install and that somehow not allowing it make use of the GPU?
> 
> Can you clarify what you mean by this / what the installation steps would look like?
> 
> Would it be possible for you to write an example internet-enabled GPU kernel which installs and tests using the package in a simple way to prove it's installed correctly?
> 
> If you could share that setup with us we might be able to help integrate it into the image.

Thanks for your replies~!
https://www.kaggle.com/vinhnguyen/gpu-acceleration-for-lightgbm

Current lightgbm in notebook:lightgbm-CPU
What      We want  in notebook:lightgbm-GPU

**Comment by appleyuchi** [comment]
I think it really time-wasting 
reinstall lightgbm again and again and again and again...
Please help,thanks

**Comment by qinhanmin2014** [comment]
Why do you close this? @appleyuchi
