### ISSUE TITLE
Detectron2

### ISSUE THREAD

**Issue by miwojc** [Kaggle/docker-python#627]
Hello
Would be great if Detectron2 worked on Kaggle platform. It works on Colab when following this instructions: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

However, in Kaggle, when i follow the install instructions it installs OK to the point where there is an instruction to restart runtime. In kaggle notebook i can restart session. But after that i get error on import detectron2. It also gives the same error without restarting session.
Error: ModuleNotFoundError: No module named 'detectron2'

i would appreciate your hlep!

thank you

**Comment by Philmod** [comment]
Hey @miwojc, 

If you try to restart a Kaggle session, it will be a fresh session.

Feel free to create a PR to install the package in our base image, include a unit test.
