### ISSUE TITLE
add tensorflow-addons

### ISSUE THREAD

**Issue by martin-gorner** [Kaggle/docker-python#638]
Would you consider adding tensorflow-addons to our image ?
 https://github.com/tensorflow/addons
It’s where most of the good pieces of functionality from tf.contrib went in TF 2.0
for example tfa.image.rotate

**Comment by ma7555** [comment]
highly suggest adding it as well

**Comment by amrabed** [comment]
+1 
Any updates on that?

**Comment by rosbo** [comment]
Hi @amrabed,

I opened #814 a few minutes ago to address this. Once that PR is merged, it will be part of our next Docker Python image release. This is currently scheduled to be on June 1st.

Thank you

**Comment by amrabed** [comment]
> Hi @amrabed,
> 
> I opened #814 a few minutes ago to address this. Once that PR is merged, it will be part of our next Docker Python image release. This is currently scheduled to be on June 1st.
> 
> Thank you

Thank you, @rosbo
