### ISSUE TITLE
Add NimbusML python package

### ISSUE THREAD

**Issue by najeeb-kazmi** [Kaggle/docker-python#639]
I would like to use the nimbusml package for a competition that does not permit internet access nor external data sources.

**Comment by rosbo** [comment]
Hi @najeeb-kazmi 

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

Please reopen this issue once this package reaches that threshold.

Thanks for your understanding.
