### ISSUE TITLE
Add new package - sklearn-pandas

### ISSUE THREAD

**Issue by mratsim** [Kaggle/docker-python#66]
Hello Kaggle team,

Can you add the sklearn-pandas package.
Command is "pip install sklearn-pandas" but I'm unable to test it in docker for the moment

_Sklearn-pandas provides a bridge between Scikit-Learn’s machine learning methods and pandas-style Data Frames._
Doc: https://github.com/paulgb/sklearn-pandas

Thanks

**Comment by nerdcha** [comment]
Great idea, thanks! I've added it to the build and it will be deployed shortly.
