### ISSUE TITLE
Add new package - mlxtend

### ISSUE THREAD

**Issue by mratsim** [Kaggle/docker-python#67]
Hello Kaggle team,

Can you add the mlxtend package.
Command is "pip install mlxtend" but I'm unable to test it in docker for the moment

_Mlxtend extends Scikit-learn with an easy to use interface for Ensembling, Voting and Stacking_

Doc: https://rasbt.github.io/mlxtend/

Thanks

**Comment by nerdcha** [comment]
We actually already have it 😄  Currently version 0.5.1.dev0 is installed, about to update to 0.5.1.
