### ISSUE TITLE
Please add JAX to GPU Dockerfile

### ISSUE THREAD

**Issue by marketneutral** [Kaggle/docker-python#679]
Hi,

**"JAX is Autograd and XLA, brought together for high-performance machine learning research."** 

JAX is a Google-sponsored research project with > 5900 GitHub stars: https://github.com/google/jax

*"Why can't users just add this library in their kernels when they need it? Why should we add this to the official gpu.Dockerfile?"* Kaggle Code Competitions typically do not allow internet access and package installs. In these competitions you need to squeeze out every possible compute optimization because the code has to run within a certain time. So, users can't install JAX and JAX would be very valuable. 

I am requesting that you add JAX to the Kaggle GPU Dockerfile. I would make the PR myself but I don't have a GPU to run the tests on. However, here is a Kaggle kernel with the successful install (including unit test):

https://www.kaggle.com/marketneutral/jax-install

The following should be added to `gpu.Dockerfile`:

```Dockerfile

ENV JAX_PYTHON_VERSION=cp36
ENV JAX_CUDA_VERSION=cuda100
ENV JAX_PLATFORM=linux_x86_64
ENV JAX_BASE_URL="https://storage.googleapis.com/jax-releases"

RUN pip install pip install --upgrade $JAX_BASE_URL/$JAX_CUDA_VERSION/jaxlib-0.1.36-$JAX_PYTHON_VERSION-none-$JAX_PLATFORM.whl && \
     pip install --upgrade jax
```

The unit test can be taken from the linked kernel above. 

Thank you.

Also, there was a very nice talk at NeurIPS on JAX: https://slideslive.com/38922046/program-transformations-for-ml-3 starting at 44:26.

**Comment by rosbo** [comment]
@marketneutral Thanks for creating a notebook with a test for it. It is super helpful. I am testing a PR based on your instructions. Once it is merged, it will be part of our next Docker Python image release which should be the first week of January (we prefer not to release a new image just before the Holidays).

Thank you
