### ISSUE TITLE
NVIDIA Video support

### ISSUE THREAD

**Issue by Wegnery219** [Kaggle/docker-python#683]
Hello, I need to use nvidia Video Reader function in a competition. That competition is a kernel-submit competition, and I need to change one setting in gpu.Dockerfile `ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility` to `ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility`
I'm not familiar with kaggle competition, and I have two questions:
1. Can I change the Dockerfile in a kernel-submit competiton? How to change?
2. If I can't, can you update that code in Dockerfile so that the online kernel in browser can use VideoReader in NVIDIA?I really need that, thank you.

**Comment by NicWickman** [comment]
I would also like this added. Being able to use NVIDIA DALI for the deepfake challenge would be a major performance help.

**Comment by Philmod** [comment]
Feel free to make a PR with a unit test.
