### ISSUE TITLE
add pip installable package warcio to docker image

### ISSUE THREAD

**Issue by galtay** [Kaggle/docker-python#689]
Hi kaggle team, would be great to have this python package available, 

https://github.com/webrecorder/warcio

which is used to read the Web ARChive format which is used by Common Crawl to store their data. 
https://commoncrawl.org/the-data/get-started/

**Comment by rosbo** [comment]
Hi @galtay,

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

You can still install the package in your notebook by following these instructions:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Thanks for your understanding.
