### ISSUE TITLE
Errors installing package

### ISSUE THREAD

**Issue by anabeatrizzz** [Kaggle/docker-python#690]
I wish to install tweepy in Kaggle but I received two errors mensages:

> ERROR: Could not find a version that satisfies the requirement tweepy (from versions: none)

> ERROR: No matching distribution found for tweepy

I tried to run `!python -m pip install tweepy`, `!pip3 install tweepy` and `!pip install tweepy` but the errors persist...

**Comment by djherbis** [comment]
Did you close this because you figured out the issue?

**Comment by anabeatrizzz** [comment]
@djherbis no, I closed because I will not use tweepy anymore.
