### ISSUE TITLE
Add pyspark package

### ISSUE THREAD

**Issue by vaidyasm** [Kaggle/docker-python#719]
Have pyspark package available for large-scale data processing in python.

Ref:
* PySpark: https://pypi.org/project/pyspark/
* Apache Spark: https://spark.apache.org/

**Comment by vaidyasm** [comment]
Addressed by PR #720

**Comment by Philmod** [comment]
Hey @vaidyasm,

Thanks for your issue/PR.

Before diving into the PR, I would like to understand better how pyspark is useful in the context of a single Notebook. It seems like this tool shines to create scalable analyses and pipelines. But I don't understand how it would be useful on Kaggle.
Could you tell me a bit more about your use case and how you are planning to use pyspark?

**Comment by vaidyasm** [comment]
Hi @Philmod

It's true that Spark "shines to create scalable analyses and pipelines" and share your concern of running in 'scaled mode' in the single node/notebook environment visible to Kaggle Kernels. However, the additional capabilities provided by Spark have been proven essential in making analysis efforts an effective one. With Spark/PySpark, we can focus on data transformation without having to go through a labyrinth of additional transformations to perform simple aggregations.

As an example, on recently completed competition, a simple multi-column group-by summarize can cause Pandas to start allocating memory until it goes over the limit causing kernels or your local system to crash. A simple use case like this would require you to manually combine the columns, perform group-by aggregation, and then, finally, split the columns. This is after you optimize how data is stored with pandas - categorize your string id columns, skip loading unused columns, specify data type sizes etc. 

I believe there are more nuanced ways to optimize handling the data with Pandas and there other data processing packages like Dask which may be able to do the same job. However with PySpark, you would setup the summarization in concise manner and it will get it done - just tell it declaratively `SELECT SUM(c) GROUP BY a, b` or its equivalent `df.groupBy('a', 'b').agg({'c': 'sum'})` - it gets you the result. PySpark is better as pandas simply can't complete execution due to memory limitations or without additional setups.

With PySpark all the intermediate steps ('column concatenation' as required for Pandas) become optional, freeing up an analyst's time to be invested in productive and visible work. I believe Kaggle competition participants can benefit from having the PySpark package available as it could free up valuable time that would otherwise be spent in setting up the intermediate preparatory steps.

A simple contrived example demonstrating the 'ease-of-use-case' with PySpark and failure when carried on with Pandas is available at gist [https://gist.github.com/vaidyasm/779da72dbbf67da69ee49ee350b10ab6](https://gist.github.com/vaidyasm/779da72dbbf67da69ee49ee350b10ab6). Group-by aggregate summarizations are fairly simple and common ones. Due to Panda's limitations, data frame created in cell 9 couldn't be summarized with the aggregation code snippet in its simplest form in cell 17. Alternative approaches using Pandas and PySpark are shown in cells 18 and 28 respectively. The simplicity of the PySpark version (cell 28) far outshines the efforts required to build the workarounds required for the Pandas version (cell 18).

Additionally, PySpark's builtin data partitioning is expected to better manage the ETL computation load when working with large data sets. This feature takes the burden of managing chunking of large dataset, moving chunks of data in and out of memory before and after processing, which is a huge weight off of the shoulders. With its managed 'persistence to disk' feature, working with large datasets becomes effortless to the users.

Not to mention PySpark's SQL capabilities provide a mechanism for writing declarative specification of your data transformations.

So in short the reason behind having PySpark package available, even though PySpark's scalability may get limited in Kernel environment, revolves around enabling a user to perform data analysis effectively by (not limited to):
* its declarative syntax makes data transformations concise and productive; 
* its managed data partitioning and managed data persistence makes working with large datasets easier;
* multi-column or multi-index grouping and aggregations are possible without additional pre and post processing (example provided in gist)

My comparison here doesn't fully cover all the features and capabilities of PySpark, or Pandas frameworks. Each framework has its own strengths and has its own purpose. I also acknowledge that people have varied interest in keeping track of the level of details of their data transformation pipeline. I personally like to describe what transformations are required and let the frameworks manage memory, scheduling, resources internally. PySpark checks a lot of boxes in this area.

**Comment by Philmod** [comment]
Hey @vaidyasm,

After discussing with some colleagues, we have decided to hold off adding such a huge package to our base image.

In the meantime, you could install it in your notebook `!pip install pyspark` (after enabling internet). Or some colleague advise to use Dask which is already installed.

We may reconsider our decision in the future if a critical mass of users request it.

Thanks for understanding,
Philippe
