### ISSUE TITLE
Unpin Pandas

### ISSUE THREAD

**Issue by dansbecker** [Kaggle/docker-python#723]
It appears from https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L27-L28 that pandas is pinned to an old (pre 1.x) version to support qgrid and tsfresh.

Qgrid removed the requirement to run old versions of pandas with this commit: https://github.com/quantopian/qgrid/commit/abb4eb2d05307968bcd40c96b2214d5a4e9dd5a9

and tsfresh with this one:
https://github.com/blue-yonder/tsfresh/commit/0ef9123d68e3544ef0217caf83f63f93ad837a61

Perhaps I'm mis-reading those commits and these packages will break somewhere in use if the docker image is upgraded to 1.0.

But even if that's the case, updating pandas seems preferable to supporting these two libraries which I assume are used ~1% as much as pandas. If qgrid development stops (which I wouldn't rule out) will the docker image keep 0.25.x pandas indefinitely?

**Comment by djherbis** [comment]
Hey Dan :)

I'll check in with whomever pinned it and see if we're good to unpin in the next release. Thanks!

**Comment by dansbecker** [comment]
Thanks Dustin

I thought it would be fun to submit something to a Kaggle repo and see who
I know that responded, and it exceeded my expectations :)

**Comment by djherbis** [comment]
I double checked the bug and those do seem to be the only reason for pinning that package. I'm planning to do a release this week once some other content gets in, so I'll make sure we do this too.

Great to hear from you :)

**Comment by djherbis** [comment]
This should go out in the next image release in a week.

**Comment by dansbecker** [comment]
Hurray!

Thanks.

Stay safe over there.
