### ISSUE TITLE
Update gpu docker

### ISSUE THREAD

**Issue by leigh-plt** [Kaggle/docker-python#728]
Please move to more new docker base image:
From nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 
To nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
There are many packets not maintained in ubuntu 16.04

**Comment by rosbo** [comment]
Hi,

`nvidia/cuda` is actually not our base image. We only copy apt sources from the image using a Docker feature called multi-stage builds:
https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages

The base image of our GPU image is the Kaggle CPU image. The Kaggle CPU base image is `continuumio/anaconda3:2019.03`. 

Our plan is to upgrade the `continuumio/anaconda3` base image once they release the `2020.X` version.

Thank you

**Comment by leigh-plt** [comment]
But here https://github.com/Kaggle/docker-python/blob/master/gpu.Dockerfile
I see FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 AS nvidia
so i decided its base

**Comment by leigh-plt** [comment]
New release 2020.02 https://hub.docker.com/r/continuumio/anaconda3/tags
