### ISSUE TITLE
Add pretrained model weights for Keras

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#73]
Keras has a ```keras.applications``` module with pretrained models and automatically downloads their weights. Since the Kaggle Kernels have no external internet access, these cannot be downloaded. It would however work to add these weights to the docker-image so they were always available (since keras first checks a local cache before downloading, https://github.com/fchollet/keras/blob/master/keras/applications/vgg16.py#L162) https://github.com/fchollet/keras/blob/master/keras/utils/data_utils.py#L117). Particularly as a number of the tasks from the YouTube challenge to the Cervical Cancer contest would benefit from using pretrained models to create feature vectors

**Comment by kmader** [comment]
![image](https://cloud.githubusercontent.com/assets/116120/25169438/5aff6bcc-24e7-11e7-83c8-131c55137f4a.png)

**Comment by nerdcha** [comment]
I had a quick go at [caching](https://github.com/Kaggle/docker-python/commit/55e1a165838edc5b4c513296335852bcf504791c) them earlier, but it clearly hasn't stuck. I'll see what I can do.

**Comment by ekkus93** [comment]
I uploaded the model files as a data set here:
https://www.kaggle.com/ekkus93/keras-models

Here's an example how you can use it:
https://www.kaggle.com/ekkus93/keras-models-test-v2

**Comment by nerdcha** [comment]
Sorry for not getting to this sooner, but I think ekkus93 has the right idea. Now that we support mixing and matching data sources, it makes much more sense to have model weights as Kaggle datasets.

**Comment by fazzolini** [comment]
Is it possible to add torrent download to Kaggle for users from countries with bad internet access or censorship? Starting to download weights file where it can be interrupted at any moment without possibility of resuming can be a huge problem in many less developed countries...

**Comment by nerdcha** [comment]
@fazzolini You raise a great point. But if you use the solution mentioned above, then no downloads are necessary. See https://www.kaggle.com/gaborfodor/use-pretrained-keras-models-lb-0-3 for another example.

**Comment by R1j1t** [comment]
For those who wanted to use other models except VGG16 or VGG19 can use the following dataset,
https://www.kaggle.com/gaborfodor/keras-pretrained-models
Thought I should add it as an extension.
