### ISSUE TITLE
Request documentation - list of packages by category

### ISSUE THREAD

**Issue by sdfoley** [Kaggle/docker-python#75]
Hello and thanks for the great docker image.

It would be very useful if you can provide a separate list of all programs in the image broken down by category. For example:

- neural network 
- visualization
- out-of-core learning
- natural language processing
- computer vision
- computational geometry
- etc

**Comment by nerdcha** [comment]
This is a nice idea, thanks! Currently the best way to do that is browse the Dockerfile, but we'll keep this in mind for future development.
