### ISSUE TITLE
[MongoDB] ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by borisalmonacid** [Kaggle/docker-python#766]
Simple test:
```
import json
import io
import pymongo
from pymongo import MongoClient

#client = MongoClient('mongodb://localhost:27017/')
#client = MongoClient('mongodb://localhost:27017/', connect=False)
client = MongoClient('localhost', 27017)

print(client)
dbnames = client.list_database_names()
print(dbnames)
```

Error:
`ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused`

Error Reproduction:
https://www.kaggle.com/logachevpa/trip-routes-visualisation-on-map-by-time
https://www.kaggle.com/apjansing/preliminary-taxi-data-processing-using-mongodb

**Comment by Philmod** [comment]
Did you install a MongoDB instance in your notebook? In this snippet, I only see client code to reach a local database, not a server setup.

**Comment by borisalmonacid** [comment]
The error is from a kaggle Notebook: https://www.kaggle.com/apjansing/preliminary-taxi-data-processing-using-mongodb

![image](https://user-images.githubusercontent.com/28852633/80134111-43e0f580-856c-11ea-99fe-87e6dd753fb5.png)

![image](https://user-images.githubusercontent.com/28852633/80134199-64a94b00-856c-11ea-812b-c1656198e442.png)

**Comment by Philmod** [comment]
Right. Where do you start the MongoDB server? Could you share that code too?

**Comment by Philmod** [comment]
[This notebook](https://www.kaggle.com/apjansing/preliminary-taxi-data-processing-using-mongodb) you referenced have the same error because there is no local MongoDB server running.

Maybe they ran that code on their own computer where they have a MongoDB server.

**Comment by borisalmonacid** [comment]
Thank you very much for the clarification, now everything makes sense to me.

**Comment by l0ric** [comment]
lol

**Comment by g3holliday** [comment]
I have the same error with this code:

`
import sys
 import random
 import pymongo
 from pymongo import MongoClient

def delDB():
    client = MongoClient('localhost', 27017)
    db = client.words_database

    client.drop_database(db)

    self._ensure_opened()

if__name__=="main":
    delDB()
`
Can you tell me how to fix it? 

Thanks, 
g3holliday
