### ISSUE TITLE
add hdbscan

### ISSUE THREAD

**Issue by sp1thas** [Kaggle/docker-python#770]
Would you consider adding [hdbscan](https://github.com/scikit-learn-contrib/hdbscan) to your image?

`hdbscan` is one of the most popular python modules for clustering and specifically for hierarchical clustring.

**Comment by Philmod** [comment]
Hey, have you considered installing the package on your notebook? https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by sp1thas** [comment]
Hey @Philmod sorry for my late response. In my case I installed `hdbscan` manually. I know that docker image can not have every python module but `hdbscan` is very popular.

**Comment by kurianbenoy** [comment]
@Philmod what about competitons without internet acess?

**Comment by Philmod** [comment]
@kurianbenoy That would be a good reason to install the package on the image. Feel free to submit a PR with a unit test.
