### ISSUE TITLE
`docker-python/tensorflow-whl/build` failed to build a wheel

### ISSUE THREAD

**Issue by mikleg** [Kaggle/docker-python#774]
ERROR: /usr/local/src/tensorflow/tensorflow/core/kernels/BUILD:3942:1: C++ compilation of rule '//tensorflow/core/kernels:reduction_ops' failed (Exit 1)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:105:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/kernels/reduction_ops_common.h:27,
                 from tensorflow/core/kernels/reduction_ops_sum.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Functor = Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tiling>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >; bool Vectorizable = true; Eigen::internal::TiledEvaluation Tiling = (Eigen::internal::TiledEvaluation)0u]::<lambda(Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, (Eigen::internal::TiledEvaluation)0u>::StorageIndex, Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::IndexList<Eigen::type2index<0l> >, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, (Eigen::internal::TiledEvaluation)0u>::StorageIndex)>; _ArgTypes = {long int, long int}]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:870:9: internal compiler error: in emit_move_insn, at expr.c:3547
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
         ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4221.898s, Critical Path: 158.22s
INFO: 4513 processes: 4513 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
The command '/bin/sh -c cd /usr/local/src/tensorflow &&     cat /dev/null | ./configure &&     bazel build --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_cpu &&     bazel clean' returned a non-zero code: 1

Commands sequence:
git clone https://github.com/Kaggle/docker-python.git
cd docker-python/tensorflow-whl/
./build

System: Ubuntu 16.04 on Vmware ESXI 6.5 12Gb (I tried 10..16) RAM CPU Xeon W3550 (no AVX) Geforce GTX 1070 with installed Nvidia Drivers, Docker, Docker composer, nvidia-docker2. 
Previously I successfully used it for a compilation of Tensorflow 1.15 whl from sources using code from tensorflow/tensorflow and 3rd party Dockerfile with my adjustments. Also, that image runs on this machine without problems.
Then I revert a snapshot and tried this repo because I need 2.1 with similar to Kaggle environment. I tried to fix this issue by myself but until now I was unsuccessful. I found that probably the issue caused by the version of GCC with a bug as mentioned here: https://github.com/tensorflow/tensorflow/issues/25323.
Please help! Any ideas about how to avoid/fix this issue will be greatly appreciated.
Mikle

**Comment by rosbo** [comment]
We moved away from using custom wheels and are now using the official `tensorflow` and `tensorflow-gpu` wheels from `pip`.
