### ISSUE TITLE
[BUG] Exception: Your CUDA environment is invalid.

### ISSUE THREAD

**Issue by aerdem4** [Kaggle/docker-python#791]
Recently I got this error while trying to install cupy on a Kaggle GPU Kernel:

```
Collecting cupy
  Downloading cupy-7.4.0.tar.gz (3.7 MB)
     |████████████████████████████████| 3.7 MB 3.4 MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jzxcfeco/cupy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jzxcfeco/cupy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jzxcfeco/cupy/pip-egg-info
         cwd: /tmp/pip-install-jzxcfeco/cupy/
    Complete output (48 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}
    
    -------- Configuring Module: cuda --------
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /opt/conda/compiler_compat/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so: file not recognized: file truncated
    collect2: error: ld returned 1 exit status
    Cannot build a stub file.
    Original error: command 'g++' failed with exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jzxcfeco/cupy/setup.py", line 129, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-jzxcfeco/cupy/cupy_setup_build.py", line 744, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-jzxcfeco/cupy/cupy_setup_build.py", line 492, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/usr/local/cuda/include']
      Library directories: ['/usr/local/cuda/lib64']
      nvcc command       : ['/usr/local/cuda/bin/nvcc']
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
      ROCM_HOME       : (none)
    
    Modules:
      cuda      : No
        -> Cannot link libraries: ['cublas', 'cuda', 'cudart', 'cufft', 'curand', 'cusparse', 'nvrtc']
        -> Check your LDFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rosbo** [comment]
Hi @aerdem4,

May I ask why you are trying to install cupy?

`cupy` comes pre-installed on our GPU kernels: https://admin.kaggle.com/rosebv/cupy-cuda?scriptVersionId=33015500

Thank you

**Comment by aerdem4** [comment]
@rosbo thanks for your quick response. We install rapids using a workaround. (First cell of this notebook: https://www.kaggle.com/aerdem4/rapids-svm-on-trends-neuroimaging). With the new image, it stopped working and returned an error stating that cupy is not installed when cuml is imported. Our hacky way of installing Rapids may be the reason but I suspected maybe something is wrong with the new image after trying to install cupy via pip.

**Comment by rosbo** [comment]
```
import sys
!cp ../input/rapids/rapids.0.13.0 /opt/conda/envs/rapids.tar.gz
!cd /opt/conda/envs/ && tar -xzvf rapids.tar.gz > /dev/null
sys.path = ["/opt/conda/envs/rapids/lib/python3.6/site-packages"] + sys.path
sys.path = ["/opt/conda/envs/rapids/lib/python3.6"] + sys.path
sys.path = ["/opt/conda/envs/rapids/lib"] + sys.path
!cp /opt/conda/envs/rapids/lib/libxgboost.so /opt/conda/lib/
```

The new image is now using Python 3.7 you will need to update the `sys.path` and use a Rapid wheel built for Python 3.7.

I hope that helps.

**Comment by rosbo** [comment]
About pre-installing Rapids packages, I tried in December 2019 but hit that issue: https://github.com/Kaggle/docker-python/issues/594#issuecomment-563498314

Let me check whether this dependency conflict issue has been fixed.

**Comment by aerdem4** [comment]
As far as I heard from my colleagues, pandas dependency issue shouldn't exist anymore in rapids 0.13. Please let us know if it still exists. Thank you very much.

**Comment by rosbo** [comment]
That's a great news, I will try to tackle this next week :)

**Comment by aerdem4** [comment]
Hi @rosbo , could you have a look into it?

**Comment by rosbo** [comment]
I am having weird conflict issue with conda, hopefully I can get them resolved soon:

```
# 10.1.243 does match all constraint....
Package cudatoolkit conflicts for:
cuml=0.13.0 -> cupy[version='>=7,<8.0.0a0'] -> cudatoolkit[version='10.0|10.0.*|10.2|10.2.*|9.2|9.2.*|10.1|10.1.*']
cudatoolkit=10.1.243
cuml=0.13.0 -> cudatoolkit[version='>=10.0.130,<10.1.0a0|>=10.1.243,<10.2.0a0|>=10.2.89,<10.3.0a0']

# I would expect conda to consider 0.13 equivalent to 0.13.0
Package cudf conflicts for:
cudf=0.13.0
cuml=0.13.0 -> dask-cudf=0.13 -> cudf=0.13.0
cuml=0.13.0 -> cudf=0.13
```

Stay tuned.

**Comment by kkraus14** [comment]
@rosbo Hey I'm one of the cuDF / RAPIDS maintainers. Any chance you could share the full output from your conda command to help see where the conflict is coming from?

**Comment by rosbo** [comment]
@kkraus14 Thanks for jumping in :)

This is actually the full output when I run the following command:

`conda install -y -c rapidsai cudf=0.13 cuml=0.13 cudatoolkit=10.1.243`

**Comment by kkraus14** [comment]
Could you try `conda install -y -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.13 cuml=0.13 cudatoolkit=10.1.243`?

I'm guessing the lack of the `nvidia` / `conda-forge` channel can cause issues here. `defaults` typically isn't up to date enough for the latest RAPIDS release.

**Comment by rosbo** [comment]
I kicked off a build with the `conda install -y -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.13 cuml=0.13 cudatoolkit=10.1.243` earlier today. It still hit conflicts and has been making slow progress "examining conflict" for ~6 hours now... I will wait until this ends to see if it surfaces any conflicts we can easily resolve.

For background, the way our GPU image is:

1. Base image is the CPU image (which includes ~ 700 packages).
2. Install NVIDIA stuff
3. Reinstall key packages that needs it to support GPU: TensorFlow, Pytorch, mxnet, LightGBM, etc.

Building the CPU image takes ~ 1h.
Building the GPU image takes an extra ~10 minutes.

**Comment by kkraus14** [comment]
> 1. Base image is the CPU image (which includes ~ 700 packages).

Do you happen to know if these packages are installed from the `defaults` or `conda-forge` channel? If from defaults this explains why the solve time is crazy and may be able to be somewhat mitigated by changing the order of `conda-forge` and `defaults`.

**Comment by rosbo** [comment]
Most of them are installed from `pip`: https://github.com/Kaggle/docker-python/blob/master/Dockerfile

**Comment by rosbo** [comment]
FYI, after 24h, I cancelled the process examining conflicts which was at only 7% (still making progress).

**Comment by kkraus14** [comment]
I'm guessing the issue is here: https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L39-L42

By default conda only has the `defaults` channel as the searchable channels. When you add a channel with `-c channel_name` it basically adds that with higher priority than defaults into the current search.

It looks like you're first installing a few things from conda-forge which I'm guessing mostly resolve their dependency tree using conda-forge packages. Afterwards, you install pytorch effectively using `-c pytorch -c defaults`, so conda-forge isn't available and it ends up downgrading a bunch of packages from conda-forge --> defaults. Then when you go to install rapids, it ends up needing to scan through a large area of packages in the current environment that are currently a mix of `defaults` and `conda-forge` which turns it into a combinatorics explosion.

If possible, I'd suggest reworking the conda commands to all use the same consistent set of channels, i.e. `conda install -c pytorch -c rapidsai -c nvidia -c conda-forge -c defaults` or better yet use a `.condarc` file so you can just use `conda install` and you're guaranteed a more consistent experience in building the environment and solving for packages.

**Comment by rosbo** [comment]
Using consistent channels throughout is a great suggestion. I opened a specific PR for this: #820.

Next, I will try adding rapidsai.

**Comment by rosbo** [comment]
Unfortunately, there is still conflicts and hangs forever at examining conflict.

Looking manually at the `info/index.json` for the `cuml-0.14.0-cuda10.1_py37_0` conda package, here are the deps:

```
"cudatoolkit >=10.1.243,<10.2.0a0",
"cudf 0.14.*",
"cupy >=7,<8.0.0a0",
"dask >=2.12.0",
"dask-cudf 0.14.*",
"distributed >=2.12.0",
"joblib >=0.11",
"libcuml 0.14.0.*",
"libcumlprims 0.14.*",
"nccl >=2.5",
"python >=3.7,<3.8.0a0",
"python_abi 3.7.* *_cp37m",
"ucx-py 0.14.*"
```

Satisfied dependencies:
cudatoolkit, dask, python, python_abi

Need upgrade:
distributed (2.10.0)

New deps:
cudf, dask-cudf, joblib, cupy, libcuml, libcumlprims, nccl, ucx-py

I will try installing some of these deps individually and hope that conflicts finding will work this way.

**Comment by rosbo** [comment]
I will post any additional updates on adding Rapidsai to #594

**Comment by LeoGautheron** [comment]
I have the same error when compiling a source code inside a Kaggle notebook:
```
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
```
The error message is correct as the file libcuda.so seems broken (it as 0 byte):
```
!ls -la /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda*
lrwxrwxrwx 1 root root 12 Jul  8 13:47 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root 17 Jul  8 13:47 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.418.67
-rwxr-xr-x 1 root root  0 Jul  8 13:47 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcuda.so.418.67
```

However it seems there is also another file libcuda.so which is not broken somewhere else:
```
!ls -la /usr/local/nvidia/lib64/libcuda*
lrwxrwxrwx 1 root root       12 Jul 23 20:39 /usr/local/nvidia/lib64/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       17 Jul 23 20:39 /usr/local/nvidia/lib64/libcuda.so.1 -> libcuda.so.418.67
-rwxr-xr-x 1 root root 16142096 Jul 23 20:39 /usr/local/nvidia/lib64/libcuda.so.418.67
```

Can someone fix the broken file ?
Thanks
