### ISSUE TITLE
package requested: afinn

### ISSUE THREAD

**Issue by RMitra90** [Kaggle/docker-python#796]
I need this package for the 'Tweet Sentiment Extraction' competition. The competition does not allow the internet for kernel submission and hence my kernel is not working.

It will be great if I could import this package.

pip install afinn

**Comment by rosbo** [comment]
Hi @RMitra90,

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

Please reopen this issue once this package reaches that threshold.

Thanks for your understanding.
