### ISSUE TITLE
GDAL library for processing map data...

### ISSUE THREAD

**Issue by happycube** [Kaggle/docker-python#80]
I'm looking at OpenStreetMap data for the Sberbank competition and saw this article http://andrewgaidus.com/Convert_OSM_Data/ that led me to GDAL (which has 'ogr' to read geodata files including OSM format) - https://pypi.python.org/pypi/GDAL

edit:  It does seem to require 'gdal-bin' and 'libgdal-dev' in ubuntu, then running pip with "CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal" environment variabls so it might pull in too much to be practical...

**Comment by nerdcha** [comment]
Getting GDAL working in here would be great. We explored this for PR https://github.com/Kaggle/docker-python/pull/74 recently, but ended up admitting defeat: the `conda` version has weird dependency issues, and installing GDAL manually leads you down a rabbit hole.

I'll revisit this soon, though. It would be nice to get it working.
