### ISSUE TITLE
how to choose python version?

### ISSUE THREAD

**Issue by flydragon2018** [Kaggle/docker-python#811]
how to use python3.6 instead of 3.7?

**Comment by rosbo** [comment]
Hi @flydragon2018,

At this point, we are only supporting python 3.7.

You can use one of the older image with python 3.6 if you want. The latest image with python 3.6 was released on March 30th 2020. Here is a link to this image: https://pantheon.corp.google.com/gcr/images/kaggle-images/GLOBAL/python@sha256:3955da6976c9d10a271fb822aaf0170c57ca7c38d880549619669a735e12df2e/details?tab=info

Thank you.
