### ISSUE TITLE
packet sklearn_crfsuite is needed

### ISSUE THREAD

**Issue by zhuzhanshi** [Kaggle/docker-python#818]
I want to submit my output by kaggle kernel.
I know I can intall it by '! pip install sklearn_crfsuite' with internet on.
But after that, 'submit to competition' is banned.
If I set the internet off, there is no sklearn_crfsuite in the environment.

Thus, I need the packet 'sklearn_crfsuite' in the environment.
Also, if you have other way to solve this problem, share with please.

**Comment by rosbo** [comment]
Hi @zhuzhanshi,

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only pre-installing the popular packages into it (1000+ stars on GitHub).

Please reopen this issue once this package reaches that threshold.

Thanks for your understanding.
