### ISSUE TITLE
Can't build Docker image for kaggle

### ISSUE THREAD

**Issue by Yuki-mm** [Kaggle/docker-python#834]
Hi! I'm docker beginer. Thanks your kindness. 

My env is 
OS:windows10
CLI:gitbash(MINGW64),
GPU:NVIDIA GeForce RTX 2080 SUPER

I tried to build docker-python image from [gpu.Dockerfile](https://github.com/Kaggle/docker-python/blob/master/gpu.Dockerfile), but I can't.

I tiped this command.
`$ ./build --gpu`

and outout it.

```
Processing triggers for libc-bin (2.27-3ubuntu1) ...
/bin/sh: 1: /tmp/clean-layer.sh: not found
The command 
'/bin/sh -c apt-get update && apt-get install -y --no-install-recommends       
cuda-cupti-$CUDA_PKG_VERSION       
cuda-cudart-$CUDA_PKG_VERSION       
cuda-cudart-dev-$CUDA_PKG_VERSION       
cuda-libraries-$CUDA_PKG_VERSION       
cuda-libraries-dev-$CUDA_PKG_VERSION       
cuda-nvml-dev-$CUDA_PKG_VERSION       
cuda-minimal-build-$CUDA_PKG_VERSION       
cuda-command-line-tools-$CUDA_PKG_VERSION       
libcudnn7=7.6.5.32-1+cuda$CUDA_MAJOR_VERSION.$CUDA_MINOR_VERSION       
libcudnn7-dev=7.6.5.32-1+cuda$CUDA_MAJOR_VERSION.$CUDA_MINOR_VERSION      
libnccl2=2.5.6-1+cuda$CUDA_MAJOR_VERSION.$CUDA_MINOR_VERSION       
libnccl-dev=2.5.6-1+cuda$CUDA_MAJOR_VERSION.$CUDA_MINOR_VERSION && ln -s /usr/local/cuda-$CUDA_MAJOR_VERSION.$CUDA_MINOR_VERSION /usr/local/cuda && ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1 && /tmp/clean-layer.sh' 
returned a non-zero code: 127
```

I wanna use gpu-docker env for kaggle, but I have no idea.

What is needed to builed docker container about gpu(cuda), docker, anything else?

I hope your kindly help. Thank you.

**Comment by rosbo** [comment]
Hi @Yuki-mm,

To build the GPU image, you only need docker. You don't even need a GPU to build the image, we are using stubs for CUDA. However, to run the image, you will need a GPU.

I see you are using Windows as the host for building the image. We recommend using a linux or os x machine to build it.

I am a bit surprise with the error `/tmp/clean-layer.sh: not found`. This file is added [here](https://github.com/Kaggle/docker-python/blob/master/gpu.Dockerfile#L7). Did you update any files in the repo prior to running `./build --gpu`?

You can also use one of our pre-built GPU docker image available here: https://pantheon.corp.google.com/gcr/images/kaggle-gpu-images/GLOBAL/python

The image tagged with `latest` is the one currently in use on Kaggle notebooks.

Thank you
