### ISSUE TITLE
Pleases change notebook and tornado version

### ISSUE THREAD

**Issue by imrankhan441** [Kaggle/docker-python#845]
For TensorFlow, Federated Learning needs notebook version 5.7.8 and tornado version 4.4.3 Because on the new version of notebook and tornado TensorFlow Federated freeze the kernel. please change these two version.

Thank you.

**Comment by rosbo** [comment]
Hi @imrankhan441,

We've upgraded to `tornado` 6.x in #989. A new image with these changes should be released to Kaggle notebooks in less than two weeks.

Thank you
