### ISSUE TITLE
PyTorch XLA for TPU kernels

### ISSUE THREAD

**Issue by tmabraham** [Kaggle/docker-python#846]
I don't know if this is the right repository for requesting changes to the TPU Kaggle Kernel VM. If not, please let me know which is the correct GitHub repository or Kaggle forum for this.

When we use PyTorch XLA in Kaggle Kernels, we always require the following installation code:

```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version nightly --apt-packages libomp5 libopenblas-dev
```

Essentially, this code runs [this program](https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py). It obtains the appropriate wheels, uninstalls torch and torchvision, and installs torch_xla and its corresponding versions of torch and torchvision. It also installs two Linux packages, libomp5 and libopenblas-dev.

Can the Linux packages and PyTorch XLA package be pre-installed in the TPU Kaggle Kernel? This process takes two minutes or so, and it's slightly annoying to keep waiting for this during interactive mode. So it would be really helpful if it is pre-installed.

**Comment by rosbo** [comment]
Hi @tmabraham,

The PyTorch XLA is still in rapid development and we want users to get the latest XLA code when running TPU.

Once XLA stabilizes (probably in a few months), we are planning on including it in our base image and this step won't be necessary.

Stay tuned.

Thank you

**Comment by tmabraham** [comment]
@rosbo My understanding is that there is already a PyTorch XLA release over [here](https://github.com/pytorch/xla/releases/tag/v1.5.0). Can at least this be included for the timebeing?  I think this release has all the main functionality for TPU usage.

**Comment by rosbo** [comment]
Adding @ifigotin who's working on the TPU integration.

**Comment by ifigotin** [comment]
> What's the latest decision about including PyTorch XLA in our image? From what I remembered, this was still a few months out.

The PyTorch/XLA support is still experimental, and my understanding is that the packages are update daily at the moment. At some point in the future (I don't know the date), PyTorch/XLA team will reach GA status, at which point the packages should stabilize. 

It is indeed annoying to run the script all the time now. My understanding is that in the future the solution would be more subtle and fast, and we could hopefully pre-install the required packages.

**Comment by tmabraham** [comment]
@ifigotin My understanding though is that there is already a release with most of the major features (unless there is a plan to change a major part of the interface). I am not talking about the nightly version, but rather the v1.5 release from a couple months ago. However, I understand if PyTorch XLA team is not ready for it to be available as part of the Kaggle image, and I guess I will just have to wait...

**Comment by ifigotin** [comment]
@jysohn23 may have more context on this, however, my understanding is that the releases are not GA yet, so may possibly break, and have instabilities. Additionally, the current installation process (via the script provided by the team) will also change. We are planning to revisit integrating everything into Kaggle image after the GA.
