### ISSUE TITLE
Support to install graph_tool 

### ISSUE THREAD

**Issue by jpzhangvincent** [Kaggle/docker-python#85]
I'd like to use "from skmultilearn.cluster import IGraphLabelCooccurenceClusterer"  from the scikit-multilearn package. And it requires the graph_tool dependency, which needs to re-configure the dockerfile. 
Thanks!

graph_tool :
https://git.skewed.de/count0/graph-tool/wikis/installation-instructions

**Comment by nerdcha** [comment]
Hmm, that looks interesting but the installation is fairly complex. If you can get the installation working in this docker image, please submit a Pull Request, we'd love to have it!
