### ISSUE TITLE
upgrade hypertools to 0.3.0

### ISSUE THREAD

**Issue by andrewheusser** [Kaggle/docker-python#86]
Hi - we just added a bunch of new stuff to our software (no API changes).  Could you pull the latest version of hypertools from pip? Thank you!

**Comment by andrewheusser** [comment]
just circling back on this, thanks!

**Comment by nerdcha** [comment]
Sorry to be slow in getting back to you! We update our python image every week or two, so 0.3.0 has been deployed for a while. Let us know if you need anything else…

**Comment by andrewheusser** [comment]
no worries, thanks @nerdcha!
