### ISSUE TITLE
Pymongo on gitlab: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by bulkerke** [Kaggle/docker-python#863]
I have some troubles with connecting to mongodb when pushing to gitlab.

So I tried the following:

`test-ci.ini`:

    [MONGODB]
    url = mongodb://localhost:27017/
    user = root
    password = root
    db_name = database
    port = 27017

docker-compose.yml:

    version: "3.2"
    services:
      app:
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
          args:
            requirements: requirements.txt
            environement: development
        volumes:
          - ./:/project
        depends_on:
          - db
          - mongodb
    
      db:
        restart: always
        image: postgres
        hostname: db
    
      mongodb:
        restart: always
        image: mongo
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

When I run this I get following error:

    pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

Then I tried this issue
https://stackoverflow.com/questions/61153087/mongodb-gitlab-ci-docker-connection-refused

I got following settings:

`test-ci.ini`:

    [MONGODB]
    url = mongodb://mongo:27017/
    user = root
    password = root
    db_name= database
    port = 27017

which gives me this error:

    pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name or service not known

**Comment by Philmod** [comment]
@bulkerke Could you explain a bit more how this is linked to Kaggle?

**Comment by bulkerke** [comment]
oops this is probably the wrong location?

**Comment by Philmod** [comment]
If you are looking for help with Gitlab, yes it's the wrong repo :-)

Feel free to reopen otherwise.
