### ISSUE TITLE
Adding pysox

### ISSUE THREAD

**Issue by placardo** [Kaggle/docker-python#864]
Would you consider adding [pysox](https://github.com/rabitt/pysox) to your image? It's very fast and efficient and useful for competitions without internet access

**Comment by jplotts** [comment]
Hi @placardo ,

In an effort to limit the size of our Docker Python image and ease the maintenance burden, we are only preinstalling very popular packages into it (1000+ stars on GitHub).

Please reopen this issue once this package reaches that threshold.

Thanks for your understanding.
