### ISSUE TITLE
Upgrade to pytorch version 1.6.0

### ISSUE THREAD

**Issue by vijaypal89** [Kaggle/docker-python#871]
https://github.com/Kaggle/docker-python/blob/0c998f32bb373752e9c52f0da6e91b5d8e80fcad/Dockerfile#L50

Pytorch has stable version of 1.6.0 - https://github.com/pytorch/pytorch/releases

**Comment by paultimothymooney** [comment]
There was also a recent product feedback forum post requesting to upgrade to PyTorch 1.6: https://www.kaggle.com/product-feedback/180814

**Comment by Philmod** [comment]
The goal is to upgrade to 1.6 as soon as most packages depending on PyTorch support the new version. 
https://github.com/Kaggle/docker-python/pull/860

**Comment by rosbo** [comment]
Fixed by #860. The new image will be available in Kaggle Kernels early next week. Thank you.
