### ISSUE TITLE
fastai version upgrade needed

### ISSUE THREAD

**Issue by nitinvinayak** [Kaggle/docker-python#874]
fastai version is too old for working. There has been a release of new fastai library which is better and faster. pip install fastai --upgrade does not provide updated library inside the notebook when fastai is imported. 

fastai==2.0 needed

**Comment by paultimothymooney** [comment]
There was a recent request in the product feedback forum to upgrade to fastai 2.0: https://www.kaggle.com/product-feedback/180645

**Comment by Philmod** [comment]
Hi @nitinvinayak, 

The 2.x version released on August 21st uses the new Pytorch 1.6. Unfortunately, we cannot upgrade to Pytorch 1.6 until most packages depending on pytorch support 1.6.

https://github.com/Kaggle/docker-python/issues/871

**Comment by rosbo** [comment]
Fixed by #860. The new image will be available in Kaggle Kernels early next week. Thank you.
