### ISSUE TITLE
install of Jupyter-Beeper with pip

### ISSUE THREAD

**Issue by tomoki-shibata** [Kaggle/docker-python#879]
I want to use the library of Jupyter-Beeper(https://pypi.org/project/Jupyter-Beeper/) for notifying of  the end of processing.
Please add it to docker-python environment.

The code for Install is below. 
"pip install Jupyter-Beeper"

Thanx.

**Comment by Philmod** [comment]
Hey @tomoki-shibata ,

This package doesn't meet our requirements to install it in our base image.
Feel free to install it in your notebooks: https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Best,
Philippe
