### ISSUE TITLE
when i use get_transform() function using fastai then generating some error can anyone help me regards this?

### ISSUE THREAD

**Issue by radadiyamohit81** [Kaggle/docker-python#880]
![first](https://user-images.githubusercontent.com/30775542/94509490-fdd24100-0231-11eb-81f5-6088deb20619.PNG)

**Comment by Philmod** [comment]
Hi @radadiyamohit81 ,

You may have more luck to get help from other Kagglers on our forums: https://www.kaggle.com/discussion

I don't see the full code, but have you imported properly this method? Something like: `from fastai.vision import get_transforms`

Closing this bug as it's more a question about python/fastai.
Feel free to reopen if I'm mistaken.

Best,
Philippe
