### ISSUE TITLE
Use cuda 10.2 for GPU?

### ISSUE THREAD

**Issue by Jimexist** [Kaggle/docker-python#882]
In https://github.com/Kaggle/docker-python/commit/8de8bd0648676d80f33ac8f498234a398819f8e1#diff-fdb0991c83e40c667bdb702ba2d9a2e9 the version was upgraded to 10.1, but then if you `pip install pytorch` by default it'll install 10.2 version which renders the GPU unrecognized.

**Comment by rosbo** [comment]
Fixed in #886, the new image will be released to Kaggle notebooks early next week.
