### ISSUE TITLE
Upgrade to tornado 6?

### ISSUE THREAD

**Issue by dovahcrow** [Kaggle/docker-python#890]
Originally, we pinned to tornado 5.0.2 in this commit 72ed33d0 due to the incompatibility of jupyter with tornado 6 as mentioned in this issue https://github.com/jupyter/notebook/issues/4439. 

This bug seems already been fixed in the upstream. Can we relax the requirement now?

**Comment by djherbis** [comment]
We can certainly try it out, it'll take awhile before it gets released on Kaggle if it does work.

@dovahcrow Out of curiosity, what led you to noticing this / how are you using this image?

**Comment by djherbis** [comment]
Closed my PR trying this out because it seems our pinned jupyter version (5.5.0) still experiences this issue.

**Comment by dovahcrow** [comment]
> We can certainly try it out, it'll take awhile before it gets released on Kaggle if it does work.
> 
> @dovahcrow Out of curiosity, what led you to noticing this / how are you using this image?

Our library [`dataprep`](dataprep.ai) once had a higher version of `tornado`. Installing it on the [Kaggle Notebook](https://www.kaggle.com/notebooks/welcome) will break the notebook thus making our library not usable on Kaggle. As a workaround, we also pinned tornado in our library. 

However, `bokeh > 2.0` requires a higher version of `tornado`. Since `bokeh` is also a widely used dependency by other libraries, I'm worrying one day this pinned `tornado` will us impossible to resolve the dependencies. Moreover, I think this pinned tornado will also be an issue for other libraries.

**Comment by dovahcrow** [comment]
> Closed my PR trying this out because it seems our pinned jupyter version (5.5.0) still experiences this issue.

Yes, you are right. The fix is landed in jupyter 5.7.5 version.

**Comment by djherbis** [comment]
Yeah these are very fair concerns, I commented on #891 that we might be able to unpin jupyter without consequences, though it'll still take testing/verification.

May take some time before we're able to confirm the feasibility.

**Comment by rosbo** [comment]
Hi @dovahcrow,

We have upgraded to `tornado` 6.x in #989. A new image with these changes should be released to Kaggle notebooks in less than two weeks.

Thank you
