### ISSUE TITLE
Add skorch package

### ISSUE THREAD

**Issue by kqf** [Kaggle/docker-python#893]
Hi, could you evaluate the possibility of adding [skorch](https://github.com/skorch-dev/skorch) to the image. This package is quite popular and generic. The urge to install comes from kernel-only competitions that don't allow internet connection.

**Comment by rosbo** [comment]
Hi @kqf,

We will soon upgrade to torch 1.7 and skorch doesn't yet support this version.

I will install this package after we migrate to torch 1.7 and that this package supports it.

Thank you

**Comment by calderjo** [comment]
In an effort to limit the size of our Docker Python image and ease the maintenance burden, The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image.

Thank you for understanding!
