### ISSUE TITLE
Would like to have psycopg2 (Postgres connector)...

### ISSUE THREAD

**Issue by happycube** [Kaggle/docker-python#90]
I'm playing with SQL stuff for a competition and am manually loading that in now.  Installs with a clean "pip install psycopg2" - thanks!

**Comment by nerdcha** [comment]
Thanks for the suggestion! Is there an advantage to including it in this image, compared to building your own image using this one as a base?

**Comment by happycube** [comment]
Not really, thinking about it.  It also installs cleanly in pip in a notebook (when run as root) :)
