### ISSUE TITLE
Upgrade from CUDA 10.2 to 11.0 ?

### ISSUE THREAD

**Issue by lowener** [Kaggle/docker-python#908]
Is it possible to upgrade the notebook Cuda version to 11.0 ? This version is fixing bugs in svd:
https://github.com/cupy/cupy/issues/2351

Thanks

**Comment by rosbo** [comment]
Hi @lowener,

This is on our radar. We are waiting until all our GPU-enabled packages support cuda 11.

Thank you

**Comment by claverru** [comment]
Any updates on this?

**Comment by rosbo** [comment]
@claverru we are waiting on `mxnet` to release their GA version for CUDA 11.0: https://github.com/apache/incubator-mxnet/issues/18657

**Comment by toshi-k** [comment]
I think it's the time to install CUDA 11 (by removing mxnet at once and add it again after the update for CUDA11).
The number of users of RTX 30X0 GPUs / A6000 / A100 would be more than the users of mxnet in Kaggle.

**Comment by toshi-k** [comment]
@djherbis Basically, there are two ways of submission in Kaggle, CSV based competition, and code competition (2stage competition).

In code competition, all participants have to submit inference notebook through Kaggle Notebooks. RTX 30X0 users train the model on own machine (with CUDA11), and submit their model by Kaggle Notebooks (with CUDA10). The difference of CUDA version sometimes causes issues, which seems more crucial than the availability of mxnet.

**Comment by rosbo** [comment]
Hi @toshi-k,

The mxnet wheel for CUDA 11 was released last week. I will start working on upgrading our image to CUDA 11.

**Comment by toshi-k** [comment]
@rosbo That's good news ! I'm looking forward to the upgrade of GPU image.

**Comment by rosbo** [comment]
I upgraded CUDA to version 11.0 in #985.

We will release a new Docker image to Kaggle notebooks next week.
