### ISSUE TITLE
I can't use Gurobi package in python on Kaggle

### ISSUE THREAD

**Issue by Dana2021** [Kaggle/docker-python#910]
Hello, 

I am trying to import gurobi in kaggle but I am not able to do so. 
I am using:
from gurobipy import * 
but I am receiving an error that says the module doesn't exist

**Comment by rosbo** [comment]
Hi @Dana2021,

We don't pre-install every packages on Kaggle notebooks to keep the Docker image backing  the sessions at a reasonable size.

You can follow these steps to install the `gurobipy` package into your own Kaggle notebooks only: https://github.com/Kaggle/docker-python/wiki/Missing-Packages
