### ISSUE TITLE
Please integrate PaddlePaddle in the basic image

### ISSUE THREAD

**Issue by weiexcelpro** [Kaggle/docker-python#926]
Hi all,

I am using PaddlePaddle as my daily DL framework, instead of TF/PyTorch. 

PaddlePaddle is a deep learning framework that is very popular in East Asia. The latest version is 2.0RC1 and stable enough for everyone.

Could you consider making PaddlePaddle part of the base image, rather than requiring users to install it themselves every time?

Installation takes a lot of time, and not recommended in some competitions. 

Thanks,
Wei

**Comment by calderjo** [comment]
In an effort to limit the size of our Docker Python image and ease the maintenance burden, The docker image team is currently phasing out the 1k star requirements and not accepting new packages at this time. While we don't take user request for new packages, we still encourage users to report and send PRs for fixing issues seen in our image.

Thank you for understanding!
