### ISSUE TITLE
Add nb_black package

### ISSUE THREAD

**Issue by nickcorona** [Kaggle/docker-python#927]
https://pypi.org/project/nb-black/

It's a code formatter extension that works in notebooks.

**Comment by djherbis** [comment]
Seems like the parent project has sufficient stars https://github.com/psf/black, just brining it up with our internal product team  how this will work.

We actually do a lot of magic with our editor, which actually means adding nb_black to the docker image may not affect notebook extensions available in our editor at all. There are ways for Kaggle to add notebook extensions, but it's via another process than this repo.

**Comment by djherbis** [comment]
Looks like we're not going to be able to add this package at this time. Thanks for requesting it though!
