### ISSUE TITLE
add vaex

### ISSUE THREAD

**Issue by Chizuchizu** [Kaggle/docker-python#928]
https://github.com/vaexio/vaex

I would like to see the vaex library added.

It can produce higher performance than Pandas.

🙏

**Comment by Leeeooo19888** [comment]
> https://github.com/vaexio/vaex
> 
> I would like to see the vaex library added.
> 
> It can produce higher performance than Pandas.
> 
> 🙏

.. and now ???

**Comment by Chizuchizu** [comment]
There are no updates.

**Comment by Leeeooo19888** [comment]
[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

**Comment by rosbo** [comment]
Hi,

`vaex` requires pyarrow >= 3.0. Unfortunately, RapidsAI cuml/cudf packages only work with pyarrow 1.0

The good news is that rapidsai 21.08 (next release) will include support for `pyarrow` 4.0! I will make sure to add vaex once the new version of rapidsai is released.

Stay tuned.

**Comment by scottie34** [comment]
Any news ? `rapidsai 21.08` seems released
