### ISSUE TITLE
module Geohash do not work

### ISSUE THREAD

**Issue by pbeaune** [Kaggle/docker-python#95]
The module does not work whit python3 (issue -> https://github.com/vinsci/geohash/issues/4).

I also tried to install from code source and i have the same error.

However the following fix works : 
sed -i -- 's/geohash/.geohash/g' /opt/conda/lib/python3.6/site-packages/Geohash/__init__.py

**Comment by nerdcha** [comment]
Thanks for pointing that out! This patch will be deployed shortly.
