### ISSUE TITLE
add pydot/graphviz

### ISSUE THREAD

**Issue by ldmtwo** [Kaggle/docker-python#953]
I got an error with this code. Graphviz is pretty standard, so please add. Thanks.
`pip install pydot`
```

    from keras.utils.vis_utils import plot_model
    plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)
```

**Comment by ldmtwo** [comment]
Can you also add keras applications of create a wiki on pretrained models?

**Comment by rosbo** [comment]
@ldmtwo 

`pydot` is now included in the base Kaggle Python Docker notebook image.

About your 2nd question, we don't include pretrained models in our base image to limit its size.

Thank you
