### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'

### ISSUE THREAD

**Issue by meet-web** [Kaggle/docker-python#958]
#Conolutional Neural Networks (CNN)
from keras.layers import Flatten
from keras.layers import Convolution1D, GlobalMaxPooling1D
from keras.layers import Dropout
model = Sequential()
embedding_layer = Embedding(vocab_size,50,embeddings_initializer = Constant(embedding_matrix),input_length=20, trainable=False)
model.add(embedding_layer)
model.add(Convolution1D(nb_filter=100,
                        filter_length=5,
                        border_mode='valid',
                        activation='relu',
                        subsample_length=1))
model.add(GlobalMaxPooling1D())
model.add(Dense(128,activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x_train_DL,y_train_DL,epochs=20)
ans = model.predict(x_test_DL)
labels = [np.where(r==1)[0][0] for r in y_test_DL]
ans = np.argmax(ans,axis=1)
accuracy_score(ans,labels)
results(ans,labels)

please tell me the solution of this code

TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'

**Comment by Philmod** [comment]
Hi,

To ask for help from other Kaggle users, please use the forums: https://www.kaggle.com/discussion

**Comment by Gewei0102** [comment]
i have same problem can you help me
