### ISSUE TITLE
Add support for conda in online Kaggle kernels

### ISSUE THREAD

**Issue by gvyshnya** [Kaggle/docker-python#97]
It would be nice to use ability to install new packages via conda package manager (https://conda.io/docs/intro.html) in online Kaggle kernels.

**Comment by nerdcha** [comment]
Yes, that's something we're planning to introduce soon. Thanks for the suggestion!

**Comment by mlisovyi** [comment]
Has this been ever implemented?

**Comment by crawforc3** [comment]
@mlisovyi You can now pip install packages from the settings tab in Kernels.

**Comment by mlisovyi** [comment]
pip is nice, but it seems to have a different selection of packages. For example, in context of an attempt to install vowpalwabbit python package via the same pip interface, I would want to pre-install `boost` (a newer version than 0.1, that i see installed), `libboost` and `py-boost`. This can be done "easily" via conda: `conda install -c anaconda boost` ("easily" = "it worked locally on my machine"), but i did not manage to get those packages via pip installation.

**Comment by crawforc3** [comment]
Yeah, it would be nice to have both. Thanks for the suggestion! In the meantime, if there's a package you would like feel free to make a pull request and add it to the Dockerfile.
