### ISSUE TITLE
add EasyOCR for competition purposes

### ISSUE THREAD

**Issue by rafmacalaba** [Kaggle/docker-python#970]
Hello,

I emailed Addison Howard for this issue and would like to request to add [easyocr](https://github.com/JaidedAI/EasyOCR) to the docker-python of kaggle notebooks.

Heres the reply of Howard re the matter.
![image](https://user-images.githubusercontent.com/30100644/110878709-a541bc80-8316-11eb-8c1b-8a25c5571c9d.png)

Hope it'll be integrated and deployed soon :)

Thanks,
Rafael

**Comment by Philmod** [comment]
Hi Rafael,

Have you considered installing the package on your notebook directly? https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Comment by rafmacalaba** [comment]
@Philmod thanks for replying.

im gonna use the module in a competition where the internet access is disabled. thats why I want it to be like on the standard library and not install inside the notebook. please let me know if this kinda makes sense to you.

thanks

**Comment by Philmod** [comment]
Gotcha, I'll add it to the base image, but its release will take 2+ weeks.

**Comment by rafmacalaba** [comment]
oh I see! why does it take that long? but thank you!!

**Comment by Philmod** [comment]
We release a new image every 2 weeks, and we did the release this week already.

**Comment by rafmacalaba** [comment]
@Philmod may I know when will you release this? I still can't use easyocr as of now, 14 days after this was closed. Thanks!

**Comment by Philmod** [comment]
It looks like it was included in the last release: https://github.com/Kaggle/docker-python/releases/tag/da8df81cfa243148eed7af89d88ab85a88419749938682aa3d380cf04de90034

It should reach all notebooks today or tomorrow.

Thanks for your patience.

**Comment by Philmod** [comment]
@rafmacalaba It should be fully released now.

**Comment by rafmacalaba** [comment]
thanks!!


Sent from Yahoo Mail for iPhone


On Thursday, April 1, 2021, 1:03 AM, Philippe Modard ***@***.***> wrote:




@rafmacalaba It should be fully released now.
