### ISSUE TITLE
Add tflite-support 

### ISSUE THREAD

**Issue by alexovidiupopa** [Kaggle/docker-python#979]
Hi, I think tflite-support would be a good addition to the python environment as it helps with the deployment of tflite models which are becoming a standard in integrating the ML model into mobile devices' applications.

Command:
`pip install tflite-support`
[PyPI URL](
https://pypi.org/project/tflite-support/)
[Github URL](https://github.com/tensorflow/tflite-support)

Thanks.

**Comment by Philmod** [comment]
Hi @alexovidiupopa ,

Unfortunately this package doesn't meet one of our requirements (1000+ stars) to be added to the base image.

Feel free to install it in your notebooks using the pip command.

Thanks,
Philippe
