### ISSUE TITLE
Update pytorch from 1.7.0 to 1.8.1

### ISSUE THREAD

**Issue by paultimothymooney** [Kaggle/docker-python#984]
Upgrade pytorch from 1.7.0 to 1.8.

Forum post: https://www.kaggle.com/product-feedback/230489
Quote:

```
Could we get pytorch 1.8.1 in Kaggle notebooks?
Current is 1.7.0 which is known to be buggy as it was not compiled with the right cudnn. At the very least please move to 1.7.1.
```

**Comment by dfayzur** [comment]
Hello,

Any news on the Pull request? I would love to get pytorch 1.8.1 in the docker.
