### ISSUE TITLE
Update spaCy from 2.3.5 to >=3.0

### ISSUE THREAD

**Issue by horatiubota** [Kaggle/docker-python#986]
"spaCy v3.0 features new transformer-based pipelines that bring spaCy’s accuracy right up to the current state-of-the-art."

**Comment by rosbo** [comment]
Hi @horatiubota,

Our image includes `fastai` which at the moment requires `spacy` < 3.0. Once `fastai` adds support for `spacy` >= 3.0, we will move to it: https://github.com/fastai/fastai/blob/73a7ae9a56e31beb6b75d21f3b07edd9a6dd9d0d/settings.ini#L16

**Comment by gautierdag** [comment]
Also interested in getting the latest `spacy` by default in kernels (without having to go through kaggle datasets to install it without internet). I am not using `fastai`.

It doesn't seem like an upgrade to spacy>3.0+ is on the radar for `fastai` (https://github.com/fastai/fastai/search?q=spacy&type=issues), if it is a blocker for the upgrade to the kaggle docker then maybe we should flag it there @rosbo ?

**Comment by rosbo** [comment]
@gautierdag I opened an issue on the `fastai` repo. Let's see if it is on their radar. Thank you for flagging.

**Comment by skewwhiff** [comment]
Any update on this issue?

**Comment by rosbo** [comment]
`fastai` now supports spacy 3.x. We have to upgrade to `pytorch` 1.8 to upgrade `fastai`. Unfortunately, we currently have unresolvable dependencies preventing the upgrade. I am working with some package owners to expand/upgrade dependencies support.

**Comment by rosbo** [comment]
Upgraded in #1083.
